[New Atom] Relative Entropy (#1406 / #733)
cvxpy/cvxpy pull request #1427
Opened 2021-06-25 23:10 UTC by phschiele

Adding the atom as discussed in #1406 / #733 (atom, tests, documentation).

2021-06-25 23:25 UTC, phschiele commented on cvxpy/tests/test_constant_atoms.py
> -        return tuple()
Returning `tuple()` here did lead to all tests with `size = tuple()` being silently skipped.
Fixing this has caused some tests unrelated to the PR to fail. 

Some tests fail with errors which seemed to be discussed in older issues already:
```
>           raise TypeError("'h' must be a 'd' matrix of size (%d,1)" %cdim)
E           TypeError: 'h' must be a 'd' matrix of size (9,1)
```
Other tests failed for SCS, but passed for ECOS.
I was also surprised that the expected values for the `cp.norm()` needed to be updated. Were there any updates to the function which would make this expected, such as the default axis?

2021-06-26 21:54 UTC, phschiele commented on cvxpy/tests/test_conic_solvers.py
> -    def test_kl_div(self) -> None:
This test seemed to be duplicated from `test_nonlinear_atoms.py`.

I wanted to check if there is a reason to keep this duplication. If not, I can remove some more duplicates in a follow-up.

2021-06-26 23:29 UTC, SteveDiamond commented on cvxpy/tests/test_conic_solvers.py
> -    def test_kl_div(self) -> None:
Yeah the only difference I see is the test_nonlinear_atoms tests SCS and ECOS. So if you merge the two tests that's fine.

2021-06-26 23:35 UTC, SteveDiamond commented on cvxpy/tests/test_constant_atoms.py
> +     Constant([7])),
The change in value here is because cvxpy used to have an idiosyncratic definition of the L1 and LInf norm of matrices, but it was changed to match wikipedia etc.

2021-06-26 23:37 UTC, SteveDiamond commented on cvxpy/tests/test_constant_atoms.py
> -        return tuple()
That's great you uncovered this issue! That's a lot of errors :( These constant_atoms tests can be surprisingly challenging for solvers. But the cvxopt failures are clearly an input formatting issue.

2021-06-27 23:23 UTC, phschiele commented on cvxpy/tests/test_constant_atoms.py
> +     Constant([7])),
Thanks for the clarification. I noticed that it does make a difference it a list of lists or an np.array of those lists is passed:


```py
cp.norm([[-1, 2], [3, -4]], 1).value
>>>> array(7.)
cp.norm(np.array([[-1, 2], [3, -4]]), 1).value
>>>> array(6.)

# Numpy
np.linalg.norm([[-1, 2], [3, -4]],1)
>>>> 6.0
np.linalg.norm(np.array([[-1, 2], [3, -4]]),1)
>>>> 6.0

# Scipy
from scipy.linalg import norm
norm([[-1, 2], [3, -4]],1)
>>>> 6.0
norm(np.array([[-1, 2], [3, -4]]), 1)
>>>> 6.0
```

This is due to the transpose in the following line in the `ndarray_interface`:
https://github.com/cvxpy/cvxpy/blob/693a58a7d784bca7c0b6460f462ec22326555f6d/cvxpy/interface/numpy_interface/ndarray_interface.py#L45-L46

I know there are different conventions around how to parse such lists, so it is most likely expected.

2021-06-28 01:34 UTC, SteveDiamond commented on cvxpy/tests/test_constant_atoms.py
> +     Constant([7])),
Yeah the cvxpy parsing of lists is not aligned with numpy for historical reasons. We should change it, but it would require changing a lot of tests. Taking in lists is not a documented feature of cvxpy so we wouldn't be breaking the API though.

2021-07-02 03:39 UTC, r-barnes commented on cvxpy/atoms/elementwise/rel_entr.py
> +    def _grad(self, values) -> List[Any]:
You could try `List[Optional[whatever type rel_entr.elemwise_grad_to_diag returns]]`

2021-07-08 12:48 UTC, phschiele commented on cvxpy/atoms/elementwise/rel_entr.py
> +    def _grad(self, values) -> List[Any]:
Done in 0d5044a

2021-07-08 12:56 UTC, phschiele commented on cvxpy/tests/test_constant_atoms.py
> -        return tuple()
I have fixed most of the tests, the three cases below are still failing under CVXOPT only. Strangely, the tests pass for other solvers, and CVXOPT passes for other test cases of these atoms. Perhaps you or @rileyjmurray can give me a pointer for further investigation, as there seemed to be a discussion around this error in [issue 1147](https://github.com/cvxpy/cvxpy/issues/1147).
```py
    (cp.lambda_max, tuple(), [[[2, 0, 0], [0, 3, 0], [0, 0, 1]]], Constant([3])),
...
    (cp.matrix_frac, tuple(), [[1, 2, 3],
                               [[1, 0, 0],
                                [0, 1, 0],
                                [0, 0, 1]]], Constant([14])),
    (cp.matrix_frac, tuple(), [[1, 2, 3],
                               [[67, 78, 90],
                                [78, 94, 108],
                                [90, 108, 127]]], Constant([0.46557377049180271])),
```

2021-07-08 13:38 UTC, phschiele commented on cvxpy/tests/test_constant_atoms.py
> -        return tuple()
Looking a bit further, I found that removing the following condition and keeping the `else` case only, all tests pass:
https://github.com/cvxpy/cvxpy/blob/8c1ca2901645497748dccfe65e3b7981bf9bbe7e/cvxpy/reductions/solvers/conic_solvers/cvxopt_conif.py#L123-L130

There is already an [open PR](https://github.com/cvxpy/cvxpy/pull/1250) on this block.

2021-07-08 14:45 UTC, rileyjmurray commented on cvxpy/tests/test_constant_atoms.py
> -        return tuple()
@phschiele I'll look at this tonight.

2021-07-09 00:24 UTC, rileyjmurray commented on cvxpy/tests/test_constant_atoms.py
> -        return tuple()
@phschiele can you change lines 123 -- 127 to the following?
```
        if len_eq >= A.shape[0]:
            # Then the given optimization problem has no conic constraints.
            # This is certainly a degenerate case, but we'll handle it downstream.
            data[s.G] = None
            data[s.H] = None
```
I believe that will fix things. Let me know if it doesn't! (I made the changes on a branch that's a little old.)

2021-07-10 12:36 UTC, phschiele commented on cvxpy/tests/test_constant_atoms.py
> -        return tuple()
Many thanks, @rileyjmurray, all tests are passing after adding this fix.

2021-07-10 12:57 UTC, rileyjmurray commented on cvxpy/reductions/dcp2cone/atom_canonicalizers/rel_entr_canon.py
> +    return obj, constraints
This is identical to canonicalization for ``kl_div`` (reproduced below)
```
def kl_div_canon(expr, args):
    shape = expr.shape
    x = promote(args[0], shape)
    y = promote(args[1], shape)
    t = Variable(shape)
    constraints = [ExpCone(t, x, y)]
    obj = y - x - t
    return obj, constraints
```
Shouldn't there be some difference between the two?

2021-07-10 13:20 UTC, rileyjmurray commented on cvxpy/reductions/dcp2cone/atom_canonicalizers/rel_entr_canon.py
> +    return obj, constraints
I believe the correct return value here should be ``obj = -t``.

2021-07-10 13:29 UTC, rileyjmurray requested changes
I believe ``rel_entr`` is incorrectly being canonicalized, and that tests are passing only because ``sum(rel_entr(x,y))`` and ``sum(kl_div(x,y))`` are the same when applied to probability distributions.

2021-07-10 13:29 UTC, rileyjmurray commented on cvxpy/atoms/elementwise/rel_entr.py
> +        return xlogy(x, x/y)
SciPy ``rel_entr`` should be used instead. It will correctly identify the domain.

2021-07-10 13:29 UTC, rileyjmurray commented on cvxpy/tests/test_nonlinear_atoms.py
> +
Earlier I made a comment that I think canonicalization of rel_entr is incorrect. Looking at this test I'm more confident of that comment. It may well be that this test passes, but note that it only uses ``rel_entr`` with two probability distributions. In this case ``sum(rel_entr(x,y))`` returns the same value as ``sum(kl_div(x,y))``. A test needs to be written where these atoms are applied without using a probability distribution as input. Let me know if you need help finding such a test problem.

2021-07-11 12:29 UTC, phschiele commented on cvxpy/tests/test_nonlinear_atoms.py
> +
> I believe `rel_entr` is incorrectly being canonicalized, and that tests are passing only because `sum(rel_entr(x,y))` and `sum(kl_div(x,y))` are the same when applied to probability distributions.

@rileyjmurray I have addressed your comments in the latest commit. The test I have added is quite simple, but it is sensitive to the change in `rel_entr_canon.py` and now gives the expected results. Please let me know if you had a more practical example in mind, though. 

I have also added the SciPy function you mentioned, and I have done the same for the `kl_div` atom.

2021-07-11 14:27 UTC, rileyjmurray commented on cvxpy/tests/test_nonlinear_atoms.py
> +
Looks good. Can you add a comment like the following?
```
"""
Reference solution computed by passing the following command to Wolfram Alpha:
minimize x*log(x/y) subject to {x + y <= 1, 0 <= x, 0 <= y}
"""
```
I don't know how you personally computed the reference solution, but I did just verify it on Wolfram Alpha.

2021-07-11 14:28 UTC, rileyjmurray reviewed
I left one tiny comment about documenting a test. Once that's addressed I believe this is good to merge.

2021-07-11 17:57 UTC, phschiele commented on cvxpy/tests/test_nonlinear_atoms.py
> +
Exactly, I have used Wolfram Alpha to get external validation. Added the comment in the latest commit.

2021-07-11 21:41 UTC, rileyjmurray approved these changes
@akshayka @SteveDiamond @bstellato. Our [governance doc](https://github.com/cvxpy/org/blob/main/governance.md#non-financial-decisions) requires approval from at least half the project maintainers before changes are made to the public API. I'm approving now, but before we merge we'll need approval from one of you as well.

2021-07-11 22:39 UTC, SteveDiamond approved these changes
LGTM. Great job @phschiele !

2021-07-11 22:39 UTC, merged