pip install cvxpy[GLOP,XPRESS]
cvxpy/cvxpy pull request #1719
Opened 2022-03-20 22:02 UTC by mkoeppe

## Description
Please include a short summary of the change.
Issue link (if applicable):
Add `extras_require` mapping solver names to the pip-installable distribution providing it

## Type of change
- [X] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [ ] Add our license to new files.
- [ ] Check that your code adheres to our coding style.
- [ ] Write unittests.
- [ ] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

2022-03-21 04:06 UTC, SteveDiamond commented
This is very interesting! If we make this change, we should update the install guide. Also, mosek can be pip installed (though you need a license to solve anything).

2022-03-22 01:14 UTC, rileyjmurray requested changes
Nice work! I left comments about ``sdpt3glue`` and DSDP. Please respond to those in one form or another.

2022-03-22 01:14 UTC, rileyjmurray commented on setup.cfg
> +SDPT3 = sdpt3glue
I don't think it's accurate to say that we support SDPT3. From [the sdpt3glue documentation](https://pythonhosted.org/sdpt3glue/quickguide.html), they clearly structure things so you can call ``prob.solve(solver='SDPT3')`` on a CVXPY Problem object.

2022-03-22 01:14 UTC, rileyjmurray commented on setup.cfg
> +DSDP = cvxopt
[CVXOPT's documentation](https://cvxopt.org/userguide/coneprog.html#semidefinite-programming) says that it's DSDP interface can only be called through ``cvxopt.solvers.sdp`` rather than ``cvxopt.solvers.conelp``, so we'd actually need to update the CVXOPT interface to support DSDP.

The documentation also says that CVXOPT's DSDP interface doesn't support problems with equality constraints, so we'd need to figure out how we want to handle that (or if it's appropriate in CVXPY's context).

My suggestion is that we forgo this for the time being.

2022-03-22 01:14 UTC, rileyjmurray commented on setup.cfg
> +HIGHS = scipy>=1.6.1
This is a nice touch!

2022-03-22 01:21 UTC, mkoeppe commented on setup.cfg
> +SDPT3 = sdpt3glue
I took this from the documentation https://www.cvxpy.org/install/#install-with-sdpt3-support; I don't know anything more specific about it.

2022-03-22 11:15 UTC, rileyjmurray commented on setup.cfg
> +SDPT3 = sdpt3glue
The language there is a little different with SDPT3 than with other packages. For the main text, it doesn't say "CVXPY supports the SDPT3 solver," which would be analogous to the main text used for other solvers. I think the heading is a little misleading and should be changed. Please remove the SDPT3 line here, and then I'll approve the PR.

2022-03-22 16:41 UTC, mkoeppe commented on setup.cfg
> +SDPT3 = sdpt3glue
Done.

2022-03-22 23:44 UTC, merged

2022-03-22 23:45 UTC, mkoeppe commented
Thanks for the fix for the documentation, which I had forgotten

2022-03-22 23:48 UTC, rileyjmurray commented
You're welcome! Thanks for the PR :)