Add autoflake pre-commit; remove unused variable; remove unused pass
cvxpy/cvxpy pull request #1756
Opened 2022-04-21 13:54 UTC by yasirroni

## Description
Add autoflake pre-commit; remove unused variable; remove unused pass

Issue link (if applicable): https://github.com/cvxpy/cvxpy/issues/1750

## Type of change
- [x] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [x] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [ ] Write unittests.
- [x] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

2022-05-17 03:39 UTC, rileyjmurray requested changes
Hi @yasirroni. Wow, you made a lot of PR's at once!

I'll let @phschiele comment on if these changes to pre-commit make sense. He's the one who suggested we use pre-commit in the first place.

I would prefer that the ``pass`` statements appear in the unit tests. Those make it easier to place break points to investigate test values that are "weird" even when the test fails outright.

2022-05-17 06:10 UTC, yasirroni commented
> I would prefer that the pass statements appear in the unit tests. Those make it easier to place break points to investigate test values that are "weird" even when the test fails outright.

Okay. Shoul i git reset and force, add new commit that revert the removed pass, or you prefer just cherry-pick?

___

Anyway, this PR will add extra ms to run autoflake. But, it is still better than manually edit after violating pep8.

2022-05-22 16:23 UTC, phschiele reviewed
@yasirroni Thanks for this PR! 

In general, I like the idea of autoflake and it does not seem to have negative side effects judging by the changes. One comment would be that, as you even mention in the PR description, even relatively small convenience improvements like this do add a (development) dependency, which can go unmaintained etc. 
-> Overall in favor of adding it

I don't have a strong view on the `pass` statements, but @rileyjmurray's comment regarding debugging makes sense.

2022-05-22 16:23 UTC, phschiele commented on .pre-commit-config.yaml
> +          '--'
Nit: Is this line required?

2022-05-23 07:15 UTC, yasirroni commented on .pre-commit-config.yaml
> +          '--'
Those are setting to set how autoflake work. Default mode, it will not do those three. `--ignore-init-module-imports` only relevant if we use `--remove-all-unused-imports`.

2022-06-25 21:48 UTC, phschiele commented on .pre-commit-config.yaml
> +          '--'
Understood, I was referring only to the trailing `--` in l.12, though, which seems redundant.

2022-06-25 21:50 UTC, phschiele commented
@yasirroni It would be great if you could incorporate @rileyjmurray's suggested change so we can get this PR merged.

2022-06-27 23:25 UTC, yasirroni commented on .pre-commit-config.yaml
> +          '--'
No, it was not redundant and explained by pre-commit author in their issue to be used for ending arguments. Need to dig the issue if want to find the specific post.

2022-06-27 23:27 UTC, yasirroni commented
> @yasirroni It would be great if you could incorporate @rileyjmurray's suggested change so we can get this PR merged.

So, the only modification requested is to not remove the pass? Okay then. Will work on that soon.

2022-06-27 23:39 UTC, yasirroni commented on .pre-commit-config.yaml
> +          '--'
Note that autoflake did not support pyproject.toml

2022-06-28 01:16 UTC, yasirroni commented
Since the main functionality of autoflake is to remove unused pass, the new arguments will skip all check in tests.

2022-06-28 04:34 UTC, SteveDiamond commented
LGTM

2022-06-28 04:35 UTC, SteveDiamond approved these changes

2022-06-28 04:35 UTC, merged