Added a new atom function con_num()
cvxpy/cvxpy pull request #1768
Opened 2022-05-08 19:08 UTC by parthb83

## Description
Added a new atom function `con_num()` to compute the condition number.
Added the atom file, canonicalization file and written unittests for the same.
`con_num(A) = lambda_max(A) / lambda_min(A)`

Issue link (if applicable): #858 

## Type of change
- [x] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [x] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [x] Write unittests.
- [x] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

2022-05-08 19:10 UTC, parthb83 commented
@rileyjmurray @phschiele I am currently facing issues in writing test for `test_constant_atoms.py`

2022-05-08 19:26 UTC, SteveDiamond commented on cvxpy/atoms/con_num.py
> +        return True
Should be False

2022-05-08 19:27 UTC, SteveDiamond commented on cvxpy/reductions/dcp2cone/atom_canonicalizers/con_num_canon.py
> +"""
This reduction is in the wrong place. It's a dqcp2dcp reduction.

2022-05-08 19:28 UTC, SteveDiamond commented
Thanks for getting started on this! DQCP atoms are fairly different from DCP atoms like xexp. I would suggest discussing further in the Discord about how exactly to do this.

2022-05-08 19:33 UTC, parthb83 commented on cvxpy/reductions/dcp2cone/atom_canonicalizers/con_num_canon.py
> +"""
But the dqcp2dcp folder has no subfolder for atom_canonicalization. Should we make a new folder for this or just add the canon file in the dqcp2dcp folder?

2022-05-08 19:42 UTC, SteveDiamond commented on cvxpy/reductions/dcp2cone/atom_canonicalizers/con_num_canon.py
> +"""
Hmm you're right, dqcp2dcp pulls from dcp atom_canonicalization. That's very strange. @akshayka is their a reason for not having a separate dqcp2dcp atom_canonicalization folder?

2022-05-12 05:03 UTC, rileyjmurray commented
Chiming in: I think it should be ``cond_num`` rather than ``con_num``. The prefix "con" is often used for other purposes in building constrained optimization models :)

2022-05-12 08:06 UTC, keithbriggs commented
I would go further and say it should be `condition_number`.

This would fit the general principle that the less frequently used a function is, the longer its name should be.  It makes code more readable.

2022-05-12 14:40 UTC, rileyjmurray commented
@keithbriggs makes a good point. This atom will only be used in very specific situations. It's unlikely that it will be used in more than one place in a given optimization model. @akshayka @SteveDiamond @phschiele @bstellato what do you all think?

2022-05-12 16:17 UTC, SteveDiamond commented
I vote for ``condition_number``

2022-05-17 03:15 UTC, rileyjmurray commented
Hi @parthb83! Just checking in on this. I see that our CI tests are failing due to code style issues. You can prevent that by following the instructions here: https://www.cvxpy.org/contributing/index.html#code-style.

2022-05-17 05:52 UTC, parthb83 commented
> Hi @parthb83! Just checking in on this. I see that our CI tests are failing due to code style issues. You can prevent that by following the instructions here: https://www.cvxpy.org/contributing/index.html#code-style. It would also be good if you could push changes to resolve Steven Diamond's comments.

Hi @rileyjmurray! I've just pushed the desired changes but I think the main problem is that the `condition_number_canon.py` reduction is in the wrong place and it should be in `dqcp2dcp` reduction. Since that folder doesn't have a subfolder for `atom_canonicalization`, I cannot move the reduction there. I discussed the same with Steven on Discord and he also said that there is little we can do as @akshayka knows more about the `dqcp2dcp` stuff, so I'm still waiting for his reply.

2022-05-17 16:48 UTC, akshayka commented
A quasiconvex atom is replaced with a parametrized family of its sub/superlevel sets here:

cvxpy/reductions/dqcp2dcp/sets.py

If I recall correctly the value of the parameter can for some atoms change its set in a way that I was unable to capture using the way we canonicalize DCP atoms, so the the sets essentially function as lazy constraints that are evaluated/constructed when the parameter t is known.

If on the other hand you're just rewriting cond_number to be DQCP compliant, then you shouldn't have to write a custom sub/superlevel set for it. I don't have a place for such lowerings but we could make one.

2022-05-17 20:21 UTC, parthb83 commented
Interesting! `SCS == 2.1.2` was able to solve the test for `1 <= A[0], A[1] <= 2` but couldn't solve it accurately for `0 <= A[0], A[1] <= 2`, although in my opinion, both the test are almost identical and there shouldn't have been any problem for SCS 2.1.2 to solve the latter one (The answer for both the constraints is the lower bound of A[0] and A[1]). 

Anyways, leaving that aside, I guess the only thing left now is to update the docs. Other than that, can you please review the changes @SteveDiamond, @rileyjmurray?

2022-05-17 22:21 UTC, SteveDiamond commented on cvxpy/atoms/condition_number.py
> +            raise ValueError("The argument '%s' to con_num must resolve to a square matrix."
con_num -> condition_number

2022-05-17 22:21 UTC, SteveDiamond commented on cvxpy/atoms/condition_number.py
> +        return (False, False)
I believe this is positive so should return (True, False)

2022-05-17 22:22 UTC, SteveDiamond commented on cvxpy/reductions/dqcp2dcp/sets.py
> +            A >> 0,
A >> 0 -> PSD(A)

2022-05-17 22:23 UTC, SteveDiamond commented on cvxpy/tests/test_dqcp.py
> +        prob.solve(cp.SCS, qcp=True)
can we test something about the output? Ideally we would know the optimal value and check that the variable attains it. Right now you aren't testing the correctness of the canonicalization.

2022-05-18 04:58 UTC, rileyjmurray commented on cvxpy/atoms/condition_number.py
> +        return (False, False)
@parthb83 in general it's good to do some digging into an atom to figure out the appropriate properties. For example, you can learn about condition numbers here: https://en.wikipedia.org/wiki/Condition_number#Matrices.

2022-05-18 07:27 UTC, keithbriggs commented on cvxpy/atoms/condition_number.py
> +            raise ValueError("The argument '%s' to con_num must resolve to a square matrix."
Also, shouldn't we be using f-strings rather than the old %-formatting?

2022-05-18 15:07 UTC, parthb83 commented on cvxpy/tests/test_dqcp.py
> +        prob.solve(cp.SCS, qcp=True)
So I tested this for the output and the output isn't accurate enough. For the above constraints, the output was
```
[[2.00004109, 0.97275377]
 [0.97275377, 2.99999668]]
```
which is close to the actual output but not accurate enough. Do you have any idea how can we increase the accuarcy of canonicalization?

2022-05-18 18:02 UTC, SteveDiamond commented on cvxpy/tests/test_dqcp.py
> +        prob.solve(cp.SCS, qcp=True)
You can increase the accuracy by setting solver options (https://www.cvxpy.org/tutorial/advanced/index.html#setting-solver-options). But it would be better to just reduce the accuracy of the assert. Search the codebase for ``assertItemsAlmostEqual`` and use the ``places`` argument to control accuracy.

2022-05-18 18:05 UTC, parthb83 commented on cvxpy/tests/test_dqcp.py
> +        prob.solve(cp.SCS, qcp=True)
But is the following accuracy acceptable for the canonicalization?

2022-05-18 18:27 UTC, SteveDiamond commented on cvxpy/tests/test_dqcp.py
> +        prob.solve(cp.SCS, qcp=True)
I see what you mean, the accuracy is pretty bad. Try solving it with ``prob.solve(solver=cp.SCS, qcp=True, eps=1e-8, max_iters=20_000)``. If that doesn't improve things it's ok. We can still merge the PR and investigate it more on our side.

2022-05-18 19:43 UTC, parthb83 commented on cvxpy/tests/test_dqcp.py
> +        prob.solve(cp.SCS, qcp=True)
> I see what you mean, the accuracy is pretty bad. Try solving it with `prob.solve(solver=cp.SCS, qcp=True, eps=1e-8, max_iters=20_000)`. If that doesn't improve things it's ok. We can still merge the PR and investigate it more on our side.

This didn't change the answer much so I'm checking the answer in `test_dqcp.py` for just 1 place.

2022-05-19 17:13 UTC, SteveDiamond approved these changes
LGTM

2022-05-20 14:10 UTC, rileyjmurray commented
I'll review this weekend, and if it looks good I'll merge.

2022-06-08 16:39 UTC, SteveDiamond commented
@rileyjmurray where did we land with this PR?

2022-06-09 02:41 UTC, rileyjmurray requested changes
Sorry for the delay on this. There's a canonicalization inefficiency I'd like addressed. I also have a minor comment on the docstring. Lastly, I'll check out this code locally and run the test case. I'm curious if using a solver other than SCS can lead to better results.

2022-06-09 02:41 UTC, rileyjmurray commented on cvxpy/atoms/condition_number.py
> +    """
State that ``A`` needs to be PSD.

2022-06-09 02:41 UTC, rileyjmurray commented on cvxpy/reductions/dqcp2dcp/sets.py
> +            PSD(tmp_expr2)]
``A == A.T`` is an inefficient way to enforce symmetry. You only need ``n(n-1)/2`` of these ``n**2`` constraints. We should also check if ``A`` is declared as symmetric before bothering to enforce symmetry here.

2022-06-09 02:41 UTC, rileyjmurray commented on cvxpy/tests/test_dqcp.py
> +        prob.solve(cp.SCS, qcp=True)
Let me check with another solver.

2022-06-29 00:33 UTC, SteveDiamond commented
ping. You can use the ``upper_tri`` atom to reduce the number of constrains (i.e., ``upper_tri(A) == upper_tri(A.T)``).

2022-07-01 18:54 UTC, SteveDiamond commented
@rileyjmurray all the requested changes have been made now. could you review/approve?

2022-07-01 19:28 UTC, SteveDiamond commented
Test failures are unrelated to PR. Some kind of package change with one of the MIP solvers...

2022-07-01 19:42 UTC, rileyjmurray commented
Approved!

On Fri, Jul 1, 2022 at 12:28 PM Steven Diamond ***@***.***>
wrote:

> Test failures are unrelated to PR. Some kind of package change with one of
> the MIP solvers...
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cvxpy/cvxpy/pull/1768#issuecomment-1172655727>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACRLIFG4SKQMX6QGRDNUZTDVR5BHJANCNFSM5VMKI66Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-07-01 21:19 UTC, merged