Atom for the Von Neumann Entropy
cvxpy/cvxpy pull request #1789
Opened 2022-05-28 06:50 UTC by aryamanJgl

In this PR I add support for the Von Neumann Entropy as an `Atom`. The `vn_entr` class itself lies in `cvxpy/atoms`, and it's respective Canonicalization method lies in `cvxpy/reductions/dcp2cone/atom_canonicalizers`, finally, the tests reside in `cvxpy/tests/test_vn_entr.py`. I chose to omit the `_grad` method for this PR as per @SteveDiamond's advice.

The Canonicalization procedure is based off of  *Proposition-4* of [THIS](https://link.springer.com/article/10.1007/s10107-016-0998-2) paper.

I only wrote 4 test cases for the atom, and would be open to adding more if needed (though I think they cover a decent variety).

2022-05-28 07:33 UTC, keithbriggs commented
"it's respective Canonicalization method" should be "its respective Canonicalization method".

2022-05-28 22:32 UTC, rileyjmurray commented
The failing tests seem to be for versions of Python where SCS 2.1.2 is installed, rather than SCS 3. I ran the tests on my laptop with SCS 3 and they passed, but the return code was "inaccurate" even after I increased ``max_iters`` to 500,000. So I think we'll need MOSEK for these tests to pass.

2022-05-28 22:52 UTC, rileyjmurray reviewed
@aryamanJgl here are some things to be aware of. I'm investigating other stuff and hopefully will provide more comments soon.

2022-05-28 22:52 UTC, rileyjmurray commented on cvxpy/tests/test_vn_entr.py
> +        cons1 = N >> 0
The constraint that ``N >> 0`` is redundant, since you already declared ``PSD = True`` for ``N``. Same comment goes for other tests.

2022-05-28 22:52 UTC, rileyjmurray commented on cvxpy/tests/test_vn_entr.py
> +            (N, expect_N)
Here you're reassigning ``N``. That should cause tests to fail since ``expect_N`` is supposed to be with respect to the original variable.

2022-05-28 22:57 UTC, rileyjmurray commented on cvxpy/tests/test_vn_entr.py
> +        cons3 = N[2][0] == 1e-2
This is inconsistent with ``expect_N``.

2022-05-28 23:02 UTC, rileyjmurray commented
@aryamanJgl after running the tests with MOSEK I'm getting that they all fail. Something is going wrong in ``vn_entr`` canonicalization, since MOSEK is reporting that the problem is unbounded even though the feasible set should be compact.

2022-05-28 23:14 UTC, rileyjmurray commented
@aryamanJgl here is a tiny example of a test that's failing:
```
N = cp.Variable(shape=(2, 2), PSD=True)
constraints = [cp.trace(N) <= 1,
               N[0, 1] == -0.1,
               ]
objective = cp.Maximize(cp.vn_entr(N))
prob = cp.Problem(objective, constraints)
prob.solve(verbose=True)  # infeasible
```
The solver (SCS or MOSEK) says the problem is infeasible, but ``N = [[0.5, -0.1],[-0.1, 0.5]]`` is feasible (its eigenvalues are 0.4 and 0.6).

2022-05-29 06:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=1789) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=1789) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: aryamanJgl<br/>:white_check_mark: rileyjmurray<br/>:x: Riley Murray<br/><hr/>**Riley Murray** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cvxpy/cvxpy?pullRequest=1789) it.</sub>

2022-05-29 07:06 UTC, keithbriggs commented
Isn't this a another case where a long name is needed? vn_entr is completely cryptic. I would go for von_neumann_entropy.

2022-05-29 15:07 UTC, rileyjmurray commented
> Isn't this a another case where a long name is needed? vn_entr is completely cryptic. I would go for von_neumann_entropy.

That's a good point. Although I'd vote for ``von_neumann_entr``, since basic (Shannon) entropy is just ``entr``. In the near future we'll have a bunch of other atoms where we'll want to continue to use existing abbreviations, like ``quantum_rel_entr`` and ``operator_rel_entr``.

@aryamanJgl if you don't object, how about you change it to ``von_neumann_entr``?

2022-06-07 03:03 UTC, rileyjmurray commented on cvxpy/atoms/von_neumann_entr.py
> +        super(von_neumann_entr, self).__init__(N)
This function needs a docstring.

2022-06-07 03:08 UTC, rileyjmurray requested changes
Mostly looks good! The main thing that stands out is the need for documentation. The docstring for ``von_neumann_entr`` is missing, and the web docs need to be updated to mention this new atom. I also left minor comments on the tests.

2022-06-07 03:08 UTC, rileyjmurray commented on cvxpy/atoms/von_neumann_entr.py
> +        super(von_neumann_entr, self).__init__(N)
This function needs a docstring.

2022-06-07 03:08 UTC, rileyjmurray commented on cvxpy/tests/test_von_neumann_entr.py
> +        trMax = 0.9
This should be ``trMin``.

2022-06-07 03:08 UTC, rileyjmurray commented on cvxpy/tests/test_von_neumann_entr.py
> +        obj_pair = (objective, -0.13372929515039528)
You should provide the code used to generate this test data. (At least, the code to generate ``expect_N``.)

2022-06-21 14:37 UTC, rileyjmurray approved these changes
Looks good to me!

2022-06-21 14:38 UTC, rileyjmurray commented
@SteveDiamond can you review this PR? We need to project maintainers to approve before merging, since this affects the public API.

2022-06-21 16:23 UTC, SteveDiamond commented on cvxpy/atoms/von_neumann_entr.py
> +        if hasattr(N, 'value'):
Normally we do ``isinstance(N, np.ndarray)``.

2022-06-21 16:25 UTC, SteveDiamond commented on cvxpy/reductions/dcp2cone/atom_canonicalizers/von_neumann_entr_canon.py
> +        expr_r = lambda_sum_largest(N, r)
This is going to create a massive internal representation, right? Are we sure we this is how we want to do the canonicalization? For instance, doesn't lambda_sum_largest apply ``N >> 0``? That should only happen once. Please ignore this comment if I'm totally off.

2022-06-21 16:26 UTC, SteveDiamond approved these changes
Approved subject to my comments. Also shouldn't we add it to the table of atoms?

2022-06-23 13:35 UTC, rileyjmurray commented on cvxpy/reductions/dcp2cone/atom_canonicalizers/von_neumann_entr_canon.py
> +        expr_r = lambda_sum_largest(N, r)
@SteveDiamond the representation will indeed be large, but ``lambda_sum_largest`` doesn't impose any redundant constraints across these function calls. One thing @aryamanJgl can do is use ``range(1, n)`` instead of ``range(1, n+1)`` and then simplify ``lambda_sum_largest(N, n) == trace(N)``.

2022-06-23 13:40 UTC, rileyjmurray commented
@aryamanJgl please address my response to Steven's comment. Also, there are two things to do for the docs.

1. ``von_neumann_entr`` isn't an elementwise atom. It should be documented [here](https://github.com/cvxpy/cvxpy/blob/master/doc/source/api_reference/cvxpy.atoms.other_atoms.rst), not at ``doc/source/api_reference/cvxpy.atoms.elementwise.rst``.
2. Add ``von_neumann_entr`` to the table of "Scalar Functions" [here](https://github.com/cvxpy/cvxpy/blob/master/doc/source/tutorial/functions/index.rst).

2022-06-23 13:42 UTC, rileyjmurray commented on cvxpy/atoms/von_neumann_entr.py
> +        if hasattr(N, 'value'):
Is ``values[0]``guaranteed to be a certain type? This check makes sure Expression objects work and plain numeric numpy ndarrays work.

2022-06-23 16:26 UTC, SteveDiamond commented on cvxpy/atoms/von_neumann_entr.py
> +        if hasattr(N, 'value'):
values[0] is supposed to be an ndarray, float, or possibly a scipy sparse matrix. You can leave the attribute check, it was just something that stuck out to me.

2022-06-23 20:48 UTC, merged