contribute a atomic operation of trace(inv(X))
cvxpy/cvxpy pull request #1822
Opened 2022-07-09 06:10 UTC by imcjp

## Description
Hello, since the current cvxpy does not support the atomic operation $\operatorname{trace}\left( \operatorname{inv}\left( X \right) \right)$ where $X$ is PSD, but I need that feature in my research work. I designed the atomic operation and contributed it to the cvxpy community. Our main work is to demonstrate that $\operatorname{trace}\left( \operatorname{inv}\left( X \right) \right)$ is convex and to implement an equivalent cone form of it. In addition, we provided an example in "examples/ex_tr_inv.py"

The code we submitted in
1. "cvxpy/atoms/tr_inv.py"
2. "cvxpy/reductions/dcp2cone/atom_canonicalizers/tr_inv_canon.py"
3. "cvxpy/reductions/dcp2cone/atom_canonicalizers/tr_inv_canon.py"
4. "cvxpy/atoms/__init__.py"
5. "cvxpy/reductions/dcp2cone/atom_canonicalizers/__init__.py"
6. "examples/ex_tr_inv.py"

## Type of change
- [ ] New feature (backwards compatible)
- [*] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [*] Add our license to new files.
- [*] Check that your code adheres to our coding style.
- [*] Write unittests.
- [*] Run the unittests and check that they’re passing.
- [*] Run the benchmarks to make sure your change doesn’t introduce a regression.

2022-07-09 06:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=1822) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=1822) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cvxpy/cvxpy?pullRequest=1822) it.</sub>

2022-07-09 18:14 UTC, SteveDiamond commented
This is a great contribution! The next step is to add a test in ``test_atoms.py``, where you solve a problem involving ``tr_inv``.

2022-07-09 19:20 UTC, rileyjmurray commented on cvxpy/atoms/tr_inv.py
> +Copyright 2013 Steven Diamond
Copyright 2022, the CVXPY authors

2022-07-09 19:20 UTC, rileyjmurray commented on cvxpy/atoms/tr_inv.py
> +#############################################
Remove

2022-07-09 19:21 UTC, rileyjmurray commented on cvxpy/reductions/dcp2cone/atom_canonicalizers/tr_inv_canon.py
> +Copyright 2013 Steven Diamond
Copyright 2022, the CVXPY authors

2022-07-09 19:21 UTC, rileyjmurray commented on cvxpy/reductions/dcp2cone/atom_canonicalizers/tr_inv_canon.py
> +#############################################
Please remove these lines

2022-07-09 19:23 UTC, rileyjmurray commented on cvxpy/reductions/dcp2cone/atom_canonicalizers/tr_inv_canon.py
> +        ui = Variable((1,1))
Instead of declaring a bunch of scalar variables, declare a variable of shape ``(n, 1)`` before entering this loop. You can also declare ``ei`` before the start of this loop and then update it by ``ei *= 0`` and ``ei[i] = 1``.

2022-07-09 19:24 UTC, rileyjmurray commented on examples/ex_tr_inv.py
> +Copyright 2013 Steven Diamond
Copyright 2022, the CVXPY authors

2022-07-09 19:24 UTC, rileyjmurray commented on examples/ex_tr_inv.py
> +print(X.value)
Add a blank line at the end of the file

2022-07-09 19:26 UTC, rileyjmurray requested changes
Hi @imcjp! Thanks so much for your contribution. I've provided some initial feedback. As Steven said, we'll also need you to add some tests.  In addition to that, we'll need to you update our web documentation. (Look at the recently merged PR for ``von_neumann_entr`` to see what files should be changed.)

2022-07-10 04:05 UTC, imcjp commented on cvxpy/atoms/tr_inv.py
> +Copyright 2013 Steven Diamond
Thank you for your reminder, I have changed the Copyright in the revised version.

2022-07-10 04:06 UTC, imcjp commented on examples/ex_tr_inv.py
> +Copyright 2013 Steven Diamond
Thank you for your reminder, I have changed the Copyright in the revised version.

2022-07-10 04:06 UTC, imcjp commented on cvxpy/reductions/dcp2cone/atom_canonicalizers/tr_inv_canon.py
> +Copyright 2013 Steven Diamond
Thank you for your reminder, I have changed the Copyright in the revised version.

2022-07-10 04:06 UTC, imcjp commented on cvxpy/atoms/tr_inv.py
> +#############################################
Thanks for the reminder, I have removed it in the revised version.

2022-07-10 04:07 UTC, imcjp commented on cvxpy/reductions/dcp2cone/atom_canonicalizers/tr_inv_canon.py
> +#############################################
Thank you for the reminder, I have removed it in the revised version.

2022-07-10 04:12 UTC, imcjp commented on cvxpy/reductions/dcp2cone/atom_canonicalizers/tr_inv_canon.py
> +        ui = Variable((1,1))
Thank you for your advice. I have tried to declare ei before the start of this loop and then update it, but I got an incorrect result. Because such a change would cause multiple PSD constraints to share the same ei, updating any one ei would cause the other ei to be updated incorrectly as well.
Therefore, I do not accept the proposal.

2022-07-10 04:14 UTC, imcjp commented on examples/ex_tr_inv.py
> +print(X.value)
I have added a blank line at the end of the file. Meanwhile, I have updated the example to tests/test_atoms.py.

2022-07-10 04:20 UTC, imcjp commented on cvxpy/atoms/tr_inv.py
> +#############################################
Besides, how do I do to update your web documentation? Do you have a guide for this?

2022-07-14 15:01 UTC, rileyjmurray requested changes
Looking better! I have requests for the numerical implementation and the tests.

2022-07-14 15:01 UTC, rileyjmurray commented on cvxpy/tests/test_atoms.py
>  class TestDotsort(BaseTest):
A test shouldn't print values, it should use assert statements.

In this case you can compute a reference solution by imagining that ``X`` is diagonal. Suppose ``T = 2`` and ``X = diag([a, b])``. Then the constraint that ``tr(X) == 1`` becomes ``a + b == 1`` and the objective ``tr_inv(X)`` is equal to ``1 / a + 1 / (1 - a)``, which leads to an optimal value achieved at ``a = b = 1/2``. In larger problems I believe the solution will be for all eigenvalues of ``X`` to be equal to ``1/T``.  This is one good test case, but we should have another.

2022-07-14 15:03 UTC, rileyjmurray commented on cvxpy/atoms/tr_inv.py
> +        return np.trace(LA.inv(symm))
Also, I'm not sure if we should compute the projection onto the set of symmetric matrices before computing tr_inv. My feeling is that if ``values[0]`` isn't Hermitian then the numeric value should return ``np.inf``.

2022-07-15 08:57 UTC, imcjp commented on cvxpy/atoms/tr_inv.py
> +
Thank you for your advice, I have added the requirement in the comments.

2022-07-15 15:43 UTC, rileyjmurray requested changes
Looking even better! I still have a couple of follow-up comments. Please address when you get a chance.

2022-07-15 15:43 UTC, rileyjmurray commented on cvxpy/atoms/tr_inv.py
> +    # Any argument shape is valid.
This comment isn't correct; shape must be square.

2022-07-15 15:43 UTC, rileyjmurray commented on cvxpy/atoms/tr_inv.py
> +        symm = (values[0] + values[0].T)/2
Use conjugate transpose, to properly handle complex Hermitian matrices.

2022-07-15 15:43 UTC, rileyjmurray commented on cvxpy/tests/test_atoms.py
> +                    self.assertAlmostEqual(bestX[i][j], 0.0) # Others are 0
Do

```
X_actual = X.value
X_expect = np.eye(T) / T
self.assertItemsAlmostEqual(X_actual, X_expect, places=4)
```

2022-07-18 14:33 UTC, imcjp commented on cvxpy/atoms/tr_inv.py
> +    # Any argument shape is valid.
This comment has been modified.

2022-07-18 14:34 UTC, imcjp commented on cvxpy/tests/test_atoms.py
> +                    self.assertAlmostEqual(bestX[i][j], 0.0) # Others are 0
The code has been modified

2022-07-22 17:43 UTC, SteveDiamond commented
@rileyjmurray are your comments fully addressed?

2022-07-23 05:18 UTC, rileyjmurray approved these changes

2022-07-23 18:16 UTC, SteveDiamond approved these changes

2022-07-23 18:17 UTC, merged

2022-07-23 18:17 UTC, SteveDiamond commented
Great job @imcjp!