Atom for the scalar relative entropy cone: `ExpConeQuad`
cvxpy/cvxpy pull request #1833
Opened 2022-07-21 18:45 UTC by aryamanjeendgar

In this PR, I add support for the scalar relative entropy cone via the approximation method that was defined in Theorem-3 of [THIS paper](https://arxiv.org/abs/1705.00812). 

The sREC also happens to be directly connected (under a permutation and sign change of the arguments) to the exponential cone, and @rileyjmurray added a method for conversion from `ExpCone` to `ExpConeQuad` to that end. 

As it stands now, the biggest shortcoming in the current state of the PR, are two things:
1. Lack of support for elementwise application of `ExpConeQuad` to vector variables --- this is due to the usage of the `quad_over_lin` atom for implementing the semidefinite approximation outlined in theorem-3 of the above mentioned paper (currently, one of the test cases has been explicitly modified to make it pass)
2. Lack of proper experimentation for arriving on a sensible set of defaults for the parameters $(m,k)$ in the approximation --- while $m$ is related to the quadrature approximation used in the procedure, $k$, doesn't lend itself to any kind of an intuitive interpretation.

There's also some documentation missing, but I will add that in the next few commits.

Thank you!

2022-07-21 20:24 UTC, SteveDiamond commented on cvxpy/reductions/cone2cone/common2common.py
> +        super(Common2Common, self).__init__(
why do we have the new common2common for ``ExpConeQuad``?

2022-07-21 20:25 UTC, SteveDiamond commented on cvxpy/reductions/cone2cone/common2common.py
> +        expr = quad_over_lin(Z[i+1], x)
The two options here are to implement vectorized ``quad_over_lin`` or do a vectorized ``SOC`` representation directly in this block.

2022-07-22 04:00 UTC, rileyjmurray commented on cvxpy/reductions/cone2cone/common2common.py
> +        super(Common2Common, self).__init__(
@SteveDiamond this was my suggestion. The idea is that ``common2common`` could handle things like "power cone to exponential cone" and "2-by-2 SDP to SOCP". Although, strictly speaking, this is an approximation and not an exact reformulation. So it might make sense to make an ``approximations`` canonicalization path and put this there instead. We'll have more cones like ``OperatorRelativeEntropyCone`` that could go in such a future canonicalization path.

2022-07-22 04:12 UTC, rileyjmurray commented on cvxpy/constraints/exponential.py
> +# from cvxpy.expressions.constants.constant import Constant
Why is this commented out? Remove it if it isn't needed.

2022-07-22 04:22 UTC, rileyjmurray commented on cvxpy/reductions/cone2cone/common2common.py
> +Copyright 2021 the CVXPY developers
2022

2022-07-22 04:26 UTC, rileyjmurray commented on cvxpy/constraints/exponential.py
> +        return
The math associated with this task would be nontrivial for an undergrad. If you want to work on this question then I can give you some stepping stones that would make building up to this task less daunting.

2022-07-27 11:31 UTC, aryamanjeendgar commented
Just wanted to kick off an important discussion regarding where `ExpConeQuad` should be placed within the web documentation.

So, as it stands right now, semantically, `ExpConeQuad`  pretty much offers an alternative (which can be made arbitrarily accurate by tweaking $(m,k)$) canonicalization pathway to the standard `ExpCone`; hence, I felt that it might be a bit awkward to place it within all the other constraint classes (like `ExpCone`, `SOC`, PowConeND` etc.) since it is _functionally_ redundant to `ExpCone` from a modeling perspective, and instead, expose it through the `as_expconequad(. , .)` method that has been written for converting from `ExpCone` to `ExpConeQuad`.

I would like to hear everyone's thoughts on this! @SteveDiamond @rileyjmurray

2022-07-27 14:51 UTC, rileyjmurray commented
> Just wanted to kick off an important discussion regarding where `ExpConeQuad` should be placed within the web documentation.
> 
> So, as it stands right now, semantically, `ExpConeQuad` pretty much offers an alternate (which can be made arbitrarily accurate by tweaking (m,k) ) canonicalization pathway to the standard `ExpCone`; hence, I felt that it might be a bit awkward to place it within all the other constraint classes (like `ExpCone`, `SOC`, `PowConeND` etc.) since it is _functionally_ redundant to `ExpCone` from a modeling perspective, and instead, expose it through the `as_expconequad(. , .)` method that has been written for converting from `ExpCone` to `ExpConeQuad`.

I'd be in favor of retaining an ``ExpConeQuad`` class but not really suggesting that users work with that class. Rather, they should use the ``ExpCone`` class and then call ``con.as_expconequad(m k)``. How about this:

- ``ExpConeQuad`` gets a disclaimer at the top of its docstring saying that we don't promise stability of its API. However, we do promise stability of the API for ``ExpCone.as_expconequad``.
-  The docstring for ``ExpCone.as_expconequad`` contains a meaningful amount of information as to how the approximation works, but it wouldn't be as detailed as the documentation for ``ExpConeQuad``.

If we go in that direction then I think we would expose ``ExpConeQuad`` in [this part of the web docs](https://www.cvxpy.org/api_reference/cvxpy.constraints.html) like every other Constraint class.

2022-07-27 14:52 UTC, rileyjmurray commented
@aryamanjeendgar the style check with ``isort`` is failing. Take a look and fix when you get a chance.

2022-07-28 15:54 UTC, rileyjmurray requested changes
I think we should rename several things:
1. ``common2common.py`` should be renamed to ``approximations.py``.
2. ``ExpConeQuad`` should be renamed to ``RelEntrQuad``. 
3. ``ExpCone.as_expconequad`` should be ``ExpCone.as_quad_approx``.

When making these changes, be sure to update docstrings of functions in the current ``ExpConeQuad`` class accordingly. You should also update variable names used in your changes to ``solving_chain.py`` to reflect the new semantics of ``approximations.py``.

There were a couple of other small points but I think that'll do it for now.

2022-07-28 15:54 UTC, rileyjmurray commented on cvxpy/constraints/exponential.py
> +        $\\tau$ in the exponential cone.
Two points.
1. These might be Expression objects, not necessarily Variable objects.
2. These expressions aren't constrained to lay in the exponential cone. They're constrained to lay in "this approximation of" [the scalar relative entropy cone].

2022-07-28 15:54 UTC, rileyjmurray commented on cvxpy/reductions/cone2cone/common2common.py
> +}
Can you remind me what purpose this serves?

2022-07-28 15:54 UTC, rileyjmurray commented on cvxpy/reductions/cone2cone/common2common.py
> +from cvxpy.atoms.quad_over_lin import quad_over_lin
I don't think we need ``quad_over_lin`` anymore.

2022-07-28 15:54 UTC, rileyjmurray commented on cvxpy/reductions/solvers/solving_chain.py
> +        sim_cos = COMMON_CONES[co]  # get the set of required simple cones
Remark: I don't like this naming convention of ``COMMON_CONES``.

2022-07-28 15:54 UTC, rileyjmurray commented on cvxpy/tests/test_cone2cone.py
> +        con4 = ExpCone(s[2], e[2], x[2]).as_expconequad(5, 5)
The test should use a vectorized constraint.

2022-08-01 10:39 UTC, aryamanjeendgar commented on cvxpy/reductions/cone2cone/common2common.py
> +}
This is simply for maintaining a list of `COMMON_CONES`, for instance, we would add `OpRelCone` to this list next --- this list is used for checking membership while constructing the solving chain, like so:

```
approx_cos = [ct for ct in constr_types if ct in APPROX_CONES]
for co in approx_cos:
     # do something
```

2022-08-01 10:40 UTC, aryamanjeendgar commented on cvxpy/reductions/solvers/solving_chain.py
> +        sim_cos = COMMON_CONES[co]  # get the set of required simple cones
I was thinking of changing the name to `APPROX_CONES` and `QuadApprox` (from `Common2Common`) --- comments?

2022-08-01 14:21 UTC, rileyjmurray commented on cvxpy/tests/test_cone2cone.py
> +        con2 = ExpCone(s, e, x)
``con2 = ExpCone(s, e, x).as_quad_approx(5, 5)``.

2022-08-01 14:23 UTC, rileyjmurray commented on cvxpy/tests/test_cone2cone.py
> +             )
Once ``con2`` is approximated we won't be able to use a dual variable test here. (You'll put ``None`` instead of this list of arrays.)

2022-08-01 14:23 UTC, rileyjmurray requested changes
Mostly looks good! Small changes needed in ``TestRelEntrQuad``.

2022-08-02 03:19 UTC, rileyjmurray approved these changes

2022-08-02 03:23 UTC, rileyjmurray commented
Approved! @SteveDiamond or @akshayka please review as soon as convenient. Since this changes CVXPY's public API we need more than one maintainer to approve. (We will have follow-up PRs though, so these changes can easily be modified.)

2022-08-02 03:36 UTC, SteveDiamond commented on cvxpy/constraints/exponential.py
> +from __future__ import annotations
Is this necessary?

2022-08-02 03:37 UTC, SteveDiamond approved these changes
LGTM

2022-08-02 03:50 UTC, rileyjmurray commented on cvxpy/constraints/exponential.py
> +from __future__ import annotations
It seems as though it's needed for Python 3.7 - 3.10, at least: https://stackoverflow.com/questions/61544854/from-future-import-annotations.

2022-08-02 03:52 UTC, merged

2022-08-02 04:04 UTC, SteveDiamond commented on cvxpy/constraints/exponential.py
> +from __future__ import annotations
I don't think they're saying it's necessary, unless you have very complex annotations. I know you can do annotations without importing this. Not a big deal of course.