Perspective transform of Huber function
cvxpy/cvxpy pull request #1847
Opened 2022-07-29 01:34 UTC by jcbedoyam

## Description

Added new atom for perspective transform of Huber function. This is equivalent to CVX Huber function with three arguments [#1377](https://github.com/cvxpy/cvxpy/issues/1377)

## Type of change
- [x] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [x] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [x] Write unittests.
- [x] Run the unittests and check that they’re passing.
- [x] Run the benchmarks to make sure your change doesn’t introduce a regression.

2022-07-29 01:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=1847) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=1847) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cvxpy/cvxpy?pullRequest=1847) it.</sub>

2022-07-29 02:19 UTC, rileyjmurray commented on cvxpy/atoms/elementwise/huber_pers.py
> +Copyright
Copyright 2022, the CVXPY authors

2022-07-29 02:20 UTC, rileyjmurray commented on cvxpy/reductions/dcp2cone/atom_canonicalizers/huber_pers_canon.py
> +Copyright 2013 Steven Diamond
Copyright 2022, the CVXPY authors

2022-07-29 02:20 UTC, rileyjmurray commented on cvxpy/reductions/qp2quad_form/atom_canonicalizers/huber_pers_canon.py
> +Copyright 2022 CVXPY.
Copyright 2022, the CVXPY authors

2022-07-29 03:09 UTC, rileyjmurray commented on cvxpy/tests/test_atoms.py
> +    def test_huber_pers(self) -> None:
I'd rename this to ``test_huber_pers_properties`` and create a new function called ``test_huber_pers_canon``. The latter function would provide system-level tests to verify that cvxpy is correctly canonicalizing the 3-argument Huber function. I can suggest system-level tests if you'd like.

2022-07-29 03:20 UTC, rileyjmurray requested changes
Hi @jcbedoyam. Thanks for this contribution! You were very thorough in implementing your intended functionality and integrating it with cvxpy. However, I think if we have  a "perspective of Huber function" atom then we should be able to have the "perspective parameter" ``t`` be a non-constant expression. If we restrict ``t`` to be constant then we can trivially produce perspective transforms using code like the following.
```
def perspective(atom, var_args, t):
    # var_args should be a list with positional arguments suitable for calling ``atom(*var_args)``
    t = cp.Expression.cast_to_const(t)
    assert t.is_constant()
    assert t.size == 1
    if isinstance(t, cp.Parameter):
        assert t.is_pos()
    else:
        assert t.value > 0
    scaled_var_args = [arg / t for arg in var_args]
    expr = t*atom(*scaled_var_args)
    return expr
```

2022-07-29 03:23 UTC, rileyjmurray commented
@jcbedoyam I don't think it's possible to implement the perspective of the Huber function using the ``qp2quad_form`` reduction path. That is -- I think that the perspective of the Huber function can only be supported by solvers that allow second-order-cone constraints.

2022-08-04 17:54 UTC, jcbedoyam commented on cvxpy/tests/test_atoms.py
> +    def test_huber_pers(self) -> None:
Thanks, I'll gladly receive your suggestions of the system-level tests.

2022-08-09 02:15 UTC, rileyjmurray commented
My bandwidth is pretty limited right now so I can't guide this PR process in a timely way. @aryamanjeendgar, could you help with this? You have quite a bit of experience writing new atoms :)

2022-08-14 00:45 UTC, rileyjmurray commented
Ping @aryamanjeendgar; see my comment above.

2022-08-14 02:33 UTC, rileyjmurray commented
Actually, this will mostly be handled by #1867. It's best to wait until that's done before working on this any further, since once it's done this will just be a matter of making a small wrapper.

2022-11-24 01:34 UTC, ericlux commented
While #1867 introduces the perspective of an expression with respect to its *variables*, it is not pre-composable. That is if you form the perspective of some expression $f(x)$, $p(x,s) = sf(x/s)$, you will not be able to compose $p(g(x),s)$ for example.

2022-12-29 21:43 UTC, rileyjmurray commented
This is subsumed by #1867, a feature that will appear in CVXPY 1.3.

2022-12-29 21:43 UTC, closed without merging