WIP conic constraints + quadratic objective
cvxpy/cvxpy pull request #1856
Opened 2022-08-04 04:46 UTC by SteveDiamond

## Description
This is a messy WIP PR to add support for conic constraints with a quadratic objective. I haven't had much time to work on this, but it's a priority due to a new solver being added soon.
Issue link (if applicable): #1605 

## Type of change
- [x] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [x] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [ ] Write unittests.
- [ ] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

2022-08-04 17:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=1856) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=1856) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: SteveDiamond<br/>:x: Steven Diamond<br/><hr/>**Steven Diamond** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cvxpy/cvxpy?pullRequest=1856) it.</sub>

2022-08-08 02:11 UTC, rileyjmurray requested changes
Impressive work! It's surprising that this functionality could be added in such little code. Although, I'd like for us to think carefully about whether it makes sense to modify the ``ParamConeProg`` and ``Dcp2Cone`` classes or subclass them. Here are some thoughts:

* I'm not a fan of changing the ``ParamConeProg`` class so that it allows nonlinear objectives. I'd prefer to define a new class called ``ParamQuadConeProg`` that subclasses ``ParamConeProg``. If it seems like doing so would require a lot of code duplication then I think that's an argument to simplify some of the functions in the ``ParamConeProg`` class to handle smaller units of functionality a piece.

* I also think that ``Dcp2Cone`` should be clearer with its scope as to affine versus quadratic representations. I can see how defining a new canonicalization class might be overkill, but perhaps a name change is in order.

There is also a helper for which I've requested additional documentation.

2022-08-08 02:11 UTC, rileyjmurray commented on cvxpy/reductions/qp2quad_form/atom_canonicalizers/__init__.py
> +QUAD_CANON_METHODS = {}
If these variable names are going to be used then there should be comments that disambiguate them.

2022-08-08 02:11 UTC, rileyjmurray commented on cvxpy/reductions/qp2quad_form/atom_canonicalizers/__init__.py
> +CANON_METHODS.update(QUAD_CANON_METHODS)
This makes it look like ``QUAD_CANON_METHODS`` doesn't actually need to be defined. Do you reference it later?

2022-08-08 02:11 UTC, rileyjmurray commented on cvxpy/reductions/utilities.py
> +    """
I'd like for this to be more thoroughly documented. Why is it needed? What shortcoming does it address? We should be clear about these things since they'll come up when rewriting cvxcore (ping @phschiele).

2022-08-08 22:10 UTC, akshayka reviewed
Like Riley said, this is way fewer LOC than I anticipated. Very readable. Nice!

2022-08-08 22:10 UTC, akshayka commented on cvxpy/problems/problem.py
> +        **kwargs
Instead of `**kwargs`, what do you think about explicitly taking a `dict`? Otherwise we could run into an unfortunate edge case in which a solver has an option whose name is the same as an argument to `get_problem_data`, making it impossible to forward that argument to the solver. I know we take var args in `solve`, and I guess that was done to support custom solve methods ...  but here I think there's no reason to do so.

So my suggestion would be to change the signature to:

```python3
    def get_problem_data(
        self, solver,
        gp: bool = False,
        enforce_dpp: bool = False,
        ignore_dpp: bool = False,
        verbose: bool = False
        solver_args: Optional[dict] = None):
```

2022-08-08 22:10 UTC, akshayka commented on cvxpy/reductions/dcp2cone/cone_matrix_stuffing.py
>      def apply_param_jac(self, delc, delA, delb, active_params=None):
Does this function need to be updated to handle quadratic objectives? If it's not supported, we can just raise a `ValueError` if this method  is called when the `ParamConeProg` has a quadratic objective.

2022-08-08 22:50 UTC, SteveDiamond commented on cvxpy/reductions/dcp2cone/cone_matrix_stuffing.py
>      def apply_param_jac(self, delc, delA, delb, active_params=None):
Done.

2022-08-08 22:50 UTC, SteveDiamond commented on cvxpy/problems/problem.py
> +        **kwargs
Done.

2022-08-08 22:50 UTC, SteveDiamond commented on cvxpy/reductions/utilities.py
> +    """
Done.

2022-08-08 22:50 UTC, SteveDiamond commented on cvxpy/reductions/qp2quad_form/atom_canonicalizers/__init__.py
> +CANON_METHODS.update(QUAD_CANON_METHODS)
Yes, added a comment about that.

2022-08-08 22:50 UTC, SteveDiamond commented on cvxpy/reductions/qp2quad_form/atom_canonicalizers/__init__.py
> +QUAD_CANON_METHODS = {}
Done.

2022-08-08 22:51 UTC, SteveDiamond commented on cvxpy/reductions/dcp2cone/dcp2cone.py
>      """
Fixed.

2022-08-08 22:51 UTC, SteveDiamond commented on cvxpy/atoms/affine/affine_atom.py
> +        """Does the affine head of the expression contain a quadratic term?
Added explanation.

2022-08-08 22:55 UTC, SteveDiamond commented
Thanks for reviewing! Let me explain more why I added functionality to dcp2cone, cone_matrix_stuffing, and ParamConeProg rather than defining new classes. Since quadratic cone programs are a superset of both cone programs and quadratic programs, I see adding quadratic cone program support as an opportunity to simplify the canonicalization logic. We can deprecate the QP canonicalization path and reduce the QP and conic canonicalizations to a single pathway. That was too much for me to bite off right now, but I wanted to lay the ground work for that simplification by enhancing the conic canonicalization pathway.

I'm happy to rename various classes to more clearly emphasize that they now handle quadratics if that's desired.

2022-08-09 01:06 UTC, rileyjmurray commented on cvxpy/reductions/utilities.py
> +
Thanks for adding this! I don't quite follow the phrase:

> and a dense matrix that when multiplied by a parameter vector gives the values array

What's the dense matrix?

2022-08-09 01:08 UTC, rileyjmurray commented on cvxpy/reductions/utilities.py
> +        self.mapping_nonzero = None
Could you specify the data types and interpretations of these variables? I know it's a pain but I really don't want to add more matrix stuffing code that isn't clearly documented.

2022-08-09 01:14 UTC, rileyjmurray commented on cvxpy/reductions/utilities.py
> +class ReducedMat:
Consider adding a remark in the docstring that this functionality was originally duplicated in the ``ParamQuadProg`` and ``ParamConeProg`` classes, and that this class consolidates that functionality.

2022-08-09 01:15 UTC, rileyjmurray commented on cvxpy/reductions/utilities.py
> +        self.mapping_nonzero = None
I see now that this class is consolidating very similar code that appears in ``ParamConeProg`` and ``ParamQuadProg``. I'm very much in favor of this approach. I still think that now that it's in a standalone class it's a good opportunity to thoroughly document.

2022-08-09 01:15 UTC, rileyjmurray requested changes
Just a few more questions / requests.

2022-08-09 03:28 UTC, SteveDiamond commented
Thanks @rileyjmurray for the further comments! I added documentation as requested.

2022-08-09 03:28 UTC, merged