Constraint class for the "Full" operator relative entropy cone, `OpRelCone`
cvxpy/cvxpy pull request #1875
Opened 2022-08-16 17:23 UTC by aryamanjeendgar

In this PR, I add support for the "Full" operator relative entropy cone (specifically, the approximation scheme for the same as defined in [FSP17](https://arxiv.org/abs/1705.00812)) which is defined as the _non-commutative perspective_ of the _Operator Relative Entropy_. 

The current implementation is largely complete, with only the addition to the web documentation remaining.

Thank you!

2022-08-17 20:50 UTC, rileyjmurray commented on cvxpy/tests/test_cone2cone.py
> +                             [9.32509585e-14, 4.76722648e-13, 4.09021549e-14, -5.51808473e-01]])
Comments:
1. There's no need to provide numerical values on the order of 1e-12, since we only run tests to 2 or 6 decimal places. So the small values here should be explicitly zeroed out.
2. If you're testing nontrivial functionality then you should explain how you got the answer ``expect_T``. Only a small portion of our tests actually do this, but I think it's important.

Other points
1. Your constraints on ``a_diag`` and ``b_diag`` should make sure they don't all take the same values at optimality. Right now that's happening, and it's an uninteresting test since if a symmetric matrix only has one distinct eigenvalue then that matrix must be a multiple of the identity.
2. You can try computing compute the reference value ``T_expect`` by having ``T_expect = U @ diag(t_expect) @ U.T``, and then using scalar relative entropy (exact, not quad approx) to compute the optimal value of ``t_expect``.

2022-08-31 11:22 UTC, aryamanjeendgar commented
The non-commutative test cases are now working!

As it turned out, we were getting a case of non-unique solutions due to us not explicitly imposing that every involved matrix in the program be symmetric (which is the case in the actual reduction that we implement). The latest commit takes care of that and also adds in a warning to the user if they construct a `OpRelCone` constraint by passing in matrices that haven't been explicitly declared to be symmetric beforehand (which is anyways imposed internally later on, in a less efficient manner).

We were able to in part, figure this out by running through the same test case in `CVXQUAD`, where the symmetric condition was explicitly imposed internally

2022-09-01 14:25 UTC, rileyjmurray commented
@cvxpy/maintainers this is ready for review!

2022-09-01 14:27 UTC, rileyjmurray commented on cvxpy/tests/test_cone2cone.py
> +        return np.sum(val)
This is really the trace of operator relative entropy, with operators that have spectra ``(a, b)``.

2022-09-01 14:27 UTC, rileyjmurray commented on cvxpy/tests/test_cone2cone.py
> +        # ^ changed to be more efficient
Remove comments.

2022-09-01 14:27 UTC, rileyjmurray commented on cvxpy/tests/test_cone2cone.py
> +        # ^ changed to be more efficient
Remove comment

2022-09-01 14:28 UTC, rileyjmurray commented on cvxpy/tests/test_cone2cone.py
> +        return sum(sp.linalg.eigh(TestOpRelCone.Dop(a.value, U1, B.value))[0])
Again, this is specifically the trace of operator relative entropy.

2022-09-01 14:30 UTC, rileyjmurray commented on cvxpy/tests/test_cone2cone.py
> +        """
This docstring doesn't mention ``U1`` and it seems to mention ``a`` as a matrix, rather than a vector. Explain.

2022-09-01 14:31 UTC, rileyjmurray commented on cvxpy/tests/test_cone2cone.py
> +    def oprelcone_1(self) -> STH.SolverTestHelper:
Describe the mathematical nature of this test with a docstring. Don't just rely on in-line comments in the body of the function.

2022-09-01 14:31 UTC, rileyjmurray commented on cvxpy/tests/test_cone2cone.py
> +        # imposing some non-trivial constraints to ensure feasibility
These constraints weren't just for feasibility.

2022-09-01 14:32 UTC, rileyjmurray commented on cvxpy/tests/test_cone2cone.py
> +    def oprelcone_2(self) -> STH.SolverTestHelper:
As with my comment on ``oprelcone_1``: provide a mathematical explanation of how this test works in a docstring.

2022-09-01 14:34 UTC, rileyjmurray commented on cvxpy/constraints/exponential.py
> +        return
You should ``raise NotImplementedError()``

2022-09-01 14:34 UTC, rileyjmurray commented on cvxpy/constraints/exponential.py
> +                   " will be done in a less efficient way internally")
The end of this sentence should have a period.

2022-09-02 23:17 UTC, rileyjmurray requested changes
An improvement! Just a bit more to go :)

2022-09-02 23:17 UTC, rileyjmurray commented on cvxpy/tests/test_cone2cone.py
> +        return trace(TestOpRelCone.Dop_commute(a, b, U)).value
While I appreciate the clear semantics of this, if you're going to return the trace of operator relative entropy with commuting matrices, then your original implementation suffices. You should just rename this to ``tr_Dop_commute(a, b)``. Also, you shouldn't use a cvxpy Atom unless you need to. In this case I believe ``np.linalg.trace`` or ``scipy.linalg.trace`` would be preferable.

2022-09-02 23:17 UTC, rileyjmurray commented on cvxpy/tests/test_cone2cone.py
> +        return trace(TestOpRelCone.Dop(a.value, U1, B.value)).value
Rename this function to ``tr_Dop(a, U, B)``, and use ``scipy.linalg.trace`` instead of the cvxpy trace Atom.

2022-09-02 23:17 UTC, rileyjmurray commented on cvxpy/tests/test_cone2cone.py
> +        """
Explain why this test is valid. This is good given the discussion that you and I have had, but it won't be a useful description if someone has to read this code years from now.

2022-09-02 23:17 UTC, rileyjmurray commented on cvxpy/tests/test_cone2cone.py
> +        """
Clarify how this difference affects test code. I believe that in this case we had to rely on CVXQUAD's correctness to get the reference solution. Compare to the commutative tests, where we could reformulate using standard CVXPY atoms that we already trust as correct.

2022-09-10 18:14 UTC, aryamanjeendgar commented
@SteveDiamond I had a question regarding what would be a consistent naming convention for these approximation classes that we are implementing, so, we named the Scalar Relative Entropy: `RelEntrQuad`, and this current class has been named `OpRelCone` --- I think it makes a lot of sense to rename the latter to include `Quad` to explicitly indicate the approximate nature of this class's construction, but I was then not sure about whether it should be `OpRelConeQuad` or `OpRelQuad` (if we go with the former, then I think it's only fair to rename `RelEntrQuad` to `RelEntrConeQuad`)

Something also relevant to the above discussion is something that @rileyjmurray mentioned, which was that a recent paper by Fawzi talked about how it is possible to implement the _exact_ operator relative entropy cone, and so we would probably want to have that construction as a part of CVXpy at some point as well (i.e. an actual `OpRelCone` class would also probably exist down the road)

2022-09-11 08:20 UTC, SteveDiamond commented
My vote is for ``OpRelConeQuad`` and ``RelEntrConeQuad``, leaving room for ``OpRelCone`` as you said.

2022-09-16 13:09 UTC, rileyjmurray commented on cvxpy/constraints/exponential.py
> +    Number of semidefinite constraints used in constructing this approximation: $(m+k)$
Docstrings render with ReStructured Text. So you should use
```
:math:`m+k`
```

2022-09-16 13:13 UTC, rileyjmurray commented on cvxpy/tests/test_cone2cone.py
> +        return U @ np.diag(a.value * np.log(a.value/b.value)) @ np.linalg.inv(U)
Since ``U`` is orthogonal, it's better to use ``U.T`` instead of ``inv(U)``.

2022-09-16 13:17 UTC, rileyjmurray commented on cvxpy/tests/test_cone2cone.py
> +        b_upper = np.array([0.38687005, 1.18908653, 1.43546562, 2.01528889])
These upper and lower bounds are really close to one another. Can you try making the gap larger? My reasoning is this: if we only test that the solution matches what we expect up to 2 decimal places, then we should make sure the problem has feasible solutions which differ by more than 2 decimal places.

2022-09-17 01:06 UTC, rileyjmurray approved these changes
@cvxpy/maintainers this is ready for review.

2022-09-17 01:06 UTC, rileyjmurray commented on cvxpy/tests/test_cone2cone.py
> +        b_upper = np.array([0.38687005, 1.18908653, 1.43546562, 2.01528889])
Thanks for fixing!

2022-09-17 01:06 UTC, rileyjmurray commented on cvxpy/tests/test_cone2cone.py
> +        return U @ np.diag(a.value * np.log(a.value/b.value)) @ np.linalg.inv(U)
Thanks for fixing!

2022-09-17 01:06 UTC, rileyjmurray commented on cvxpy/constraints/exponential.py
> +    Number of semidefinite constraints used in constructing this approximation: $(m+k)$
I went in and tweaked the docstring a bit more.

2022-09-17 01:11 UTC, rileyjmurray commented
@aryamanjeendgar flake8 is failing. Please do a ``git pull`` to get my latest commit on this branch. Then fix the style issues that flake8 doesn't like.

2022-09-17 16:47 UTC, rileyjmurray approved these changes

2022-09-17 16:58 UTC, SteveDiamond commented on cvxpy/constraints/exponential.py
> +    This approximation uses :math:`m + k` semidefinte constraints.
semidefinite

2022-09-17 16:58 UTC, SteveDiamond commented on cvxpy/constraints/exponential.py
> +    def __init__(self, X, Y, Z, m, k, constr_id=None) -> None:
should we do types here for the arguments?

2022-09-17 16:59 UTC, SteveDiamond commented on cvxpy/constraints/exponential.py
> +            warnings.warn(msg)
Nice!

2022-09-17 16:59 UTC, SteveDiamond commented on cvxpy/constraints/exponential.py
> +        """An operator relative conic constraint is DCP when (A, B, C)is affine
(A, b, C) is affine

2022-09-17 17:00 UTC, SteveDiamond commented on cvxpy/constraints/exponential.py
> +        return
should be ``pass`` instead of return?

2022-09-17 17:01 UTC, SteveDiamond commented on cvxpy/reductions/solvers/solving_chain.py
> +                reductions.append(OpRelConeQuadApprox())
Why are OpRelConeQuadApprox and QuadApprox separate reductions?

2022-09-17 17:02 UTC, SteveDiamond commented
Looks good other than minor comments! Feel free to merge once those are addressed.

2022-09-17 18:31 UTC, rileyjmurray commented on cvxpy/constraints/exponential.py
> +    def __init__(self, X, Y, Z, m, k, constr_id=None) -> None:
We should! @aryamanjeendgar please add type hints.

2022-09-17 18:32 UTC, rileyjmurray commented on cvxpy/constraints/exponential.py
> +        return
Not sure, but probably. @aryamanjeendgar please compare to the SOC, PSD, and ExpCone classes for consistency.

2022-09-17 18:38 UTC, rileyjmurray commented on cvxpy/reductions/solvers/solving_chain.py
> +                reductions.append(OpRelConeQuadApprox())
This is a good point. @aryamanjeendgar I think it's possible for the ``QuadApprox`` to handle the scalar and operator cases. You can just update
https://github.com/cvxpy/cvxpy/blob/04af387a3e1cf1e4df3c23f02708301d779cbf86/cvxpy/reductions/cone2cone/approximations.py#L131-L139
so that 
```
CANON_METHODS = {
    RelEntrQuad: RelEntrQuad_canon,
    OpRelEntrConeQuad : OpRelEntrConeQuad_canon
}
```.

2022-09-18 14:53 UTC, rileyjmurray commented on cvxpy/reductions/solvers/solving_chain.py
> +            if RelEntrQuad or OpRelConeQuad in approx_cos:
This line isn't doing what you think it should be doing. For example,
```
'' or '1' in ['']
```
is False. The check should be
```
RelEntrQuad in approx_cos or OpRelConeQuad in approx_cos
```

2022-09-18 15:14 UTC, merged

2022-09-18 18:40 UTC, SteveDiamond commented
Great job @aryamanjeendgar!!!