WIP initial values
cvxpy/cvxpy pull request #1877
Opened 2022-08-23 21:23 UTC by SteveDiamond

## Description
This is a work in progress PR to add initial values for the solvers that support it. I've copied the implementation for Gurobi from #1664.
Issue link (if applicable): #1664 

## Type of change
- [x] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [ ] Add our license to new files.
- [ ] Check that your code adheres to our coding style.
- [ ] Write unittests.
- [ ] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

2022-08-23 21:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=1877) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=1877) before we can accept your contribution.<br/><hr/>**Steven Diamond** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cvxpy/cvxpy?pullRequest=1877) it.</sub>

2022-08-25 17:38 UTC, SteveDiamond commented
FYI @aszekMosek two of the mosek tests are failing due to the new v10 release.

2022-08-25 17:39 UTC, SteveDiamond commented
This is ready for review. The test failures are due to a new mosek release.

2022-08-26 03:47 UTC, rileyjmurray commented
@SteveDiamond the failures for MOSEK are rather small precision issues; nothing too crazy. We should look into it but there's a small chance that there's an issue on our end.

2022-08-31 16:49 UTC, SteveDiamond commented
@phschiele @rileyjmurray can we review and merge this? It has a fix for the failing mosek tests.

2022-09-21 00:17 UTC, phschiele commented on cvxpy/reductions/solvers/utilities.py
> +            value.append(np.ravel(variable.value, 'C'))
Do all solvers require to ravel the variables in 'C' order?

2022-09-21 00:20 UTC, rileyjmurray requested changes
I left feedback for the tests.

2022-09-21 00:20 UTC, rileyjmurray commented on cvxpy/tests/test_conic_solvers.py
> +
I don't think we can rely on this test to verify correctness of the implementation. At minimum I'd try setting ``self.x.value`` to something that's very far from optimal and see if the solver takes more iterations. Then you can try initializing at the optimal value and seeing if the solver takes fewer iterations.

2022-09-21 00:20 UTC, rileyjmurray commented on cvxpy/tests/test_qp_solvers.py
> +            prob.solve(solver=cp.GUROBI, warm_start=True)
I have a similar feeling about this test and the last test; they should both be structured so that we're confident that options are getting passed correctly. I know it's a pain to write that kind of test, but I want to avoid situations like with our CBC interface (where it turns out we've been silently failing to set solver options for a long time).

In this case I would generate a problem where ``A`` is wide, ``b = A @ np.random.randint(-10, 10, n)``, and ``x.value = np.ones(n)``. If ``A`` is wide enough then I think this problem will be hard to solve, since most convex relaxations encountered in branch-and-bound will be able to achieve $Ax=b$, but probably not with integer solutions.

2022-09-21 00:27 UTC, phschiele commented on cvxpy/tests/test_conic_solvers.py
> +            self.assertItemsAlmostEqual(self.x.value, [1, 2])
It looks like this test is using the qp interface.

2022-09-21 04:05 UTC, phschiele commented on cvxpy/reductions/solvers/utilities.py
> +def stack_vals(variables: list, default: float, order: str = "C") -> np.ndarray:
@SteveDiamond Thanks for adding the order argument!
Just wondering: Where does the C order for Gurobi come from? I would have thought to match the columns of A, F, and P, we would need to ravel in Fortran order, too.

2022-09-21 04:37 UTC, phschiele commented on cvxpy/tests/test_conic_solvers.py
> +
@rileyjmurray Good point. I played around with your suggestion, but the initial value did not affect the iteration count in my (short) testing. 

https://www.gurobi.com/documentation/9.5/refman/start.html suggests that `Start` only affects MIP problems.

2022-09-26 17:07 UTC, SteveDiamond commented
Are we good with this PR? I accidentally started the new SCIP interface from this PR, so need to merge this in first.

2022-09-27 00:46 UTC, rileyjmurray approved these changes

2022-09-27 02:17 UTC, merged