WIP: interface to Clarabel.rs solver
cvxpy/cvxpy pull request #1888
Opened 2022-09-08 16:24 UTC by goulart-paul

## Description
Implements cvxpy interface to the Clarabel solver.   
Main repo for the solver:  https://github.com/oxfordcontrol/Clarabel.rs
Documentation, including native python interface : https://oxfordcontrol.github.io/ClarabelDocs/stable/

## Type of change
- [x] New feature (backwards compatible)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [x ] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [ ] Write unittests.
- [ ] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

This is a WIP PR, not yet ready to merge.   It works with the v0.3.0 dev branch for the solver, but not with the publicly available compiled versions that are still on v0.2.0.    Thus far tested only with single examples, but unittests will be added.

This currently supports nonnegative, second order and exponential cones.   We will add power cone support prior to finalising the PR.  We will also make the solve v0.3.0 binaries available first.

2022-09-08 16:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=1888) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=1888) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cvxpy/cvxpy?pullRequest=1888) it.</sub>

2022-09-11 08:24 UTC, SteveDiamond commented on cvxpy/reductions/solvers/conic_solvers/clarabel_conif.py
> +    #PJG : I don't understand what this does
This does generic preprocessing for conic solvers. There's no need to include this function since it's the same as the super class. It's a mistake that it's present in SCS.

2022-09-11 08:26 UTC, SteveDiamond commented
Looks great! We usually put solver specific tests here: https://github.com/cvxpy/cvxpy/blob/master/cvxpy/tests/test_conic_solvers.py

2022-09-13 08:37 UTC, goulart-paul commented on cvxpy/reductions/solvers/conic_solvers/clarabel_conif.py
> +    #PJG : I don't understand what this does
Thanks.   Deleted.

2022-09-14 12:08 UTC, goulart-paul commented
@SteveDiamond This PR is now passing all workflow tests on my fork of the repo ([here](https://github.com/goulart-paul/cvxpy/actions)).     I think it's now ready for a review.

2022-09-14 16:39 UTC, SteveDiamond commented on setup.cfg
> +CLARABEL =
The pip package name should be here.

2022-09-14 16:39 UTC, SteveDiamond commented on setup.py
> +        "clarabel >= 0.3.0"
Adding clarabel as a requirement seems like kind of a big step. I'd prefer to add it in 1.3 as an optional solver and then in 1.4 we can make it a requirement.

2022-09-14 16:40 UTC, SteveDiamond commented on setup.py
> +        "clarabel >= 0.3.0"
FYI 1.3 will be out by the end of the month.

2022-09-14 16:41 UTC, SteveDiamond commented on cvxpy/tests/test_conic_solvers.py
You should add a line to skip the tests if clarabel is not installed, like L457.

2022-09-14 16:42 UTC, SteveDiamond commented on cvxpy/reductions/solvers/conic_solvers/clarabel_conif.py
> +                    clarabel.SolverStatus.MaxIterations: s.UNBOUNDED_INACCURATE,
The status for MaxIterations and MaxTime should be USER_LIMIT.

2022-09-14 16:46 UTC, SteveDiamond commented
This looks great to me! The only missing piece is documentation of Clarabel solver options at ``doc/source/tutorial/advanced/index.rst`` and installation instructions at ``doc/source/install.rxt``.

@rileyjmurray what do you think?

2022-09-14 16:51 UTC, goulart-paul commented on setup.py
> +        "clarabel >= 0.3.0"
That's fine.   I couldn't figure out how to get the unit tests to behave unless it was a requirement though.   How do I configure it as optional?

2022-09-14 16:51 UTC, goulart-paul commented on cvxpy/tests/test_conic_solvers.py
It seems that you have answered my preceding question already here....

2022-09-14 16:53 UTC, SteveDiamond commented on setup.py
> +        "clarabel >= 0.3.0"
For the github CI/unit tests, you add it to ``continuous_integration/install_dependencies.sh``.

2022-09-14 16:54 UTC, SteveDiamond commented on setup.cfg
> +CLARABEL =
should be ``CLARABEL = clarabel``, until we make it one of the default solvers.

2022-09-14 19:25 UTC, goulart-paul commented on setup.py
> +        "clarabel >= 0.3.0"
Removed in [a5ba6bc](https://github.com/cvxpy/cvxpy/pull/1888/commits/a5ba6bc79af19c2865dd406390c825389389abd3)

2022-09-14 19:26 UTC, goulart-paul commented on cvxpy/tests/test_conic_solvers.py
Skipped in [0fec942](https://github.com/cvxpy/cvxpy/pull/1888/commits/0fec942c674ca26231c45f84ddc465a7e5e2a34f)

2022-09-14 19:26 UTC, goulart-paul commented on cvxpy/reductions/solvers/conic_solvers/clarabel_conif.py
> +                    clarabel.SolverStatus.MaxIterations: s.UNBOUNDED_INACCURATE,
Skipped in [0fec942](https://github.com/cvxpy/cvxpy/pull/1888/commits/0fec942c674ca26231c45f84ddc465a7e5e2a34f)

2022-09-14 19:27 UTC, goulart-paul commented on setup.cfg
> +CLARABEL =
Done in [d2cae49](https://github.com/cvxpy/cvxpy/pull/1888/commits/d2cae4907a4c294b6cc937b4851b30b34f631d19)

2022-09-14 20:47 UTC, SteveDiamond approved these changes

2022-09-14 20:52 UTC, goulart-paul commented
I am getting some weird failures now on the benchmark tests since the solver is not installed by default.   It only happens on a few (seemingly random) combinations of OS and python version.    I think I have not properly configured it as optional everywhere, but I'm not sure how to resolve it.

I put this back to draft for the moment since I will first update the docs to v0.3.0 which might change the user settings URL.

2022-09-14 22:39 UTC, SteveDiamond commented
Ok don't worry about the benchmark failures. We'll fix that on our side. The benchmarks are in a different repo so probably clarabel just needs to be installed in that CI.

2022-09-14 22:43 UTC, SteveDiamond commented on cvxpy/reductions/solvers/conic_solvers/clarabel_conif.py
> +    import clarabel
The import here is causing errors I believe. Maybe you can replace STATUS_MAP with a ``get_status`` function that imports clarabel?

2022-09-14 23:34 UTC, goulart-paul commented on cvxpy/reductions/solvers/conic_solvers/clarabel_conif.py
> +    import clarabel
OK, I think I fixed it.   Passing all tests on my fork again now.   Thanks for the help.

2022-09-15 02:40 UTC, rileyjmurray commented
Thanks for the hard work, @goulart-paul! I'll review this tomorrow.

2022-09-16 12:40 UTC, rileyjmurray commented on cvxpy/reductions/solvers/conic_solvers/clarabel_conif.py
> +Copyright 2022 Paul Goulart
Copyright 2022, the CVXPY Authors

2022-09-16 12:48 UTC, rileyjmurray requested changes
Great work, @goulart-paul! Thanks so much. I'm requesting some very minor changes. @SteveDiamond please feel free to merge once those changes are made.

2022-09-16 12:48 UTC, rileyjmurray commented on cvxpy/reductions/solvers/conic_solvers/clarabel_conif.py
> +Copyright 2022 Paul Goulart
Copyright 2022, the CVXPY Authors

2022-09-16 12:48 UTC, rileyjmurray commented on cvxpy/reductions/solvers/conic_solvers/clarabel_conif.py
> +            raise RuntimeError("PSD cones not yet supported. This function should be unreachable.")
I think you mean "this functionality" or "this line" should be unreachable.

2022-09-16 12:48 UTC, rileyjmurray commented on cvxpy/reductions/solvers/conic_solvers/clarabel_conif.py
> +                raise TypeError("Clarabel: Incorrect type for setting '" + opt + "'") from e
Use f-strings:
```
raise TypeError(f"Clarabel: Incorrect type for setting '{opt}'.") from e
```
(I won't duplicate this comment but please make analogous changes in all appropriate places.)

2022-09-16 12:48 UTC, rileyjmurray commented on cvxpy/tests/solver_test_helpers.py
> +
Thanks for using this API!

2022-09-17 10:40 UTC, goulart-paul commented on cvxpy/reductions/solvers/conic_solvers/clarabel_conif.py
> +Copyright 2022 Paul Goulart
done.

2022-09-17 10:41 UTC, goulart-paul commented on cvxpy/reductions/solvers/conic_solvers/clarabel_conif.py
> +            raise RuntimeError("PSD cones not yet supported. This function should be unreachable.")
done in [490dacc](https://github.com/cvxpy/cvxpy/pull/1888/commits/490daccb5258aaa73465025bc2d608a62ad3b793)

2022-09-17 10:41 UTC, goulart-paul commented on cvxpy/reductions/solvers/conic_solvers/clarabel_conif.py
> +                raise TypeError("Clarabel: Incorrect type for setting '" + opt + "'") from e
done in [490dacc](https://github.com/cvxpy/cvxpy/pull/1888/commits/490daccb5258aaa73465025bc2d608a62ad3b793)

2022-09-17 10:44 UTC, goulart-paul commented on cvxpy/tests/solver_test_helpers.py
> +
I was happy to find it there.   Some future PR might include some more qp tests, e.g. primal and dual infeasible QP cases.   I might do this as part of a COSMO wrapper, but not for a few weeks yet.

2022-09-17 10:45 UTC, goulart-paul commented
@rileyjmurray @SteveDiamond I have pushed some final housekeeping changes as requested.   Many thanks for the help in putting this together.

2022-09-17 16:54 UTC, merged

2022-09-17 16:56 UTC, SteveDiamond commented
Thanks @goulart-paul for putting this together! I'm really excited that we have clarabel now as a solver. It would be amazing to have a set of default solvers that are non-GPL and actively maintained.