Approximate canonicalization for `von_neumann_entr`
cvxpy/cvxpy pull request #1899
Opened 2022-09-27 05:08 UTC by aryamanjeendgar

This PR implements an alternate, approximate canonicalization pathway for the `von_neumann_entr` atom. 
I adapted the same series of semi-definite approximations that I have been implementing so far for the previous `Constraint` classes to get a representation for `von_neumann_entr`. 

The API for `von_neumann_entr` remains unchanged --- if the user wants to employ this approximate formulation in their program, then they can just pass in the usual parameters for the approximation along with the input matrix, like so: `atom=von_neumann_entr(N, (m, k))`.

Some documentation in `von_neumann_entr`'s docstring still remains, but other than that, this is mostly complete!

Thanks!

2022-09-27 20:49 UTC, SteveDiamond commented on cvxpy/atoms/von_neumann_entr.py
> +        self.quad_approx = quad_approx
I think you need a get_data function that returns quad_approx, like L208 of pnorm.py

2022-09-27 20:51 UTC, SteveDiamond commented on cvxpy/atoms/von_neumann_entr.py
> +        self.quad_approx = quad_approx
https://github.com/cvxpy/cvxpy/blob/03fe861fd3450d67445d657cb9a27bcc496e5030/cvxpy/atoms/pnorm.py#L208

2022-09-29 03:48 UTC, aryamanjeendgar commented on cvxpy/atoms/von_neumann_entr.py
> +        self.quad_approx = quad_approx
Ah, sorry for missing that! Have taken care of it in the most recent commit!

2022-09-29 10:44 UTC, rileyjmurray requested changes

2022-09-29 10:44 UTC, rileyjmurray commented on cvxpy/reductions/cone2cone/approximations.py
> +    t = Variable(shape=N.shape)
My dude, you personally wrote the warning message that we should provide symmetric input to ``OpRelConeQuad``!

Declare ``t = cp.Variable(shape=(n, n), symmetric=True)``.

2022-09-29 10:44 UTC, rileyjmurray commented on cvxpy/reductions/cone2cone/approximations.py
> +    return -cp.trace(con.Z), ([lead_con] + cons)
do
```
cons.append(lead_con)
return -cp.trace(con.Z), cons
```

2022-09-29 10:44 UTC, rileyjmurray commented on cvxpy/tests/test_von_neumann_entr.py
> +        """Test#1 for the approximate canonicalization"""
Describe the changes you made relative to the original test. How did you compute the reference solution in this case? If the only difference is that you provide ``quad_approx=(5,5)`` I suggest that you create a helper function like 
```
    def build_test1(quad_approx=False):
        n = 3
        N = cp.Variable(shape=(n, n), PSD=True)
        expect_N = np.array([[0.14523781, 0.02381009, 0.10238067],
                             [0.02381009, 0.28095125, 0.13809581],
                             [0.10238067, 0.13809581, 0.37380924]])
        v1 = np.array([[-0.26726124],
                       [-0.53452248],
                       [-0.80178373]])
        v2 = np.array([[0.87287156],
                       [0.21821789],
                       [-0.43643578]])
        lambda1 = 0.5
        lambda2 = 0.1
        trMax = 0.8
        cons1 = N @ v1 == lambda1 * v1
        cons2 = N @ v2 == lambda2 * v2
        cons3 = trace(N) <= trMax
        if quad_approx is not None:
            quad_approx_params = (5, 5)
            objective = cp.Maximize(von_neumann_entr(N, quad_approx_params))
        else:
            objective = cp.Maximize(von_neumann_entr(N))
        obj_pair = (objective, 0.8987186478352693)
        con_pairs = [
            (cons1, None),
            (cons2, None),
            (cons3, None)
        ]
        var_pairs = [
            (N, expect_N)
        ]
        sth = STH.SolverTestHelper(obj_pair, var_pairs, con_pairs)
        return sth
```
Then call this function in two different contexts for running actual tests.

2022-09-29 10:44 UTC, rileyjmurray commented on cvxpy/tests/test_von_neumann_entr.py
> +    def make_test_6():
My first comment here is that my instinct is to modify this along the lines of my suggestions for ``make_test_5``. However, I worry that this test might be unnecessarily expensive since it uses (8, 8) for the quad_approx parameters. Can you use smaller values, like ``(3, 2)``, and compute the reference solution using CVXQUAD?

2022-10-03 17:35 UTC, aryamanjeendgar commented on cvxpy/reductions/cone2cone/approximations.py
> +    t = Variable(shape=N.shape)
Big oopsie! Took care of this!

2022-10-03 17:45 UTC, aryamanjeendgar commented on cvxpy/tests/test_von_neumann_entr.py
> +        """Test#1 for the approximate canonicalization"""
These test cases have readily computable solutions, so we don't need CVXQUAD for the references -- so I stuck with the same values as before for these.

2022-10-03 17:48 UTC, aryamanjeendgar commented on cvxpy/tests/test_von_neumann_entr.py
> +    def make_test_6():
The `(8,8)` was mostly just out of curiosity XD, I changed it to a much more reasonable `(3,2)`.

2022-10-03 17:49 UTC, aryamanjeendgar commented on cvxpy/reductions/cone2cone/approximations.py
> +    return -cp.trace(con.Z), ([lead_con] + cons)
Changed!

2022-10-09 12:46 UTC, rileyjmurray commented on cvxpy/tests/test_von_neumann_entr.py
> +        """Test#1 for the approximate canonicalization"""
@aryamanjeendgar can you please make this change?

2022-10-10 17:51 UTC, aryamanjeendgar commented on cvxpy/tests/test_von_neumann_entr.py
> +        """Test#1 for the approximate canonicalization"""
@rileyjmurray Done!

2022-10-12 21:29 UTC, rileyjmurray approved these changes
@cvxpy/maintainers this is ready for review

2022-10-12 22:34 UTC, SteveDiamond commented on cvxpy/atoms/von_neumann_entr.py
> +        return self.quad_approx
return [self.quad_approx]

2022-10-12 22:36 UTC, SteveDiamond approved these changes
LGTM other than minor issue with get_data

2022-10-13 13:44 UTC, merged