Fix-curvature-bug-by-randomized-vector
cvxpy/cvxpy pull request #2086
Opened 2023-03-31 10:52 UTC by Paulnkk

## Description
Please include a short summary of the change.
I have included the suggestions from the issue link below. However, there is still the problem that since the curvature is not clearly defined (convex or unknown), in the case of a defined seed, the curvature is set to unknown, which should not happen when executing the code given in the issue link, since the eigenvalues of the matrix from the example are strictly positive (except for one EV that is very close to 0, but that makes no difference for the convexity of quad_form). 
Issue link (if applicable):
The issue was found with the following link: https://github.com/cvxpy/cvxpy/issues/2083
## Type of change
![Screenshot 2023-03-31 at 12 37 35](https://user-images.githubusercontent.com/93285862/229101010-56c7f3a6-7281-45ce-a47a-ad373407af7f.png)

- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [x] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [ ] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [ ] Write unittests.
- [x] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

2023-03-31 10:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=2086) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=2086) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cvxpy/cvxpy?pullRequest=2086) it.</sub>

2023-03-31 12:38 UTC, Transurgeon commented
@Paulnkk I looked at your PR and it resolves the two issues I was talking about...
This was my implementation:
        np.random.seed(0)
        return sparla.eigsh(A, k=1, sigma=sigma, v0=A[np.random.randint(A.shape[0])],
                            which='SA', return_eigenvectors=False)
I used randint to get an index within the size of the array.. not sure why it causes problems.
Anyways, what defined seed produces this new bug you mention? (where the curvature is always unknown)

Also, we probably need to add some tests. Is it feasible to just add the 19 by 19 example we have been testing with into test_quad_form.py?

2023-04-03 15:59 UTC, Paulnkk commented
> @Paulnkk I looked at your PR and it resolves the two issues I was talking about... This was my implementation: np.random.seed(0) return sparla.eigsh(A, k=1, sigma=sigma, v0=A[np.random.randint(A.shape[0])], which='SA', return_eigenvectors=False) I used randint to get an index within the size of the array.. not sure why it causes problems. Anyways, what defined seed produces this new bug you mention? (where the curvature is always unknown)
> 
> Also, we probably need to add some tests. Is it feasible to just add the 19 by 19 example we have been testing with into test_quad_form.py?

@Transurgeon, the example mentioned in the issue link has a positive semi-definite matrix which should imply convexity for its quad_form from my point of view (not additionally "unknown" as shown: https://github.com/cvxpy/cvxpy/issues/2083), here it seems to me that the output of the curvature is dependent on some randomness which should not be the case (?). We now try to avoid this "randomness" by setting the seed and a random starting vector for Lanczos method to determine the max eigenvalue. 

Now I see one problem as the following (what I also mentioned in the PR): By setting the seed and having this "switching" property from the example of 'unknown' and 'convex', I can determine the 'unknown' curvature instead of the 'convex' curvature and get in the example (I added in the PR) all the times 'Unknown' instead of 'Convex'. 

Another problem that is not explicitly related to the problem are the tests (please see the one failing macos test below); there seems to be a technical issue with a psd check for a specific mac version. Also another thing is the scipy check (I also ran into an issue on my machine with this) which was added a couple PRs before. But actually, I do not know if these problems were created by my 'master merge' (or some local changes) or for another reason.

Maybe you can help me (or another person who knows how to do it) to run all the relevant tests for a specific branch without pushing changes so that I can check for version dependent fails (as in this PR).

2023-04-07 16:53 UTC, Paulnkk commented
@rileyjmurray I am currently facing the issue that the suggested lines I added are leading to the desired output concerning the problem mentioned in the issue link but I do not pass a particular test. Since I can not reproduce this error on my machine and I assume its inconvenient to push commits every time I make a change to see if this error is fixed, is there a way to run all the tests on my machine to potentially reproduce this error ?

2023-04-07 17:25 UTC, SteveDiamond commented
> @rileyjmurray I am currently facing the issue that the suggested lines I added are leading to the desired output concerning the problem mentioned in the issue link but I do not pass a particular test. Since I can not reproduce this error on my machine and I assume its inconvenient to push commits every time I make a change to see if this error is fixed, is there a way to run all the tests on my machine to potentially reproduce this error ?

@Paulnkk @phschiele would github codespaces help here?

2023-04-07 22:08 UTC, phschiele commented
I tried it on codespaces and the tests are passing there as well.
The failing test is this one:

```py
        n = 50
    
        # trivial cases
        psd = np.eye(n)
        nsd = -np.eye(n)
    
        assert cp.Constant(psd).is_psd()
>       assert not cp.Constant(psd).is_nsd()
```
It is a bit odd that fixing the seed vector would break the test that was specifically declared as a "trivial case" .

2023-04-08 16:17 UTC, rileyjmurray commented
1. The initial vector should have iid Gaussian entries.

2. I’m pretty sure our code special-cases for diagonal matrices. Does that
path only get hit for sparse matrices? If so we should definitely update it
to apply to dense matrices as well.

On Fri, Apr 7, 2023 at 6:08 PM Philipp Schiele ***@***.***>
wrote:

> I tried it on codespaces and the tests are passing there as well.
> The failing test is this one:
>
>         n = 50
>
>         # trivial cases
>         psd = np.eye(n)
>         nsd = -np.eye(n)
>
>         assert cp.Constant(psd).is_psd()>       assert not cp.Constant(psd).is_nsd()
>
> It is a bit odd that fixing the seed vector would break the test that was
> specifically declared as a "trivial case" .
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cvxpy/cvxpy/pull/2086#issuecomment-1500686328>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACRLIFASFVVTJ325HV4TYT3XACF43ANCNFSM6AAAAAAWOPVFQE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-08 16:20 UTC, rileyjmurray commented
Actually in retrospect the identity matrix is known to create problems for
iterative eigenvalue solvers. The only way we can catch this case reliably
is by special-casing diagonal matrices.

On Sat, Apr 8, 2023 at 12:17 PM Riley Murray ***@***.***>
wrote:

> 1. The initial vector should have iid Gaussian entries.
>
> 2. I’m pretty sure our code special-cases for diagonal matrices. Does that
> path only get hit for sparse matrices? If so we should definitely update it
> to apply to dense matrices as well.
>
> On Fri, Apr 7, 2023 at 6:08 PM Philipp Schiele ***@***.***>
> wrote:
>
>> I tried it on codespaces and the tests are passing there as well.
>> The failing test is this one:
>>
>>         n = 50
>>
>>         # trivial cases
>>         psd = np.eye(n)
>>         nsd = -np.eye(n)
>>
>>         assert cp.Constant(psd).is_psd()>       assert not cp.Constant(psd).is_nsd()
>>
>> It is a bit odd that fixing the seed vector would break the test that was
>> specifically declared as a "trivial case" .
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/cvxpy/cvxpy/pull/2086#issuecomment-1500686328>, or
>> unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ACRLIFASFVVTJ325HV4TYT3XACF43ANCNFSM6AAAAAAWOPVFQE>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2023-04-13 21:45 UTC, Paulnkk commented
There are several things I have questions about: 1.) I picked Gaussian entries with mu = 0 and sigma = 1 but since we hand over this randomly generated vector for Arnoldi, I am not sure how convergency of Arnoldi is affected but this initially randomly generated starting vector, could potentially affect speed for large scale dimensions. 2.) I now understand the error I got from your explanation and I tried to make the trivial test more versatile in terms of eigenvalues and eigenvectors but I seem to get additional failing tests now. 3.) Could you please explain by what do you mean with "The only way we can catch this case reliably is by special-casing diagonal matrices." ? Is it related to differently generate curvature info for diag matrices ? For instance Check for diag matrix property and get the minimum value from the trace instead of using numerical methods here ?

2023-04-13 22:07 UTC, Paulnkk commented
I had to revert the trivial psd checks from this commit [Adjust trivial psd check](https://github.com/cvxpy/cvxpy/pull/2086/commits/18a0222569669bd0a89e17d7bbd83eea67c870fc) back because almost all tests were failing.

2023-04-13 22:40 UTC, rileyjmurray commented
> There are several things I have questions about: 1.) I picked Gaussian entries with mu = 0 and sigma = 1 but since we hand over this randomly generated vector for Arnoldi, I am not sure how convergency of Arnoldi is affected but this initially randomly generated starting vector, could potentially affect speed for large scale dimensions. 2.) I now understand the error I got from your explanation and I tried to make the trivial test more versatile in terms of eigenvalues and eigenvectors but I seem to get additional failing tests now. 3.) Could you please explain by what do you mean with "The only way we can catch this case reliably is by special-casing diagonal matrices." ? Is it related to differently generate curvature info for diag matrices ? For instance Check for diag matrix property and get the minimum value from the trace instead of using numerical methods here ?

@Paulnkk, for (1), Arnoldi will only converge to the correct eigenspace if the starting vector has a nontrivial projection onto that eigenspace. Sampling a vector whose components are iid Gaussian ensures that this happens with probability one, no matter the matrix or eigenspace that you're considering. The complexity of forming the Gaussian random vector is negligible.

For (3), I mean that we should check if the input matrix is diagonal. If it is, then we should determine whether or not it's PSD simply by checking that its minimum diagonal entry is nonnegative. That is, we would simply check that ``min([A[i,i] for i in range(n)]) >= 0``, if ``A`` is an array of order ``n``. (I'm not sure how you would consider using the trace. That would not suffice for a PSD check even if the matrix was diagonal.)

2023-04-13 22:52 UTC, Paulnkk commented
@rileyjmurray Thanks! Concerning 3.) sorry translation mistake from my side; I meant using the min element from the diagonal (I mentioned as trace) of matrix as you mentioned it

2023-04-25 21:32 UTC, Paulnkk commented
I used this branch on codespace, but I am still not sure how to run specific tests from the build-in codespace to check why those tests are failing, very grateful for a small hint how to do that :) Also, I do not know why but I am using a mac m1 version 12 and tests are passing without a fail.

2023-04-25 22:43 UTC, phschiele commented
@Paulnkk Make sure to have pytest and the Python extension installed. You then need to configure tests by typing:
`Ctrl + P`, `Python: Configure Tests`, `Pytest`, `cvxpy`.

You should then see a beaker icon in the left sidebar. Clicking on this reveals the individual test cases that can be run one at a time (see below).

Since #2088 this is done automatically, so if it doesn't work out you can create a new codespace after making sure that the current master is merged into this branch.

![image](https://user-images.githubusercontent.com/44360364/234420823-e8379b5d-267b-45e9-8b9f-484216d4c76e.png)

2023-04-26 15:57 UTC, Paulnkk commented
@phschiele, thanks for the support! It works itself but I am currently facing the issue that the tests which are failing and I need to check for fixing the errorors are skipped (please find attached a screenshot for one example test). I see from the test report that I am using the test on linux(?). Maybe I can change the system on which the test runs and therefore those tests are not skipped (or maybe I can avoid skipping the test). 
<img width="655" alt="Screenshot 2023-04-26 at 17 46 26" src="https://user-images.githubusercontent.com/93285862/234632989-c8955c9e-ac65-4ac9-b83e-0003d311b442.png">

2023-05-07 01:53 UTC, rileyjmurray requested changes
Mostly looks good! I have one small comment in ``is_psd_within_tol``.

2023-05-07 01:53 UTC, rileyjmurray commented on cvxpy/utilities/linalg.py
> +            min_diag_entry = np.min(np.diag(A))
This conversion to a dense array can be avoided. Since we've checked that the matrix is diagonal, we know that ``A.data`` contains the diagonal of ``A`` (possibly with explicit zeros elsewhere). So it suffices to check ``np.all(A.data >= -tol)`` without converting to an array.

Or you could set ``min_diag_entry = np.min(A.data)``, with the understanding that this might equal zero in an unusual case where off-diagonal zero entries are stored explicitly.

2023-05-08 20:29 UTC, Paulnkk commented on cvxpy/utilities/linalg.py
> +            min_diag_entry = np.min(np.diag(A))
@rileyjmurray thanks for the suggestion! Made the change here: [Remove dense array conversion](https://github.com/cvxpy/cvxpy/pull/2086/commits/81b8778b192d3f122b1a12ed5b10d58cacdc3a1a)

2023-05-14 01:43 UTC, rileyjmurray commented
@Paulnkk, it occurred to me that we shouldn't be setting the global seed for NumPy's random number generator. 

We can define our own random stream with this API: https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.default_rng. For example
```
g = np.random.default_rng(123)
v0 = g.normal(loc=0.0, scale=1.0, size=n)
```
That won't quite cut it though, since we need to support the legacy API as well: https://numpy.org/doc/stable/reference/random/legacy.html#legacy
```
g = np.random.random_state(123)
v0 = g.normal(loc=0.0, scale=1.0, size=n)
```
So we should really get the random vectors using a code snippet like this:
```
if hasattr(np.random, 'default_rng'):
    g = np.random.default_rng(123)
else:
    g = np.random.RandomState(123)
v0 = g.normal(loc=0.0, scale=1.0, size=n)
```
I think we should be good to merge once you make this change in the appropriate places.

2023-05-21 22:20 UTC, rileyjmurray commented
@Paulnkk I'll go ahead and make the changes I requested in my last comment.

2023-05-21 22:22 UTC, Paulnkk commented
@rileyjmurray I can also make the changes, sorry for the late response. I visited my graduation. Planned to make changes on my way back and commit changes when I have access again.

2023-05-21 22:28 UTC, rileyjmurray commented
@Paulnkk ah! Well, in that case, I'll let you finish. I'll be sure to review shortly after your changes show up :)

2023-05-21 22:39 UTC, Paulnkk commented
@rileyjmurray thanks a lot ! :) 
I will tag you as soon as I made the changes and wifi connection (will have a bigger travel now and unfortunately no wifi)

2023-05-22 01:35 UTC, rileyjmurray approved these changes
Looks good to me!

2023-05-22 01:35 UTC, rileyjmurray approved these changes
Looks good to me!

2023-05-22 01:35 UTC, rileyjmurray approved these changes
Looks good to me! (For reasons that I don't understand, GitHub posted my approval comment three times.)

2023-05-22 01:59 UTC, merged