Add SOC2PSD Reduction
cvxpy/cvxpy pull request #2116
Opened 2023-04-30 18:19 UTC by usamamuneeb

## Description

Added a reduction `SOC2PSD` that converts the SOC constraints to PSD constraints, for solvers that support the PSD cone but not the second order cone.

This enables the SDPA solver to be used for solving QPs and SOCPs.

## Type of change
- [x] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [x] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [x] Write unittests.
- [x] Run the unittests and check that they’re passing.
- [x] Run the benchmarks to make sure your change doesn’t introduce a regression.

2023-05-02 00:28 UTC, SteveDiamond commented on cvxpy/reductions/solvers/solving_chain.py
> +            unsupported_constraints = [
Move this out of the else clause so it's calculated in both cases.

2023-05-02 00:29 UTC, SteveDiamond commented on cvxpy/reductions/solvers/solving_chain.py
> +            elif all(c==SOC for c in unsupported_constraints):
This feels a bit fragile and SDPA specific. We probably want something more general. For example doesn't this code assume the solver supports PSD constraints?

2023-05-02 00:30 UTC, SteveDiamond commented
This is quite a nice contribution, thanks! We definitely should have an SOC2PSD reduction. The solving_chain code is very critical and already pretty messy so may require more organization.

2023-05-02 02:30 UTC, usamamuneeb commented on cvxpy/reductions/solvers/solving_chain.py
> +            elif all(c==SOC for c in unsupported_constraints):
Indeed. Just fixed.

2023-05-07 02:12 UTC, rileyjmurray requested changes
@usamamuneeb in your ``soc2psd.py`` file, please replace the ``np.identity(k)`` calls to ``scipy.sparse.eye(k)``. This will result in far lower memory consumption. (You might need to change the format of the SciPy sparse matrix to ``csc_matrix``, not sure.)

2023-05-07 15:08 UTC, usamamuneeb commented
`scipy.sparse.eye` uses the `DIAgonal format` by default and `cvxpy.bmat` accepts it.

I believe conversion from diagonal format to either `CSR` or `CSC` should have the same complexity, so we should perhaps let CVXPY decide whichever is more appropriate when it needs to performs matrix operations internally.

2023-05-07 16:53 UTC, rileyjmurray commented
Thanks for making the change!

> `scipy.sparse.eye` uses the `DIAgonal format` by default and `cvxpy.bmat` accepts it.
> 
> I believe conversion from diagonal format to either `CSR` or `CSC` should have the same complexity, so we should perhaps let CVXPY decide whichever is more appropriate when it needs to performs matrix operations internally.

I agree that we should let cvxpy decide on any conversions if needed. I just didn't know if we accepted diagonal format SciPy sparse matrices.

2023-05-07 17:05 UTC, rileyjmurray commented on cvxpy/reductions/cone2cone/soc2psd.py
> +                new_psd_constraint = PSD(M / 2)
Since the PSD cone is a cone, scaling ``M`` doesn't change whether or not the constraint holds. Is there a reason why you use this scaled version instead of ``new_psd_constraint = PSD(M)``?

The only thing I can think of is that you might need it to get dual variables right. If that's the case, then I think you can replace this long comment with a single-line comment saying ``# scale M by 1/2 so the PSD cone dual variables get correctly mapped to SOC dual variables``.

If this scaling isn't needed for dual variable purposes then I suggest it be removed, along with this comment.

2023-05-07 17:08 UTC, rileyjmurray commented
Note: the test failures are unrelated. (They're due to a test where we expect an ARPack convergence failure in ``is_psd`` but ARPack actually converges.)

2023-05-07 18:09 UTC, usamamuneeb commented on cvxpy/reductions/cone2cone/soc2psd.py
> +                new_psd_constraint = PSD(M / 2)
Yup, it's the dual variables :)

If I don't divide the matrix `M` by 2, I have to multiply the dual variables by 2. The reason I chose to divide `M` by 2 was that this way it's easier to explain to the reader why this scaling is needed in the first place.

If we don't need to explain to the reader, then we can simply multiply the dual variables by 2 instead. This is because the number of elements requiring division (i.e. the entire PSD constraint matrix) is a square of the number of the elements that would otherwise require multiplication (i.e. just a row of the PSD dual variable matrix).

2023-05-07 18:15 UTC, usamamuneeb commented on cvxpy/reductions/cone2cone/soc2psd.py
> +                new_psd_constraint = PSD(M / 2)
In addition, multiplication of the dual variables by 2 can also be further vectorized if performed after we `np.hstack` all the dual variables of a packed SOC constraint.

2023-05-07 21:58 UTC, usamamuneeb commented on cvxpy/reductions/cone2cone/soc2psd.py
> +                new_psd_constraint = PSD(M / 2)
I've simplified the comment and moved the scaling to the dual variables for the reasons mentioned above.

2023-05-08 00:35 UTC, rileyjmurray commented on cvxpy/reductions/cone2cone/soc2psd.py
> +                """
I think this comment isn't necessary. There's no way this scaling could have a measurable impact on compile time or solve time. You can just have a small comment in the invert function saying that the PSD representation requires scaling the dual variables by 2 to get the SOC dual variable. These sorts of things are not uncommon and don't need a lengthy explanation.

2023-05-08 00:40 UTC, usamamuneeb commented on cvxpy/reductions/cone2cone/soc2psd.py
> +                """
Just fixed.

2023-05-08 02:12 UTC, rileyjmurray approved these changes
Looks good to me!

2023-05-08 02:13 UTC, rileyjmurray commented
@SteveDiamond can you take another look and see if it's good from your perspective?

2023-05-08 04:08 UTC, SteveDiamond approved these changes
This LGTM as well.

2023-05-08 19:09 UTC, merged