Add-solver-opts-parameter-mosek
cvxpy/cvxpy pull request #2117
Opened 2023-05-01 16:18 UTC by Paulnkk

## Description
I added a parameter for the mosek solver option to map solver status 'unknown' to an inaccurate solution if applicable.
Issue link (if applicable):
I found the issue here: https://github.com/cvxpy/cvxpy/issues/1787

## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [x] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [ ] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [ ] Write unittests.
- [ ] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

2023-05-01 16:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=2117) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=2117) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cvxpy/cvxpy?pullRequest=2117) it.</sub>

2023-05-01 16:48 UTC, phschiele commented on cvxpy/reductions/solvers/conic_solvers/mosek_conif.py
> +        # man muss hier über
:de: comment :)

2023-05-01 16:48 UTC, phschiele commented on cvxpy/reductions/solvers/conic_solvers/mosek_conif.py
> +            if solver_opts['accept_unknown']:
Can be combined as `if solver_opts.get('accept_unknown', False)`

2023-05-01 16:50 UTC, phschiele commented on cvxpy/reductions/solvers/conic_solvers/mosek_conif.py
> +                STATUS_MAP[mosek.solsta.dual_infeas_cer] = s.UNBOUNDED
We would only need to update the entries that changed from above.

2023-05-01 16:57 UTC, phschiele commented
@Paulnkk Thanks for adding this! 
In addition to a few small comments above, we should also document the setting here:
https://www.cvxpy.org/tutorial/advanced/index.html#setting-solver-options

It would be even better if we could add a test case. Paging @pqrz, @aszekMosek, @erling-d-andersen, @rileyjmurray , and @SteveDiamond from the discussion in #1787 for ideas about a minimal example that can trigger the unknown status (with solution).

2023-05-01 17:03 UTC, rileyjmurray commented
@phschiele: a few months ago (between 1.2 and 1.3 releases) we found an example in ``test_constant_atoms`` that resulted in an ill-posed exponential cone program. I think the exponential cone is the only one that MOSEK supports which is defined as a closure of some inequality-representable set. So I would try making such an example where the only feasible solutions lay on the boundary that needs the closure.

2023-05-01 17:08 UTC, Paulnkk commented on cvxpy/reductions/solvers/conic_solvers/mosek_conif.py
> +            if solver_opts['accept_unknown']:
Merged conditions together here: [Adjust accept_unknown condition](https://github.com/cvxpy/cvxpy/pull/2117/commits/abf94f70f559daef24aacb5f1efa1257e319d318)

2023-05-01 17:08 UTC, Paulnkk commented on cvxpy/reductions/solvers/conic_solvers/mosek_conif.py
> +                STATUS_MAP[mosek.solsta.dual_infeas_cer] = s.UNBOUNDED
Removed conditions here: [Adjust accept_unknown condition](https://github.com/cvxpy/cvxpy/pull/2117/commits/abf94f70f559daef24aacb5f1efa1257e319d318)

2023-05-01 17:30 UTC, aszekMosek commented
To reliably get solution status unknown take any problem that is nontrivial enough not to get solved by presolve and set time limit or max number of iterations to 0.

2023-05-01 21:43 UTC, Paulnkk commented
@phschiele @rileyjmurray @aszekMosek I added a problem from a simple cone program which already exists in cvxpy with setting timelimit to 0 but I need to double check if the problem is actually non-trivial enough to to trigger the unknown status and that the assertion I build actually leads to the desired check we want here.

2023-05-01 22:37 UTC, rileyjmurray commented
I think it suffices to check that the status is "optimal - inaccurate".
With this PR it's clear that we send that status back only when MOSEK
returns an "unknown" status code. If MOSEK's presolve gets better in the
future we may need to update the test problem. I think we can cross that
bridge if / when we come to it.

On Mon, May 1, 2023 at 2:43 PM Paul ***@***.***> wrote:

> @phschiele <https://github.com/phschiele> @rileyjmurray
> <https://github.com/rileyjmurray> @aszekMosek
> <https://github.com/aszekMosek> I added a problem from a simple cone
> program which already exists in cvxpy with setting timelimit to 0 but I
> need to double check if the problem is actually non-trivial enough to to
> trigger the unknown status and that the assertion I build actually leads to
> the desired check we want here.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cvxpy/cvxpy/pull/2117#issuecomment-1530347353>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACRLIFFVKIPEG6HUIOPBRJDXEAU7BANCNFSM6AAAAAAXR5O6DA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-02 21:18 UTC, Paulnkk commented
@rileyjmurray thanks, I think I implemented it with the desired output but termination with OPTIMAL_INACCURATE is actually trivial since we have no timelimit.

2023-05-07 01:34 UTC, rileyjmurray requested changes
@Paulnkk can you please update the web documentation to mention this parameter?

The relevant section that needs to change is here: https://github.com/cvxpy/cvxpy/blob/master/doc/source/tutorial/advanced/index.rst#setting-solver-options.

2023-05-14 01:48 UTC, rileyjmurray approved these changes

2023-05-14 04:49 UTC, SteveDiamond approved these changes

2023-05-14 07:44 UTC, phschiele approved these changes

2023-05-14 14:27 UTC, merged