Update test_conic_solvers.py
cvxpy/cvxpy pull request #2131
Opened 2023-05-16 22:53 UTC by dcajasn

Add test for the fix that solves issue #2128

## Description
Please include a short summary of the change.
Issue link (if applicable):

## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [ ] Add our license to new files.
- [ ] Check that your code adheres to our coding style.
- [ ] Write unittests.
- [ ] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

2023-05-16 23:03 UTC, SteveDiamond commented on cvxpy/tests/test_conic_solvers.py
> +        T, N = 10, 1000
can you make this problem smaller?

2023-05-16 23:04 UTC, SteveDiamond commented
Can you include the change in #2129 to mosek_conif.py here and then I will close that PR?

2023-05-16 23:08 UTC, dcajasn commented on cvxpy/tests/test_conic_solvers.py
> +        T, N = 10, 1000
When you say smaller, it means less lines or decrease the values of N and T?

2023-05-16 23:09 UTC, dcajasn commented
Ok

2023-05-16 23:14 UTC, SteveDiamond commented on cvxpy/tests/test_conic_solvers.py
> +        T, N = 10, 1000
Smaller N

2023-05-16 23:22 UTC, dcajasn commented
I've just changed the branch from steven-sdp-power to master. It includes all the changes you made on steven-sdp-power.

2023-05-16 23:28 UTC, rileyjmurray commented on cvxpy/tests/test_conic_solvers.py
> +        problem.solve(solver='MOSEK')
General comment 1: since you aren't testing MOSEK's output, there's no reason to actually solve the problem. You should set MOSEK's time and iteration limits to 0.

General comment 2: it would be nice to have a mixed powercone / SDP test that can be used in ``solver_test_helpers.py``. If you define a _much_ smaller problem, then you can write down the answer reported by MOSEK explicitly. You can also solve the problem with SCS with very small ``eps`` to check that the solutions are the same. I'm pretty sure that very small problems, say with ``T=2, N=3`` would suffice to trigger the failure case you observed.

2023-05-16 23:36 UTC, SteveDiamond commented on cvxpy/reductions/solvers/conic_solvers/mosek_conif.py
> +                if (K[a2d.DUAL_EXP] == 0) and (K[a2d.DUAL_POW3D] == 0):
All the changes besides this one line are part of #2126. I included them accidentally in #2129 . Could you remove them and keep just the change at line 248?

2023-05-17 00:49 UTC, dcajasn commented on cvxpy/tests/test_conic_solvers.py
> +        problem.solve(solver='MOSEK')
I modified the test according the first comment. I'm working on the second comment.

2023-05-17 03:53 UTC, dcajasn commented on cvxpy/tests/test_conic_solvers.py
> +        problem.solve(solver='MOSEK')
I've just finished the test helpers. Let me know if it is ok 😅

2023-05-17 18:57 UTC, SteveDiamond approved these changes
LGTM! Thanks so much!

2023-05-18 01:04 UTC, rileyjmurray requested changes
@dcajasn, thanks for updating solver_test_helpers! I played around with that new test and found some undiscovered bugs in the process. So I'm going to ask you to do a few things.

1) Please add ``sth.check_primal_feasibility(places)`` right before the ``sth.verify_primal_values(places)`` in all functions in ``StandardTestPCPs``.  This change will reveal a bug in the ``PowCone3D`` class that causes MOSEK and SCS tests to fail.

2) Please add the ``@property`` decorator to the ``residual`` method of ``PowCone3D``. This is the fix that's needed to resolve the failures introduced by my first request.

3) Please change the default value of ``duals`` in ``StandardTestMixedCPs.test_sdp_pcp_1`` to ``False``.

4) Please replace the ``test_mosek_sdp_power`` function with the following
  ```
      def test_mosek_sdp_pcp_1():
          StandardTestMixedCPs.test_sdp_soc_1(solver='MOSEK')
  ```
    
5) Please add the following function to ``TestSCS(BaseTest)``
  ```
    def test_scs_sdp_pcp_1():
        StandardTestMixedCPs.test_sdp_soc_1(solver='SCS')
  ```
  
  That's all from me. Thanks for your patience in this process!

2023-05-18 01:05 UTC, rileyjmurray commented on cvxpy/tests/test_conic_solvers.py
> +        problem.solve(solver='MOSEK')
@dcajasn the new test case ended up being very revealing! I just submitted a review that asks you to resolve some previously-undiscovered bugs.

2023-05-18 02:10 UTC, dcajasn commented
Hi @rileyjmurray, I've just made the changes. Thank you for all your hard work developing and improving this terrific software.

2023-05-18 18:01 UTC, SteveDiamond commented
I fixed some minor bugs that were causing test failures in the CI.

2023-05-21 22:12 UTC, rileyjmurray approved these changes

2023-05-21 22:19 UTC, merged