Adding functionality to cvxpy/tests: verifying stationarity of the Lagrangians as part of KKT conditions
cvxpy/cvxpy pull request #2171
Opened 2023-07-05 13:00 UTC by aryamanjeendgar

## Description
This PR adds a new method, `check_stationarity_lagrangian`, which:
1. Tries to construct the Lagrangian corresponding to a given problem
2. Check if it is stationary by using the existing `.grad` facility.
3. Can also handle the case of the user passing in implicit constraints via flags (such as `diag, PSD, NSD, nonpos` etc. by checking dual cone membership of the computed gradient instead of stationarity)

I have added in tests for this new method which live in `cvxpy/tests/test_KKT.py` --- where all of the standard test classes from `SolverTestHelpers` make an appearance --- the KKT conditions are verified in full for all of the tests (with the exception of MI-programs)  in the `solver_test_helpers.py` file.

I haven't added documentation for this method yet since it just lives within the `SolverTestHelper` class as of now --- we can probably write a full class for verifying the KKT conditions after proper support for verifying dual feasibility has been added (via the introduction of the `dual` method on `Constraint` objects).

## Type of change
- [x] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [ ] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [x] Write unittests.
- [x] Run the unittests and check that they’re passing.
- [x] Run the benchmarks to make sure your change doesn’t introduce a regression.

2023-07-25 13:41 UTC, rileyjmurray commented on cvxpy/tests/test_KKT.py
> +        sth.check_stationary_lagrangian(places=2)
You don't need to use ``verify_objective``, or ``verify_primal_values``, or ``verify_dual_values`` here. Just check the KKT conditions.

2023-07-25 13:42 UTC, rileyjmurray commented on cvxpy/tests/test_KKT.py
> +class StandardTestSOCPs(BaseTest):
Update these tests to only check the KKT conditions.

2023-07-25 13:43 UTC, rileyjmurray commented on cvxpy/tests/test_KKT.py
Naming conventions of classes: test classes start with ``Test...``. The convention you're using here is like for classes in ``solver_test_helpers.py``, which is not actually dispatched by a test runner.

2023-07-25 13:43 UTC, rileyjmurray commented on cvxpy/tests/test_KKT.py
> +    def tf_1() -> STH.SolverTestHelper:
What's the ``tf`` stand for here?

2023-07-25 13:44 UTC, rileyjmurray commented on cvxpy/tests/test_KKT.py
> +        # places is set to 3 rather than 4, because analytic solution isn't known.
This is actually a great example where we don't need to know the analytic solution. Just check the KKT conditions to the usual level of accuracy.

2023-07-25 13:45 UTC, rileyjmurray commented on cvxpy/tests/test_KKT.py
Separately: there are no tests for exponential cone constraints here.

2023-07-25 13:46 UTC, rileyjmurray requested changes
See my individual comments.

2023-07-31 12:35 UTC, aryamanjeendgar commented
@rileyjmurray I think I should've addressed your suggested changes with this commit, please take a look whenever you get time!

2023-08-03 19:59 UTC, rileyjmurray commented
Failing tests are unrelated to this PR.

2023-08-03 20:00 UTC, rileyjmurray commented on cvxpy/tests/test_KKT.py
> +    def tf_1() -> STH.SolverTestHelper:
The nature of the flag isn't obvious from the name itself. (Resolved with the latest naming convention I committed to your branch.)

2023-08-03 20:01 UTC, rileyjmurray approved these changes

2023-08-03 20:07 UTC, merged