Adding functionality to cvxpy/tests: verifying dual feasibility for `Constraint` classes as part of the KKT conditions
cvxpy/cvxpy pull request #2204
Opened 2023-08-05 19:21 UTC by aryamanjeendgar

This PR introduces the `dual_cone` methods for every `Constraint` class (which support dual variable recovery, which is all of them, with the exception of `PowConeND` and `OpRelEntrConeQuad`). A complementary `dual_violation` method if also implemented for ease in actually performing the feasibility checks.

These methods are used to update the existing `check_dual_domains` method in `solver_test_helpers.py` --- all the existing tests in `test_KKT.py` remain the same as they were when introduced as part of the `check_stationary_lagrangian` PR, and they all pass.

Again, I haven't added documentation for this method yet since it just lives within the `SolverTestHelper` class as of now.

## Type of change
- [x] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [x] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [x] Write unittests.
- [x] Run the unittests and check that they’re passing.
- [x] Run the benchmarks to make sure your change doesn’t introduce a regression.

2023-08-05 19:22 UTC, aryamanjeendgar commented
Tagging @rileyjmurray for review!

2023-08-10 13:39 UTC, rileyjmurray commented
@aryamanjeendgar one small comment. Your ``dual_violation`` function accesses the ``residual`` field of a constraint returned by ``CON.dual_cone``. It would make more sense if you named this function ``dual_residual`` instead. So the ``ExpCone`` constraint would look like the following
```
def dual_residual(self):
        return ExpCone.dual_cone(*self.dual_variables).residual
```
On that note, I'd like to suggest that ``dual_residual`` functions have the ``@property`` decorator so that you can access ``con.dual_residual`` just like you'd access ``con.residual``.

2023-08-10 22:21 UTC, rileyjmurray commented
My intuition tells me that ``dual_cone`` and ``dual_residual`` should be defined in a base class somewhere. The problem is that ``dual_cone`` makes little sense for algebraic constraints and basically no sense for constraints like ``FiniteSet``. 

Perhaps this is the time to add a ``Cone`` interface class from which all conic constraints can inherit. If we did this, then we could even write a one-size-fits-all implementation for ``dual_residual``:
```
@property
def dual_residual
    return self.dual_cone(*self.args).residual
```

 @SteveDiamond @akshayka @phschiele, what do you three think about adding such a ``Cone`` interface class? (If you need more context please do ask.)

2023-08-11 00:52 UTC, SteveDiamond commented on cvxpy/constraints/exponential.py
> +    @staticmethod
staticmethod doesn't seem right...

2023-08-11 00:53 UTC, SteveDiamond commented
> My intuition tells me that `dual_cone` and `dual_residual` should be defined in a base class somewhere. The problem is that `dual_cone` makes little sense for algebraic constraints and basically no sense for constraints like `FiniteSet`.
> 
> Perhaps this is the time to add a `Cone` interface class from which all conic constraints can inherit. If we did this, then we could even write a one-size-fits-all implementation for `dual_residual`:
> 
> ```
> @property
> def dual_residual
>     return self.dual_cone(*self.args).residual
> ```
> 
> @SteveDiamond @akshayka @phschiele, what do you three think about adding such a `Cone` interface class? (If you need more context please do ask.)

What about ``Cone`` as a subclass of ``Constraint``?

2023-08-14 13:16 UTC, rileyjmurray commented
Replying to @SteveDiamond :
> What about Cone as a subclass of Constraint?

I really like that approach. I wanted to get buy-in from others (e.g., you) before suggesting that @aryamanjeendgar go that route.

@aryamanjeendgar please create a new file ``cvxpy/constraints/cones.py`` that defines an abstract class ``Cone(Constraint)``. That class should have a (non-static!) ``dual_cone`` method that raises a ``NotImplementedError`` by default. It should also have a ``dual_residual`` property that uses my implementation suggested above. Once that class is defined, please update all existing conic constraints to formally subclass it.

2023-08-14 17:49 UTC, phschiele commented
I like the idea as well. As I've mentioned before, this could immediately use the common need of adding dual constraints, see, e.g., [here](https://github.com/cvxgrp/dsp/blob/f485eeefe089a4f897130929048159d4b4751ca0/dsp/cone_transforms.py#L380).

Would we also change the inheritance structure of existing cone constraints? I believe it could be considered nonbreaking, as `isinstance(c, Constraint)` would still be valid.

For reference, here is the current type hierarchy for `Constraint`:
![image](https://github.com/cvxpy/cvxpy/assets/44360364/eb7ea3c8-5001-4d4c-8645-c1412fc75b14)

2023-08-14 18:54 UTC, rileyjmurray commented
I would consider it a non-breaking change to change the inheritance
structure in this way

On Mon, Aug 14, 2023 at 1:49 PM Philipp Schiele ***@***.***>
wrote:

> I like the idea as well. As I've mentioned before, this could immediately
> use the common need of adding dual constraints, see, e.g., here
> <https://github.com/cvxgrp/dsp/blob/f485eeefe089a4f897130929048159d4b4751ca0/dsp/cone_transforms.py#L380>
> .
>
> Would we also change the inheritance structure of existing cone
> constraints? I believe it could be considered nonbreaking, as isinstance(c,
> Constraint) would still be valid.
>
> For reference, here is the current type hierarchy for Constraint:
> [image: image]
> <https://user-images.githubusercontent.com/44360364/260531001-eb7ea3c8-5001-4d4c-8645-c1412fc75b14.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cvxpy/cvxpy/pull/2204#issuecomment-1677807228>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACRLIFA4UE7FJJAC2BXME6TXVJQLNANCNFSM6AAAAAA3FMP44U>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-16 12:30 UTC, rileyjmurray requested changes
These changes don't really make sense. They're a big departure from what we had before.

2023-08-16 12:30 UTC, rileyjmurray commented on cvxpy/constraints/cones.py
> +        raise NotImplementedError
I think ``dual_cone`` should have the same signature as ``__init__`` as far as ``args`` go.

2023-08-16 12:30 UTC, rileyjmurray commented on cvxpy/constraints/cones.py
> +        return self.dual_cone().residual
We need to unpack ``return self.dual_cone(*self.dual_variables).residual``.

2023-08-16 12:30 UTC, rileyjmurray commented on cvxpy/constraints/power.py
> +        return PowCone3D(self.x/self.alpha, self.y/(1-self.alpha), self.z, self.alpha)
This is just ... wrong? What's the semantic or mathematical meaning of the returned constraint?

2023-08-17 11:54 UTC, rileyjmurray commented on cvxpy/constraints/psd.py
> +        See Pg 85 of the MOSEK modelling cookbook for more information"""
This docstring is copy-pasted.

2023-08-21 11:07 UTC, rileyjmurray commented on cvxpy/constraints/cones.py
> +    CVXPY supports modelling using the following cones as of today:
modelling --> modeling

2023-08-21 11:08 UTC, rileyjmurray commented on cvxpy/constraints/cones.py
> +    def dual_cone(self, args: list['cp.Expression'] | None = None) -> typing.Type['Cone']:
@aryamanjeendgar please make this a private method by renaming it to ``_dual_cone`` as we discussed.

2023-08-21 11:08 UTC, rileyjmurray commented on cvxpy/constraints/cones.py
> +    # def dual_cone(self, args) -> typing.Type['Cone']:
Remove this comment.

2023-08-21 11:09 UTC, rileyjmurray commented on cvxpy/constraints/cones.py
> +        Primarily intended to be used for full-fledged KKT checks
In
``Primarily intended to be used for full-fledged KKT checks``
remove "full-fledged".

2023-08-21 11:10 UTC, rileyjmurray commented on cvxpy/constraints/power.py
> +    def dual_cone(self, *args):
Make sure that when you change ``dual_cone`` to ``_dual_cone`` in ``cones.py`` you also make that change in the various classes (like this one).

2023-08-21 11:16 UTC, rileyjmurray commented on cvxpy/tests/solver_test_helpers.py
> +                                cp.constraints.SOC)):
This if-statement can be simplified to ``if isinstance(con, cp.constraints.Cone)``.

2023-08-21 11:19 UTC, rileyjmurray requested changes
See my individual comments.

2023-08-22 01:06 UTC, rileyjmurray commented
@aryamanjeendgar this generally looks good. Please make changes to the type annotations so that tests pass on Python 3.8. Once that's done we can request approval from another maintainer before merging.

2023-08-29 15:31 UTC, rileyjmurray approved these changes
Failing benchmarks are unrelated to this PR. I'm marking this as approved now. This doesn't change our public API so we don't need approval from a second maintainer to merge. But I'll wait until tomorrow morning ET before merging in case @SteveDiamond or @phschiele have comments they'd like to leave.

2023-08-30 14:47 UTC, phschiele approved these changes

2023-08-30 16:35 UTC, merged