Dual variables for `PowConeND`!!!
cvxpy/cvxpy pull request #2241
Opened 2023-10-01 19:10 UTC by aryamanjeendgar

## Description
This PR implements (long-coming \:)) for `PowConeND`.

The major logic of the implementation is couched inside of `invert::Exotic2Common::exotic2common.py` --- in addition, keeping in line with my on-going contributions for building a user-level infrastructure around optimality condition verification in CVXPY, I have also implemented the `_dual_cone` method for `PowConeND` (so now, one can call `dual_residual` and verify dual-feasibility for their programs involving `PowConeND`).

The tests can be found inside of `test_KKT.py` (I decided to use the existing KKT infrastructure for verifying the correctness of my implementation)

 Issue link (if applicable): #1222 

## Type of change
- [x] New feature (backwards compatible)
- [] New feature (breaking API changes)
- [] Bug fix
- [] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [*] Add our license to new files.
- [*] Check that your code adheres to our coding style.
- [*] Write unittests.
- [*] Run the unittests and check that they’re passing.
- [*] Run the benchmarks to make sure your change doesn’t introduce a regression.

2023-10-01 19:11 UTC, aryamanjeendgar commented
Tagging @rileyjmurray @SteveDiamond @phschiele for review and suggestions, thanks!

2023-10-03 01:57 UTC, PTNobel requested changes
I skipped reviewing the tests and didn't check the math, but had a few comments on the code style.

2023-10-03 01:57 UTC, PTNobel commented on cvxpy/reductions/cone2cone/exotic2common.py
> +                idx = int(f'{cons_id}')
What is going on here? This is strange notation. Why turn it into a string?

2023-10-03 01:57 UTC, PTNobel commented on cvxpy/reductions/cone2cone/exotic2common.py
> +                div_size = int(dvars[idx].shape[1] / cons.args[1].shape[0])
Should we use integer division `\\` instead? This risks weird truncation issues with floating points.

2023-10-03 02:22 UTC, rileyjmurray commented on cvxpy/constraints/power.py
> +            args_shapes = list(map(f, args))
Agreed

2023-10-03 02:22 UTC, rileyjmurray commented on cvxpy/reductions/cone2cone/exotic2common.py
> +                idx = int(f'{cons_id}')
Good question. @aryamanjeendgar?

2023-10-03 02:23 UTC, rileyjmurray commented on cvxpy/reductions/cone2cone/exotic2common.py
> +                div_size = int(dvars[idx].shape[1] / cons.args[1].shape[0])
I agree that integer division would be preferable (but it's ``//``, not ``\\``).

2023-10-03 17:05 UTC, rileyjmurray commented on cvxpy/constraints/power.py
> +            args_shapes = list(map(f, args))
Yes, I'd make the change to list comprehensions in the other classes as well. Thanks for checking!

2023-10-04 16:17 UTC, rileyjmurray approved these changes
Looks good to me!

2023-10-04 16:19 UTC, merged