Adding the ability to generate torch expressions
cvxpy/cvxpy pull request #2283
Opened 2023-10-31 18:50 UTC by AmitSolomonPrinceton

## Description
This change allows users to generate torch expressions from expressions and constraints, by using a new method called gen_torch_exp. Also added unittests for the new functionality, and one for each changed atom. This work continues the discussion in #torch_numeric in the Discord channel.
Issue link (if applicable):

## Type of change
- [X] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [X] Add our license to new files.
- [X] Check that your code adheres to our coding style.
- [X] Write unittests.
- [X] Run the unittests and check that they’re passing.
- [X] Run the benchmarks to make sure your change doesn’t introduce a regression.
====================================================================================== test session starts ======================================================================================
platform darwin -- Python 3.11.5, pytest-7.4.0, pluggy-1.0.0
rootdir: /Users/as3993/Amit/cvxpy
configfile: pyproject.toml
plugins: anyio-4.0.0, typeguard-3.0.2
collected 12 items                                                                                                                                                                              

cvxpy/tests/test_benchmarks.py ss-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Oct 31 02:49:08 PM: Compiling problem (target solver=ECOS).
(CVXPY) Oct 31 02:49:08 PM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Oct 31 02:49:08 PM: Applying reduction Dcp2Cone
(CVXPY) Oct 31 02:49:08 PM: Applying reduction CvxAttr2Constr
(CVXPY) Oct 31 02:49:08 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Oct 31 02:49:09 PM: Applying reduction ECOS
(CVXPY) Oct 31 02:49:09 PM: Finished problem compilation (took 2.831e-01 seconds).
Issue #1668 regression test
Compilation time:  0.2837810516357422
.least_squares: avg=2.010e-03 s , std=0.000e+00 s (1 iterations)
.ssqp: avg=3.008e-03 s , std=0.000e+00 s (1 iterations)
.small_cone_matrix_stuffing: avg=1.126e-02 s , std=1.509e-03 s (10 iterations)
.small_lp: avg=7.981e-03 s , std=0.000e+00 s (1 iterations)
small_lp_second_time: avg=4.008e-04 s , std=0.000e+00 s (1 iterations)
.sss

======================================================================================= warnings summary ========================================================================================
../../anaconda3/envs/lropt_cvxpy/lib/python3.11/site-packages/diffcp/cones.py:7
../../anaconda3/envs/lropt_cvxpy/lib/python3.11/site-packages/diffcp/cones.py:7
  /Users/as3993/anaconda3/envs/lropt_cvxpy/lib/python3.11/site-packages/diffcp/cones.py:7: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if StrictVersion(scs.__version__) >= StrictVersion('3.0.0'):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================================================================== 5 passed, 7 skipped, 2 warnings in 1.45s ============================================================================

2023-10-31 18:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=2283) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=2283) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cvxpy/cvxpy?pullRequest=2283) it.</sub>

2023-10-31 19:04 UTC, SteveDiamond commented
This is nice work, but it makes torch a dependency of cvxpy, which we don't want.

2023-11-02 17:07 UTC, SteveDiamond commented on lropt/pyvenv.cfg
> +home = /Users/as3993/anaconda3/envs/lropt/bin
accidentally included this file.

2023-11-02 17:07 UTC, SteveDiamond commented on cvxpy/tests/test_atoms.py
> +class TestTorchNumeric(BaseTest):
Nice tests! Maybe it should go in a separate file though?

2023-11-02 17:08 UTC, SteveDiamond commented on cvxpy/tests/test_atoms.py
> +class TestTorchNumeric(BaseTest):
I usually do one class per test file.

2023-11-02 17:08 UTC, SteveDiamond commented
> Thanks for the input, I updated the PR. Torch will no longer be a dependency of cvxpy, but is rather imported during a call to torch_numeric.

Ok sg. Great work on this MR! It might be close to mergeable.

2023-11-02 21:44 UTC, PTNobel commented
Should we add torch as an optional dependency?

2023-11-07 19:20 UTC, SteveDiamond commented on cvxpy/atoms/atom.py
> +class VariablesDict():
What is this about?

2023-11-07 19:21 UTC, SteveDiamond commented on cvxpy/atoms/atom.py
>  class Atom(Expression):
I don't love the changes to this class. Please discuss with us about the overall picture.

2023-11-09 16:19 UTC, AmitSolomonPrinceton commented on cvxpy/atoms/atom.py
> +class VariablesDict():
It's an enum to tell apart between variables/parameters, constants, and expressions.

2023-11-10 02:07 UTC, SteveDiamond commented on cvxpy/atoms/atom.py
> +            def transpose_if_matmul(self, res, should_transpose):
Wrapping with transpose in all cases seems to be more important than I had understood. I am open to changing how transpose works in expression.py.

2023-11-10 15:02 UTC, rileyjmurray requested changes
IMO, we need detailed web documentation before merging this kind of functionality. I'd like for some of the docs to be written for developers, not just users.

A detailed overview of changes should probably be given at the top-level comment of this PR.

2023-11-10 19:01 UTC, SteveDiamond commented on cvxpy/atoms/atom.py
> +    def gen_torch_exp(self):
gen_torch_exp should be a function in the Expression class, not the Atom class.

2024-01-18 02:53 UTC, rileyjmurray commented
Just popping in to say that I will want to review this thoroughly before it’s merged. Once it reaches a plausible level of maturity please request me as a reviewer!

2024-05-13 13:11 UTC, phschiele commented
@AmitSolomonPrinceton Great to see you updated this PR! It would be nice to have this functionality in 1.6.
Are there any open todos from your side here?

@rileyjmurray asked for a high level overview of changes before his review.
I think it would be important to also add documentation for this feature.
Maybe we can write some sort of a meta test that checks that all classes in the `cvxpy` namespace that implement `numeric` also implement `torch_numeric`?

2024-05-22 17:33 UTC, AmitSolomonPrinceton commented
> @AmitSolomonPrinceton Great to see you updated this PR! It would be nice to have this functionality in 1.6. Are there any open todos from your side here?
> 
> @rileyjmurray asked for a high level overview of changes before his review. I think it would be important to also add documentation for this feature. Maybe we can write some sort of a meta test that checks that all classes in the `cvxpy` namespace that implement `numeric` also implement `torch_numeric`?

Thanks @phschiele! I still iron some details (as you can see from commits, mainly working with sparse tensors).
What would you like to see in the documentation?

2024-05-28 21:03 UTC, PTNobel commented
>  What would you like to see in the documentation?

Hey Amit, are you on the CVXPY Discord? It might be easier to brainstorm the docs there and/or just a schedule a call. Personally, I think adding a section to the user guide on derivatives would be ideal.

2024-08-13 09:03 UTC, AmitSolomonPrinceton commented
@rileyjmurray @PTNobel I added a Torch expressions section to index.rst. Please let me know if this is what you had in mind and if there is anything else you would like me to add to the PR.

2024-08-13 21:43 UTC, Transurgeon reviewed
Nice work overall. Had a few concerns about duplicated code and am not really sure what is going in the tests, please have a look when possible.
Thought I would give a quick review before @rileyjmurray has a look.

P.S. Since the API is so similar to NumPy for the majority of torch_numeric functions you have added, I am wondering if we could somehow make use of the Scientific [Python Array API standard](https://data-apis.org/array-api/latest/purpose_and_scope.html) (which includes Pytorch and others) to generalize this? Would be happy to discuss more.

2024-08-13 21:43 UTC, Transurgeon commented on cvxpy/atoms/affine/reshape.py
> +            return tensor_reshape_fortran(values[0], self.shape)
a bit nitpicky, but a more compact way to do this could be something like the following:
``torch.reshape(values[0].T, shape[::-1]).T``. See the stackoverflow [discussion](https://stackoverflow.com/questions/64433896/pytorch-equivalent-of-numpy-reshape-function)

2024-08-13 21:43 UTC, Transurgeon commented on cvxpy/atoms/affine/transpose.py
> +        return values[0].T
For dimensions greater than 2, I believe using ``.T`` behaves differently as transposing with axes. I don't think it's a big deal, but something to keep in mind. Maybe it would be better to keep using ``torch``?

2024-08-13 21:43 UTC, Transurgeon commented on cvxpy/atoms/affine/upper_tri.py
> +        return value
I think you wrote this function twice. Also, I am not sure using for loops is the best solution for performance. Could you try to improve this using torch natively, if it's even possible?

2024-08-13 21:43 UTC, Transurgeon commented on cvxpy/atoms/atom.py
> +from cvxpy.expressions.constants.constant import Constant
agreed with Steven's comment below. You changed the import but it doesn't seem like it's doing anything. Could you have another look at the file changes here please?

2024-08-13 21:43 UTC, Transurgeon commented on cvxpy/expressions/leaf.py
> +        return tmp_aff_exp.gen_torch_exp()
this function is also a duplicate of lines ``556-563`` above. Also it is not clear what this function is doing. It seems like you are using it in constraints, but an explanation would be nice.

2024-08-13 21:43 UTC, Transurgeon commented on cvxpy/tests/test_constraints.py
> +        self.assertTrue((test7==n*np.ones((m,m))).all())
these tests seem very similar than the lines you have added from 400-468. I am not very sure what is going on.
I think generally we prefer breaking the tests into multiple smaller tests. For your case, it could be one test for each torch numeric function that you have implemented.

2024-08-14 09:42 UTC, AmitSolomonPrinceton commented on cvxpy/atoms/atom.py
> +from cvxpy.expressions.constants.constant import Constant
Could you please elaborate what you mean by this comment? This import is needed.

2024-08-14 09:54 UTC, AmitSolomonPrinceton commented on cvxpy/expressions/leaf.py
> +        return tmp_aff_exp.gen_torch_exp()
Thanks for catching this. This function creates a torch expression for a leaf, as described in the docstring.

2024-08-14 09:59 UTC, AmitSolomonPrinceton commented on cvxpy/tests/test_constraints.py
> +        self.assertTrue((test7==n*np.ones((m,m))).all())
Thanks for catching the duplicate definition (I don't know what caused all of these duplicate definitions). This test is a general test to check that multiple constraints can generate torch_expressions (as opposed to say expressions). The only way I see to break this test would be into 7 different tests, one for each constraint. Would you like me to do that?

2024-08-14 14:00 UTC, PTNobel reviewed
I didn't do a full review, but I'm a little concerned about how you handled constants. See a comment below.

2024-08-16 00:59 UTC, rileyjmurray commented on cvxpy/atoms/affine/reshape.py
> +            return tensor_reshape_fortran(values[0], self.shape)
@Transurgeon, it looks like the implementation of ``tensor_reshape_fortran`` has been revised to use your suggested approach. I prefer to call the explicit helper function in this case since it's easier to read. Can we mark this as resolved?

2024-08-16 02:56 UTC, rileyjmurray requested changes
This is a monster of a project! Thanks for all the hard work in getting this far, @AmitSolomonPrinceton. I've left many comments that I'd like you to address. 

## Most important comments

I'd like the semantics of``torch_numeric`` and ``gen_torch_exp`` clearly defined in the appropriate base classes (I think ``Atom`` and ``Expression`` are the appropriate base classes, but I could be wrong).

Here is a template for the kind of specification that I'm looking for.
```python
class SomewhatAbstractClass:
    ... 
    def fairly_abstract_operation(self, ...):
        """
        Implementations of this function perform  <operation involving args>, where <args> are <some datatype>
        representations of <some mathematical objects>, and <operation> can be anything that <properties>.

        For example, if <the operation> was <specific example here>, then a conformant
        implementation might look like:

        .. code:: python

            # Some Python code.
            # A little more Python code.
            # Just a teeny bit more code. But not too much!


        """
        raise NotImplementedError()
```

I also have a handful of comments that I didn't attach to a single file or block of code.

## Handling torch imports

I think importing torch in every function that needs it introduces excessive overhead, and it prevents you from using type annotations. I recently need to add torch functionality to a project that includes some amount of optimization modeling, and I found the following techniques helpful:

* An example that handles the type annotation issue. https://github.com/sandialabs/pyGSTi/blob/911118c3965a4714cbdef3e883e942d1e8c3c6eb/pygsti/modelmembers/torchable.py#L15-L18
* An example that handles type annotation and function invocation: https://github.com/sandialabs/pyGSTi/blob/911118c3965a4714cbdef3e883e942d1e8c3c6eb/pygsti/modelmembers/states/tpstate.py#L14-L21 

## Misc

The screenshot below shows deferences to intf.sparse and scipy.sparse that I wouldn't expect inside these torch-related functions.
<img width="1393" alt="Pasted Graphic 1" src="https://github.com/user-attachments/assets/59ca2bad-ef3c-4fa7-afb1-bc41bd8ecb70">

The screenshot below shows us using python's ``reduce`` function. Can you please verify that using reduce is compatible with the automatic differentiation features of pytorch?
<img width="1066" alt="Pasted Graphic 2" src="https://github.com/user-attachments/assets/1c3483c8-ea8f-4b58-b54e-beb838d9e516">

2024-08-16 02:56 UTC, rileyjmurray commented on cvxpy/expressions/expression.py
> +            return self.numeric(values)
The rationale for this function isn't clear to me. My instinct is to let the user figure out the AttributeError on their own. Alternatively, we could have a default implementation of ``torch_numeric`` for the Expression class that just raises a NotImplementedError.

2024-08-16 02:56 UTC, rileyjmurray commented on cvxpy/expressions/expression.py
> +        """
We'll definitely want more documentation here.

2024-08-16 02:56 UTC, rileyjmurray commented on cvxpy/expressions/expression.py
> +        return partial(wrapped_func, self, ind_to_value_type, vars_dict), vars_dict
All of this code is duplicated from lines 798 -- 1052, and should be removed.

2024-08-16 02:56 UTC, rileyjmurray commented on cvxpy/expressions/leaf.py
> +        self._bounds = value
This code is duplicated from lines 556 to 604, and should be removed.

2024-08-16 02:56 UTC, rileyjmurray commented on cvxpy/expressions/leaf.py
> +        return tmp_aff_exp.gen_torch_exp()
Hi, @AmitSolomonPrinceton. I have to agree with @Transurgeon that the purpose of this function is unclear. What is the formal mathematical meaning of "generating a torch expression for a leaf"? I think this would be clearer if ``Expression`` had a detailed explanation of the intended semantics of ``gen_torch_expr``.

2024-08-16 02:56 UTC, rileyjmurray commented on cvxpy/interface/matrix_utilities.py
> +import torch
Don't have a bare import statement for torch. We can't be certain that it will be installed.

2024-08-16 02:56 UTC, rileyjmurray commented on cvxpy/interface/numpy_interface/tensor_interface.py
> +Copyright 2013 Steven Diamond
Please use an appropriate copyright assertion. E.g,, "Copyright 2024, the CVXPY Authors"

2024-08-16 02:56 UTC, rileyjmurray commented on cvxpy/interface/numpy_interface/tensor_interface.py
> +import torch
A bare import of torch _might_ be okay at this point in the code, but I would prefer if you had a guard against the possibility that torch isn't available.

2024-08-16 02:56 UTC, rileyjmurray commented on cvxpy/interface/numpy_interface/tensor_interface.py
A meta-comment for @AmitSolomonPrinceton.

@PTNobel pointed out a few places where we ought to be explicit about whether a tensor is created on the CPU or GPU. This file might be a good place to add the logic that handles that for us in a clean way. I'd also suggest _not_ using torch.float64 as the precision everywhere. There are some hardware accelerators -- like Apple's Metal Performance Shaders -- that only support 32-bit precision. Users who want 64 bit by default can set with with this function: https://pytorch.org/docs/stable/generated/torch.set_default_dtype.html.

2024-08-16 02:56 UTC, rileyjmurray commented on cvxpy/tests/test_constraints.py
I can't really assess the appropriateness of these tests, since I don't know the intended semantics of ``gen_torch_exp()``.

2024-08-16 02:56 UTC, rileyjmurray commented on cvxpy/tests/test_torch_numeric.py
> +        This funciton tests if atom.torch_numeric is correct.
"funciton" should be "function"

2024-08-16 02:56 UTC, rileyjmurray commented on cvxpy/tests/test_torch_numeric.py
> +        This funciton tests if atom.torch_numeric is correct.
Please elaborate on what it means for an atom's implementation of ``torch_numeric`` to be correct.

2024-08-16 02:56 UTC, rileyjmurray commented on cvxpy/tests/test_torch_numeric.py
> +        def perform_test(atom, in_np, in_tch):
Please use a more descriptive name. E.g., ``check_torch_against_numeric``

2024-08-16 02:56 UTC, rileyjmurray commented on cvxpy/utilities/torch_utils.py
> +Copyright 2013 Steven Diamond
Please use an appropriate copyright assertion.

2024-08-16 02:56 UTC, rileyjmurray commented on cvxpy/utilities/torch_utils.py
> +    def __init__(self, provided_vars_list: list=[]):
Don't use mutable defaults: https://florimond.dev/en/posts/2018/08/python-mutable-defaults-are-the-source-of-all-evil.

2024-08-16 02:56 UTC, rileyjmurray commented on pyproject.toml
> +    "torch",
Don't include torch as a required dependency.

2024-08-16 02:56 UTC, rileyjmurray commented on cvxpy/atoms/dotsort.py
>              -> Tuple[np.ndarray, np.ndarray]:
The changes to this function make the type annotation incorrect.

2024-08-16 04:45 UTC, Transurgeon commented on cvxpy/atoms/affine/reshape.py
> +            return tensor_reshape_fortran(values[0], self.shape)
Yes sure go ahead.

2024-08-16 08:00 UTC, jonathanberthias commented
Hi everyone,

Sorry if this has already been discussed, but I wanted to suggest moving this code to an external package, e.g. `cvxpy-torch`. The reason I'm suggesting this is that almost all the code in this PR is new and does not rely much on private implementations. It would also reduce the maintenance burden for `cvxpy` and cost of implementing new atoms. Many review comments relate to making sure `torch` is an optional dependency, which is a constraint an external package would not have.

I could imagine an interface like:
```python
exp = cp.Variable() ** 2
torch_exp = cvxpy_torch.gen_exp(exp)
```
where `gen_exp` could be a [dispatching function](https://docs.python.org/3/library/functools.html#functools.singledispatch). Or it could use a visitor pattern.

Sorry to intrude so long after this feature has been started, I realize there has already been a lot of work put into this!

2024-08-16 23:07 UTC, SteveDiamond commented
@jonathanberthias we discussed and decided to develop this functionality as a separate package here https://github.com/cvxpy/cvxtorch
We would greatly appreciate your thoughts on how to best approach the problem!

2024-10-11 13:30 UTC, closed without merging