Updates scorecard action
cvxpy/cvxpy pull request #2403
Opened 2024-04-05 23:34 UTC by phschiele

## Description
Scorecard action is failing after (partial) workflow updates.
Update the complete action according to the upstream recommendations:
https://github.com/ossf/scorecard/blob/main/.github/workflows/scorecard-analysis.yml

See https://github.com/ossf/scorecard-action for more information.
Issue link (if applicable):

## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [ ] Add our license to new files.
- [ ] Check that your code adheres to our coding style.
- [ ] Write unittests.
- [ ] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

2024-04-05 23:49 UTC, PTNobel requested changes

2024-04-05 23:49 UTC, PTNobel commented on .github/workflows/scorecards.yml
> +    - main
We don't have a main branch. This should probably be changed to master

2024-04-05 23:52 UTC, phschiele commented on .github/workflows/scorecards.yml
> +    - main
Done in [496f334](https://github.com/cvxpy/cvxpy/pull/2403/commits/496f334c2dca5875978b506593347c6684e04961)

2024-04-06 00:01 UTC, PTNobel approved these changes

2024-04-06 00:02 UTC, merged