solve problem by multiple solvers
cvxpy/cvxpy pull request #2450
Opened 2024-05-20 12:07 UTC by oriyalperin

## Description
As @erelsgl suggested in discussion #1522,
in some problems, some solvers may be better than others, but they might also fail with a SolverError.
Therefore, we've added a new method that allows sending a list of solvers rather than just one.
This function tries them in the order they are provided, and return the first solution for which no SolverError is raised.
Issue link: #1529

## Type of change
- [x] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [ ] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [x] Write unittests.
- [x] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

2024-05-20 12:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=2450) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=2450) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cvxpy/cvxpy?pullRequest=2450) it.</sub>

2024-05-20 17:09 UTC, SteveDiamond commented on cvxpy/problems/problem.py
> +    def solve_multiple_solvers(self, solvers:list[tuple[str, dict] | tuple[str] | str] = None):
This is nice functionality! I don't think we need to support an argument of None, since anyone calling this function should be giving some list of solvers.

2024-05-21 07:02 UTC, oriyalperin commented on cvxpy/problems/problem.py
> +    def solve_multiple_solvers(self, solvers:list[tuple[str, dict] | tuple[str] | str] = None):
Thanks for the review!
I'll remove the support for None.
What about an empty list? Currently, the implementation uses the solve method without arguments in this case.
Do you think I should keep it like that?

2024-05-21 15:48 UTC, SteveDiamond commented on cvxpy/problems/problem.py
> +    def solve_multiple_solvers(self, solvers:list[tuple[str, dict] | tuple[str] | str] = None):
I would say that an empty list should raise a ValueError.

2024-05-21 18:29 UTC, SteveDiamond commented on cvxpy/problems/problem.py
> +    def solve_multiple_solvers(self, solvers:list[tuple[str, dict] | tuple[str] | str] = None):
Yes, these are all ValueError. Let me sync a bit with the other devs though.

2024-05-21 18:48 UTC, oriyalperin commented on cvxpy/problems/problem.py
> +    def solve_multiple_solvers(self, solvers:list[tuple[str, dict] | tuple[str] | str] = None):
Thanks, please let me know if any further changes are needed :)

2024-05-23 05:45 UTC, PTNobel requested changes
Overall I'm positive on this but not a huge fan of the current public API. I left my suggestions. Aditionaly, I don't like `solve_multiple_solvers`, could we call the method `solve_via_chain`, `solve_with_fallback`, `try_solve`, or `try_solve_till_success`? I think Stephen Boyd often uses the term solver chain for this feature; I can ask him next week.

2024-05-23 05:45 UTC, PTNobel commented on cvxpy/problems/problem.py
> +            The solvers to use. For example, ['SCS', ('ECOS'), ('OSQP', {'max_iter':10000})]
Heads up, `('ECOS')` is just a string I think you want `('ECOS',)`. Also, plesae use `'CLARABEL'` as an example instead of ECOS

2024-05-23 05:45 UTC, PTNobel commented on cvxpy/problems/problem.py
> +    def solve_multiple_solvers(self, solvers:list[tuple[str, dict] | tuple[str] | str]):
I feel like there's a lot of `solve` kwargs we should support here, most notably verbose and solver_verbose. Maybe we can add `*args, **kwargs` as arguments here and document it takes all keyword args supported by `.solve` and then call `.solve` as `.solve(solver=solver, *args, **kwargs, **solver_kwargs)`. This will cause errors if someone repeats arguments (which I think is desired).

2024-05-23 05:45 UTC, PTNobel commented on cvxpy/tests/test_problem.py
> +        solvers_no_dict=[(s.OSQP, {'max_iter':1}), (s.CLARABEL)]
```suggestion
        solvers_no_dict=[(s.OSQP, {'max_iter':1}), (s.CLARABEL,)]
```

2024-05-23 06:16 UTC, oriyalperin commented on cvxpy/problems/problem.py
> +    def solve_multiple_solvers(self, solvers:list[tuple[str, dict] | tuple[str] | str]):
It sounds right to me,
but what if a user wants to use different arguments for each solver, or even the same solver in multiple cases?
How can we determine this?

2024-05-23 06:38 UTC, oriyalperin commented on cvxpy/problems/problem.py
> +    def solve_multiple_solvers(self, solvers:list[tuple[str, dict] | tuple[str] | str]):
Do you mean we should add `*args` and `**kwargs` to the function arguments (and keep the solvers name list)?
It sounds right to me, but what if a user wants to use different arguments for each solver, or even the same solver in multiple cases?
Could you demonstrate how you envision the arguments list, please? It would be greatly appreciated.

2024-05-23 22:58 UTC, PTNobel commented on cvxpy/problems/problem.py
> +    def solve_multiple_solvers(self, solvers:list[tuple[str, dict] | tuple[str] | str]):
```suggestion
    def solve_multiple_solvers(self, solvers:list[tuple[str, dict] | tuple[str] | str], *args, **kwargs):
```

2024-05-23 22:59 UTC, PTNobel requested changes

2024-05-23 22:59 UTC, PTNobel commented on cvxpy/problems/problem.py
> +                    solution = self.solve(solver=solver)
```suggestion
                    solution = self.solve(solver=solver, *args, **kwargs)
```

2024-05-23 22:59 UTC, PTNobel commented on cvxpy/problems/problem.py
> +                    solver_name, kwargs = solver
```suggestion
                    solver_name, solver_kwargs = solver
```

2024-05-23 22:59 UTC, PTNobel commented on cvxpy/problems/problem.py
> +                        solution = self.solve(solver=solver_name, **kwargs)
```suggestion
                        solution = self.solve(*args, solver=solver_name, **solver_kwargs, **kwargs)
```

2024-05-23 23:06 UTC, PTNobel commented on cvxpy/problems/problem.py
> +    def solve_multiple_solvers(self, solvers:list[tuple[str, dict] | tuple[str] | str]):
Suggested all the changes I think you need!

2024-05-26 06:36 UTC, oriyalperin commented
@PTNobel thank you for all your suggestions! 

> Overall I'm positive on this but not a huge fan of the current public API. I left my suggestions. Aditionaly, I don't like `solve_multiple_solvers`, could we call the method `solve_via_chain`, `solve_with_fallback`, `try_solve`, or `try_solve_till_success`? I think Stephen Boyd often uses the term solver chain for this feature; I can ask him next week.

That would be great, thanks!

2024-06-03 23:20 UTC, PTNobel commented
Stephen said we should call it a "solver path" in the documentation; he also suggested making it a keyword argument to `.solve` instead of a new public function (maybe `.solve(path=[...])`. I'm wondering if maybe we could just specifialize on if the input is a string or a list to make `.solve(solver=[cp.SCS, cp.CLARABEL])` the API. Thoughts on that @SteveDiamond @phschiele ?

2024-06-03 23:44 UTC, rileyjmurray commented
I’m not sure about “path” as a keyword argument. I’d be in favor of
“solver_path” or “solver_priority” for keyword arguments to prob.solve.

On Mon, Jun 3, 2024 at 7:20 PM Parth Nobel ***@***.***> wrote:

> Stephen said we should call it a "solver path" in the documentation; he
> also suggested making it a keyword argument to .solve instead of a new
> public function (maybe .solve(path=[...]). I'm wondering if maybe we
> could just specifialize on if the input is a string or a list to make .solve(solver=[cp.SCS,
> cp.CLARABEL]) the API. Thoughts on that @SteveDiamond
> <https://github.com/SteveDiamond> @phschiele
> <https://github.com/phschiele> ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cvxpy/cvxpy/pull/2450#issuecomment-2146284194>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACRLIFCZAUD7QOITPGPDR7TZFT24BAVCNFSM6AAAAABH7TE5E2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNBWGI4DIMJZGQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-06-05 03:07 UTC, PTNobel commented
> I’m not sure about “path” as a keyword argument. I’d be in favor of “solver_path” or “solver_priority” for keyword arguments to prob.solve.

Fair! I don't like solver_priority since we fallback to the other solvers instead of giving up, so I think `solver_path` would be a good choice.

2024-06-05 05:16 UTC, erelsgl commented
What if both "solver" and "solver_path" are given?

2024-06-05 06:39 UTC, PTNobel commented
I think that should raise a runtime error.

2024-06-05 10:03 UTC, rileyjmurray commented
That should raise a ValueError

On Wed, Jun 5, 2024 at 2:39 AM Parth Nobel ***@***.***> wrote:

> I think that should raise a runtime error.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cvxpy/cvxpy/pull/2450#issuecomment-2148996445>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACRLIFC22NDBTSI3NOFMKCDZF2XCHAVCNFSM6AAAAABH7TE5E2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNBYHE4TMNBUGU>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-06-05 17:43 UTC, SteveDiamond commented
> Stephen said we should call it a "solver path" in the documentation; he also suggested making it a keyword argument to `.solve` instead of a new public function (maybe `.solve(path=[...])`. I'm wondering if maybe we could just specifialize on if the input is a string or a list to make `.solve(solver=[cp.SCS, cp.CLARABEL])` the API. Thoughts on that @SteveDiamond @phschiele ?

How would this work when you have solver specific arguments to the solve method?

2024-06-05 18:09 UTC, phschiele commented
> > Stephen said we should call it a "solver path" in the documentation; he also suggested making it a keyword argument to `.solve` instead of a new public function (maybe `.solve(path=[...])`. I'm wondering if maybe we could just specifialize on if the input is a string or a list to make `.solve(solver=[cp.SCS, cp.CLARABEL])` the API. Thoughts on that @SteveDiamond @phschiele ?
> 
> How would this work when you have solver specific arguments to the solve method?

Could be `.solve(solver=[(cp.SCS, scs_args), (cp.CLARABEL, clarabel_args)])` but it might be getting complicated at this point.

2024-06-10 10:54 UTC, oriyalperin commented
I've made some changes according to your suggestions. Does this meet your expectations?

2024-06-10 18:34 UTC, PTNobel commented
I like this PR with Oriya's changes. Since this is a change to the public API, let's get maintainer consensus on this proposal before writing the new docs and merging.

2024-06-10 18:35 UTC, PTNobel commented on cvxpy/problems/problem.py
> +            raise ValueError("Solvers list must contain at least one solver.")
This should say solver_path

2024-06-10 18:41 UTC, PTNobel requested changes

2024-06-10 18:41 UTC, PTNobel commented on cvxpy/problems/problem.py
> +            raise ValueError("Solvers list must contain at least one solver.")
```suggestion
            raise ValueError("Solver path must contain at least one solver.")
```

2024-06-10 18:41 UTC, PTNobel commented on cvxpy/problems/problem.py
> +                                *args, **kwargs):
```suggestion
                                args, kwargs):
```

2024-06-10 18:41 UTC, PTNobel commented on cvxpy/problems/problem.py
> +            return self._solve_solver_path(solve_func,solver_path,*args,**kwargs)
```suggestion
            return self._solve_solver_path(solve_func,solver_path, args, kwargs)
```

2024-06-10 18:41 UTC, PTNobel commented on cvxpy/problems/problem.py
> +                        raise ValueError("Solver tuple input must be (str, dict) or (str)")
```suggestion
                        raise ValueError("Solver path entry must be str, tuple[str] or tuple[str, dict[str, Any]]")
```

2024-06-10 18:41 UTC, PTNobel commented on cvxpy/problems/problem.py
> +                                                (str, dict) tuple, (str) tuple, or str.")
Can you define a constant string somewhere and use the same message on line 461 and 463?

2024-06-10 18:41 UTC, PTNobel commented on cvxpy/tests/test_problem.py
> +        ## solver_path ans solver arguments
```suggestion
        ## Specify both solver_path and solver as arguments
```

2024-06-13 16:12 UTC, SteveDiamond commented
This approach looks good to me.

2024-06-13 21:25 UTC, PTNobel approved these changes
Thanks Oriya! Everything looks good on my end.

2024-06-13 21:30 UTC, phschiele commented
We're still missing the documentation for `solve`. Right now, only the private method is documented.

2024-06-13 21:30 UTC, PTNobel commented
This does needs some docs. Certainly it should be added to the .solve docstring and added to this page: https://www.cvxpy.org/tutorial/solvers/index.html Maybe as a new section title "Solver paths" that discusses how this provides a fallback on failure to solve.

2024-06-16 10:09 UTC, oriyalperin commented
I hope I've placed the documentation correctly.
If any adjustments are needed, please let me know.
Thank you!

2024-06-17 08:13 UTC, jonathanberthias commented
Hi, could you clarify what the `tuple[str]` case is for? Don't the `str` and `tuple[str, dict]` cover all cases, i.e. either no solver specific options, or some options?

2024-06-17 10:50 UTC, oriyalperin commented
> Hi, could you clarify what the `tuple[str]` case is for? Don't the `str` and `tuple[str, dict]` cover all cases, i.e. either no solver specific options, or some options?

Hi @jonathanberthias,
Perhaps it should be written as `tuple[str,]` to indicate that the type is a tuple containing only `str`.
The list items can be in three formats:
1. **tuple** of `(str, dict)`, such as `('OSQP', {'max_iter': 10000})`.
2. **tuple** of `(str,)`, such as `('CLARABEL',)`.
3. **string**, such as `'CLARABEL'` or `('CLARABEL')`

2024-06-17 20:37 UTC, jonathanberthias commented
Thanks @oriyalperin for answering so quickly! 

What I meant was, when would it be useful to use the 1-str tuple form (option 2. in your list)? As I see things, I either want to pass solver-specific options and would use option 1., or I don't in which case option 3. is perfect. And if I am writing some generic code where I sometimes want solver-specific options and sometimes not, then I can use option 1. with a perhaps empty dictionary. 

But in no case I could think of would it be useful to pass the solver name in a tuple. 🤔

2024-06-17 23:17 UTC, phschiele commented
@jonathanberthias it would be useful only if the tuple contains multiple strings, e.g., `("CLARABEL", "ECOS")`.

On that note, though, let's update the documentation of both functions to use `Iterable` instead of tuple/list.

2024-06-18 06:44 UTC, oriyalperin commented
> Thanks @oriyalperin for answering so quickly!
> 
> What I meant was, when would it be useful to use the 1-str tuple form (option 2. in your list)? As I see things, I either want to pass solver-specific options and would use option 1., or I don't in which case option 3. is perfect. And if I am writing some generic code where I sometimes want solver-specific options and sometimes not, then I can use option 1. with a perhaps empty dictionary.
> 
> But in no case I could think of would it be useful to pass the solver name in a tuple. 🤔

I agree, it's not necessary at all, it was just to offer an alternative option.
Thanks for pointing that out, I'll remove it.

2024-06-18 08:47 UTC, oriyalperin commented
@phschiele,
1. I need some clarification, does that require supporting all iterable types (dict, str...)?
2. Replacing tuple with `Iterable` - the tuple is only used as an inner type. Do you want to replace it in that context?

2024-06-19 08:06 UTC, erelsgl commented
> On that note, though, let's update the documentation of both functions to use `Iterable` instead of tuple/list.

@phschiele if we use `iterable`, we also implicitly allow `solvers` to be a string (an iterable of chars), which is of course incorrect. So maybe it is better to allow only `list`?

2024-06-19 15:59 UTC, PTNobel commented
> > On that note, though, let's update the documentation of both functions to use `Iterable` instead of tuple/list.
> 
> @phschiele if we use `iterable`, we also implicitly allow `solvers` to be a string (an iterable of chars), which is of course incorrect. So maybe it is better to allow only `list`?

I concur that we should not allow str. I support requiring an explicit list.

2024-06-19 16:14 UTC, phschiele commented
I was suggesting 
```
Iterable[tuple[str, dict] | str]
```
which a single string does not satisfy.

Requiring a list is also fine with me.

2024-06-20 17:34 UTC, oriyalperin commented
Thank you for your feedback and reviews! I really appreciate it.

2024-07-02 23:40 UTC, PTNobel commented
@SteveDiamond did you have outstanding TODOs or can I merge this?

2024-07-03 16:39 UTC, SteveDiamond approved these changes
LGTM

2024-07-04 01:04 UTC, merged