allow M to be a Parameter in the huber function
cvxpy/cvxpy pull request #2462
Opened 2024-05-31 20:13 UTC by syanga

## Description
This change allows the M parameter in the huber function to be a parameter for DPP.

## Type of change
- [x] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [ ] Add our license to new files.
- [ ] Check that your code adheres to our coding style.
- [ ] Write unittests.
- [ ] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

2024-05-31 21:58 UTC, phschiele commented on cvxpy/tests/test_atoms.py
> +        expr = cp.huber(1.0, M)
Probably we should also add a test case for something like `cp.huber(1.0,  2 * M)` (and decide if we want that to work or not).

2024-05-31 23:38 UTC, SteveDiamond commented on cvxpy/atoms/elementwise/huber.py
> +        self.M = M if isinstance(M, Parameter) else self.cast_to_const(M)
This change is not necessary.

2024-05-31 23:48 UTC, SteveDiamond commented on cvxpy/atoms/elementwise/huber.py
> +    def parameters(self):
This function is not necessary I believe.

2024-05-31 23:49 UTC, SteveDiamond commented on cvxpy/atoms/elementwise/huber.py
> +    def parameters(self):
This should be more like ```return super().parameters() + self.M.parameters()```. Your code doesn't handle the case where M is an expression that is parameterized.

2024-06-01 06:46 UTC, PTNobel commented on cvxpy/tests/test_atoms.py
> +        expr = cp.huber(1.0, M)
I think we do want that to work. Do we have any other situation where an affine expression of a parameter wouldn't work?

2024-06-03 02:20 UTC, syanga commented on cvxpy/tests/test_atoms.py
> +        expr = cp.huber(1.0, M)
I added a test for affine expressions.

2024-06-03 05:25 UTC, PTNobel requested changes

2024-06-03 05:25 UTC, PTNobel commented on cvxpy/atoms/elementwise/huber.py
> +        if isinstance(self.M, Parameter):
What if M is a parametrized expression? I don't see why we have an if clause here

2024-06-06 15:54 UTC, PTNobel approved these changes

2024-06-06 17:38 UTC, SteveDiamond commented on cvxpy/tests/test_atoms.py
> +        self.assertAlmostEqual(expr.value, 0.75)
Could we test that huber with parameterized M works properly with DPP? We have had some recent correctness bugs related to DPP so it is important to investigate/cover with tests.

2024-06-07 19:47 UTC, SteveDiamond approved these changes
Thanks!!!

2024-06-07 19:47 UTC, merged

2024-06-07 19:47 UTC, SteveDiamond commented
@syanga nice job!