Adding support for n-dimensional sum(axis, keepdims) operation
cvxpy/cvxpy pull request #2473
Opened 2024-06-14 22:08 UTC by Transurgeon

## Description
This PR is currently WIP and will eventually add support for n-dimensional sum operations with the ability to pass in any axis, including multiple axes as well.

This PR is also a small step towards enabling full nd support in light of cvxpy 2.0, hence I have commented out the ValueErrors for related instances. 

The implementation for nd sum is currently only done in NumPy (supporting parameters as well), we are thus missing both SciPy and parametrized SciPy.

The following are the remaining tasks:
- [ ] figure out issue with sum(index(...)), and incorrect shapes 
- [ ] implement SciPy efficiently (converting to NumPy then back is probably slow)
- [ ] extend the AxisAtom to support passing in multiple axis
- [ ] add a lot more tests, multiple axes and other atoms
Issue link (if applicable):

## Type of change
- [x] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [x] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [x] Write unittests.
- [x] Run the unittests and check that they’re passing.
- [x] Run the benchmarks to make sure your change doesn’t introduce a regression.

2024-06-14 22:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=2473) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=2473) before we can accept your contribution.<br/><hr/>**Transurgeon** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cvxpy/cvxpy?pullRequest=2473) it.</sub>

2024-06-20 19:36 UTC, Transurgeon commented on cvxpy/atoms/affine/sum.py
> +        if s.DEFAULT_CANON_BACKEND == 'CPP':
The following changes are to deal with the disparity between the CPP and python backends.
However, it doesn't work because we can only access the default backend, not the actual backend that is used for canonicalization. 
I was wondering what's the best way to approach this? @phschiele any thoughts? Should we add another global variable for this?

2024-06-20 19:36 UTC, Transurgeon commented on cvxpy/atoms/axis_atom.py
>          else:
This is the case when axis is a Tuple (multiple axes) and we need to iterate through all of them setting the values to one (if keepdims is True) or removing those axes (if keepdims is False)

2024-06-20 19:36 UTC, Transurgeon commented on cvxpy/atoms/axis_atom.py
> +                    raise ValueError(f"axis {axis} is out of bounds for array of dimension {dim}")
I have generalized this function to check for multiple axes.
I also added a case for negative indices by summing dim to it (this is what's happening in Python behind the scenes). I also update the error message to be similar to NumPy's.

2024-06-20 19:36 UTC, Transurgeon commented on cvxpy/expressions/expression.py
> +    @abc.abstractmethod
This way of defining an abstract property is deprecated. See [here](https://stackoverflow.com/a/48710068)

2024-06-20 19:36 UTC, Transurgeon commented on cvxpy/tests/test_atoms.py
> -        self.assertEqual(cp.max(Variable(2), axis=1).shape, (2,))
This test is being replaced below because the behavior will be deprecated in the future. 
See comment [here](https://github.com/cvxpy/cvxpy/issues/1963#issuecomment-1331151141)

2024-06-20 19:36 UTC, Transurgeon commented on cvxpy/tests/test_dqcp.py
> +        self.assertEqual(str(cm.exception), "axis 0 is out of bounds for array of dimension 0")
I encountered a weird bug for cumsum because of the ``validate_arguments`` function changes. 
I will have a further look at the cumsum atom in a future PR. It has yet to be updated for n-dimensional support. 

Also, the cumsum atom seems to behave quite differently than other axis atoms in that the axis that we specify in the argument is actually the axis that is being kept rather than removed (or set to 1, if keepdims is True).

2024-06-20 19:36 UTC, Transurgeon commented on cvxpy/tests/test_expressions.py
> +        assert np.allclose(expr.value, y)
These are the main tests that show the new features introduced in this PR.
We are able to mimic NumPy in many different ways for nd tensors, especially for sum we are able to specify multiple axes.

2024-06-20 19:36 UTC, Transurgeon commented on cvxpy/lin_ops/canon_backend.py
> +                return x.reshape((p, n//d, n), order='F')
This function contains the main changes for cvxpy to support nd sum.
The desired output is explained in greater detail in the test_python_backends file.
The goal is to turn an identity to a reduced matrix representing the summands of the original expression in column major order.
The idea came from @SteveDiamond to do the following:
```py
# Suppose we want to sum Variable(2,2,2)
x = np.eye(8)
out = x.reshape(2,2,2,8).sum(axis=axis).reshape(4,8)
```
Which produces the desired result for general cases. The idea is to keep the columns of the tensor fixed and reshape the remaining dimensions into the shape of the expression, then we simply perform the desired NumPy sum operation and reshape the result back into the desired output shape.
In the code above, p is the number of parameters, d is the output row (basically np.prod the remaining indices after summing) and n is the number of columns (hence ``tensor.shape[-1]``).

2024-06-25 18:13 UTC, SteveDiamond commented on cvxpy/reductions/solvers/solving_chain.py
> +            return "SCIPY"
use the constants from settings.py for SCIPY and CPP, not raw strings.

2024-06-25 20:31 UTC, Transurgeon commented on cvxpy/reductions/solvers/solving_chain.py
> +            return "SCIPY"
ok will make a change now.

2024-06-25 21:10 UTC, Transurgeon commented on cvxpy/atoms/axis_atom.py
>          else:
Code is pretty straightforward to understand. Didn't feel the need to add more changes to the docstrings.

2024-06-25 21:16 UTC, Transurgeon commented
This PR looks good on my end. 
Any feedback, questions or suggestions are very welcome. 
Ping for reviews: @PTNobel @SteveDiamond @phschiele (when you are back from Mexico 😅 ).

Also we should have a discussion about our plans for documenting all this in the future.

2024-06-26 21:21 UTC, SteveDiamond commented on cvxpy/cvxcore/python/cppbackend.py
> +    if linPy.data is not None and linPy.type != "sum_entries":
Can you add a comment about why this is here?

2024-06-26 21:21 UTC, SteveDiamond commented on cvxpy/atoms/affine/sum.py
> +        else:
Could you add a comment about why we have the two cases?

2024-06-26 21:22 UTC, SteveDiamond commented on cvxpy/tests/test_dqcp.py
> +        with self.assertRaises(Exception) as cm:
Can you add a comment that we want this to pass and need to develop a fix?

2024-06-27 00:36 UTC, Transurgeon commented on cvxpy/tests/test_dqcp.py
> +        with self.assertRaises(Exception) as cm:
done.

2024-06-27 00:36 UTC, Transurgeon commented on cvxpy/atoms/affine/sum.py
> +        else:
done.

2024-06-27 00:36 UTC, Transurgeon commented on cvxpy/cvxcore/python/cppbackend.py
> +    if linPy.data is not None and linPy.type != "sum_entries":
done. please let me know if the comments are accurate.

2024-06-27 17:50 UTC, SteveDiamond approved these changes

2024-06-27 17:50 UTC, SteveDiamond commented
This looks good to me.

2024-07-01 06:33 UTC, PTNobel reviewed
I only got through about the first 3rd tonight. Will keep coming back to it. Would appreciate responses to some of my qs tho

2024-07-01 06:33 UTC, PTNobel commented on cvxpy/atoms/affine/sum.py
> +        else:
Is there a reason to have the else case? Couldn't we just replace all this code with the ndarray code?

It would improve coverage and benchmarking on the new code.

2024-07-01 06:33 UTC, PTNobel commented on cvxpy/atoms/atom.py
> -            raise ValueError("Atoms must be at most 2D.")
I am a little hesitant to get rid of the error case in case we release 1.6.0 without finishing ndarrays. Can we leave it in but have it read a global constant for whether to support ndarrays?

2024-07-01 06:33 UTC, PTNobel commented on cvxpy/atoms/axis_atom.py
> +                    raise ValueError(f"axis {axis} is out of bounds for array of dimension {dim}")
Awesome! I assume the negative index behavior is the same as NumPy s?

2024-07-01 06:33 UTC, PTNobel commented on cvxpy/expressions/constants/constant.py
> +        The value of the constant as a string.
```suggestion
         The value of the constant as a string.
```

2024-07-01 06:33 UTC, PTNobel commented on cvxpy/expressions/leaf.py
> -        **Shapes cannot be more than 2D**.
I'm a little skeptical of updating the docs now

2024-07-01 06:33 UTC, PTNobel commented on cvxpy/expressions/leaf.py
> +        self, shape: int | Iterable, value=None, nonneg: bool = False,
Shouldn't it just be int | tuple[int, ...]

2024-07-01 06:33 UTC, PTNobel commented on cvxpy/expressions/leaf.py
> -                             "are not supported.")
Ditto above about deleting errors

2024-07-01 06:33 UTC, PTNobel commented on cvxpy/lin_ops/canon_backend.py
> -            assert len(lin_op.shape) in {0, 1, 2}
Ditto

2024-07-01 17:39 UTC, SteveDiamond commented on cvxpy/atoms/affine/sum.py
> +        else:
The issue is that if we switch over to the ndarray code and remove the else statement, the CPP backend can no longer handle sum_entries. We wanted to keep the CPP backend working for the cases it currently supports. In the long run it would be worthwhile to update the CPP backend so it can handle sum_entries with axis and keepdims arguments, but that was too big a lift for this MR.

2024-07-01 17:39 UTC, SteveDiamond commented on cvxpy/atoms/atom.py
> -            raise ValueError("Atoms must be at most 2D.")
I told @Transurgeon not to use global constants. But we can discuss more.

2024-07-01 20:50 UTC, Transurgeon commented on cvxpy/expressions/leaf.py
> +        self, shape: int | Iterable, value=None, nonneg: bool = False,
resolved.

2024-07-01 20:50 UTC, Transurgeon commented on cvxpy/expressions/leaf.py
> -        **Shapes cannot be more than 2D**.
yea I agree,  I reverted it for now.

2024-07-01 20:52 UTC, Transurgeon commented on cvxpy/atoms/atom.py
> -            raise ValueError("Atoms must be at most 2D.")
I added a global variable ``ALLOW_ND_EXPR``. and for all the ValueError assertions, I first check if allow_nd_expr is false. @PTNobel does this look good to you know?

2024-07-01 20:53 UTC, Transurgeon commented on cvxpy/atoms/affine/sum.py
> +        else:
Yeah I think eventually we would like to simplify this code without the else case.
However, it needs to stay for now to support the CPP backend which doesn't support nd sum, let alone passing in the axis and keepdims params.

2024-07-02 07:35 UTC, PTNobel commented on cvxpy/atoms/affine/sum.py
> +        else:
I think I'm misunderstanding something then. What is `lu`?  I don't see it as a parameter to this function and I think I'm missing where it fits in. Is this part of the backend API? I had thought we had encapsulated those.

2024-07-02 07:53 UTC, PTNobel requested changes

2024-07-02 07:53 UTC, PTNobel commented on cvxpy/lin_ops/canon_backend.py
> +                 assert len(lin_op.shape) in {0, 1, 2}
```suggestion
             assert s.ALLOW_ND_ARRAY or len(lin_op.shape) in {0, 1, 2}
```
And maybe drop the if statement? More readable personally.

2024-07-02 07:53 UTC, PTNobel commented on cvxpy/lin_ops/canon_backend.py
> +                x = x.reshape((p,)+(shape)+(n,), order='F').sum(axis=axis)
Is the parentheses around shape intentional? Looks like you're trying to make a tuple but I don't think you are

2024-07-02 07:53 UTC, PTNobel commented on cvxpy/lin_ops/canon_backend.py
> +                    x = x.toarray().reshape((shape)+(n,), order='F').sum(axis=axis)
The toarray seems concerningly expensive. Am I missing something?

2024-07-02 07:53 UTC, PTNobel commented on cvxpy/atoms/affine/sum.py
> +        else:
Never mind. I read down to lin_utils. I get the issue now.

2024-07-02 07:53 UTC, PTNobel commented on cvxpy/problems/problem.py
> +            prob_max_ndim = max([prob_max_ndim] + [arg._max_ndim() for arg in con.args])
I'm not a huge fan of the list addition. Could we write it as `max(prob_max_ndim, max(arg. ...))`?

2024-07-02 07:53 UTC, PTNobel commented on cvxpy/reductions/solvers/solving_chain.py
> +    TODO: The correct way to do this in the future is to check all nodes of
How is this difference than what you're doing?

2024-07-02 17:35 UTC, Transurgeon commented on cvxpy/reductions/solvers/solving_chain.py
> +    TODO: The correct way to do this in the future is to check all nodes of
Oh yea, nice catch. Steven helped me fix this TODO. I'll remove it.

2024-07-02 17:38 UTC, Transurgeon commented on cvxpy/lin_ops/canon_backend.py
> +                x = x.reshape((p,)+(shape)+(n,), order='F').sum(axis=axis)
nice catch! removed the parentheses in the newest commit.

2024-07-02 17:40 UTC, Transurgeon commented on cvxpy/problems/problem.py
> +            prob_max_ndim = max([prob_max_ndim] + [arg._max_ndim() for arg in con.args])
yea, I agree it's probably better than storing the values in a list. Changed

2024-07-02 17:44 UTC, Transurgeon commented on cvxpy/lin_ops/canon_backend.py
> +                    x = x.toarray().reshape((shape)+(n,), order='F').sum(axis=axis)
I just added a TODO to keep the tensor sparse. The main issue is that there are no >2d sparse representations in SciPy.

2024-07-03 04:16 UTC, PTNobel approved these changes
I have one issue left! Otherwise, this looks great and I'm promerging.

2024-07-03 04:16 UTC, PTNobel commented on cvxpy/atoms/affine/sum.py
>          self, arg_objs, shape: Tuple[int, ...], data=None
Could we pass in an optional argument that says what canonicalization backend is being used and then if we're using SciPy use the new code regardless of axis and keepdim?

2024-07-03 17:22 UTC, Transurgeon commented on cvxpy/atoms/affine/sum.py
>          self, arg_objs, shape: Tuple[int, ...], data=None
I think that's a great idea, but we would need to pass down the canon backend parameter which I am not sure it is easy to do. I am fine with keeping this as is.

2024-07-03 20:38 UTC, SteveDiamond commented on cvxpy/atoms/affine/sum.py
>          self, arg_objs, shape: Tuple[int, ...], data=None
Will and I discussed differentiating more based on the backend during the canonicalization but we chose not to go down that route in this PR.

2024-07-04 00:30 UTC, PTNobel commented on cvxpy/atoms/affine/sum.py
>          self, arg_objs, shape: Tuple[int, ...], data=None
Then I'm good to merge!

2024-07-04 04:21 UTC, merged