adding warning for eventual change of default order
cvxpy/cvxpy pull request #2525
Opened 2024-08-02 21:41 UTC by Transurgeon

## Description
Please include a short summary of the change.
adding warning for not specifying order in reshape, vec and flatten
Issue link (if applicable):

## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [x] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [x] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [x] Write unittests.
- [x] Run the unittests and check that they’re passing.
- [x] Run the benchmarks to make sure your change doesn’t introduce a regression.

2024-08-02 21:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=2525) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=2525) before we can accept your contribution.<br/><hr/>**William Zijie Zhang** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cvxpy/cvxpy?pullRequest=2525) it.</sub>

2024-08-02 22:12 UTC, Transurgeon commented on cvxpy/tests/test_expression_methods.py
> -        """
these tests seem to be duplicated from ``test_expressions``

2024-08-02 22:13 UTC, Transurgeon commented on cvxpy/tests/test_expression_methods.py
> +            X_reshaped = X.reshape((2, 6))
new test to make sure there is a warning when calling reshape without specifying order.

2024-08-02 23:09 UTC, SteveDiamond commented on cvxpy/expressions/expression.py
> +    def flatten(self, order = None):
The type of order is now `order: str | None = None`

2024-08-02 23:10 UTC, SteveDiamond commented on cvxpy/expressions/expression.py
> +    You didn't specify the order of the reshaped expression. The default order
Will this error be confusing for vec/flatten, since it says reshape? They are all sort of reshapes so maybe it's fine.

2024-08-02 23:13 UTC, Transurgeon commented on cvxpy/expressions/expression.py
> +    You didn't specify the order of the reshaped expression. The default order
Yea I agree, we can definitely improve the error message. But I think getting the ``__str__`` of the function name would be a bit too complicated. @PTNobel what do you think?

2024-08-02 23:13 UTC, Transurgeon commented on cvxpy/expressions/expression.py
> +    def flatten(self, order = None):
yea sounds good.

2024-08-02 23:31 UTC, PTNobel requested changes
I think we need to change the warning message depending on context. Otherwise, I'm a bit confused about the testing changes but it is otherwise good!

2024-08-02 23:31 UTC, PTNobel commented on cvxpy/expressions/expression.py
> +    You didn't specify the order of the reshaped expression. The default order
We can just have a FUNC_NAME and then do a string replace in each of the places we use it with context.

2024-08-03 19:56 UTC, Transurgeon commented
> I think we need to change the warning message depending on context. Otherwise, I'm a bit confused about the testing changes but it is otherwise good!

Thanks for the review parth! I just added the changes for FUNC_NAME as you suggested. Please let me know if it looks good now.

As for the test changes, it is a bit unrelated to the PR but I have always wanted to change from unittest to pytest, because the debugging/developer experience is much better. I can always make a separate PR for that if you think it's necessary.

2024-08-05 18:15 UTC, SteveDiamond approved these changes
LGTM!

2024-08-06 00:43 UTC, PTNobel requested changes
I think a number of errors were made in the test conversion. As a general matter I would prefer PRs at least mention when/why they are changing things beyond their title.

2024-08-06 00:43 UTC, PTNobel commented on cvxpy/tests/test_expression_methods.py
> +        np.allclose(b, X.value)
This no longer asserts anything. Is this an intended change?

2024-08-06 00:43 UTC, PTNobel commented on cvxpy/tests/test_expression_methods.py
> +        np.allclose(b, X.value)
DOesn't assert anything?

2024-08-06 00:43 UTC, PTNobel commented on cvxpy/tests/test_expression_methods.py
> +        np.allclose(a_np, x.value)
Similar issue?

2024-08-06 00:43 UTC, PTNobel commented on cvxpy/tests/test_expression_methods.py
> +        np.allclose(A_np, X.value)
Behaviour change that I don't get

2024-08-06 00:43 UTC, PTNobel commented on cvxpy/tests/test_expression_methods.py
> +        np.allclose(A_np, A_cp.value)
Behavior change.

2024-08-06 15:39 UTC, Transurgeon commented on cvxpy/tests/test_expression_methods.py
> +        np.allclose(b, X.value)
no, it's not. I tried to automate things and it caused some mishaps. Sorry about that and nice catch!

2024-08-06 15:40 UTC, Transurgeon commented
> I think a number of errors were made in the test conversion. As a general matter I would prefer PRs at least mention when/why they are changing things beyond their title.

Yes, agreed. I will try to separate PRs in the future. You are right that the test changes are not related to the title of the PR.

2024-08-09 18:52 UTC, SteveDiamond commented
We should add the order argument to the internal reshapes in cvxpy.

2024-08-10 02:16 UTC, PTNobel commented on cvxpy/expressions/expression.py
> +    def reshape(self, shape, order: Optional[str] = None):
Can we switch to using the typing.Literal to specify what orders are allowed?

2024-08-10 02:23 UTC, PTNobel commented
William can you address Steven's suggestion about updating our usage of reshape?

Also, I have more questions about the test changes. Are we running pytest in the CI? Is the idea to change slowly over time? I'm still quite confused about what's happening there.

2024-08-10 21:09 UTC, Transurgeon commented on cvxpy/expressions/expression.py
> +    def reshape(self, shape, order: Optional[str] = None):
yea will do. Thanks for the suggestion.

2024-08-11 03:53 UTC, Transurgeon commented
> William can you address Steven's suggestion about updating our usage of reshape?

Yes. I just made a few commits to address this. I've scanned the whole codebase including tests for instances of reshape, vec and flatten where the order is not specified by default. 

> Also, I have more questions about the test changes. Are we running pytest in the CI? Is the idea to change slowly over time? I'm still quite confused about what's happening there.

I think we are indeed running pytest in the CI, however unittest is also being covered, so no worries on that end. In my opinion, it is just older and less pythonic than pytest (also I might just be used to the later). I decided to revert the changes for now and we could revisit this at a future time, if needed. 

P.S. Sorry about the absurd amount of file changes, hopefully it's not too bad to review.

2024-08-11 04:01 UTC, PTNobel approved these changes
Looks great! Do we want to add any docs for this? My gut is no, the warning is clear enough.

2024-08-11 04:02 UTC, Transurgeon commented
> Looks great! Do we want to add any docs for this? My gut is no, the warning is clear enough.

No I think it's fine. We should definitely remember to add a bullet point in the changelog though (once we release 1.6).

2024-08-16 17:34 UTC, SteveDiamond approved these changes
Very thorough!

2024-08-16 17:34 UTC, merged