Sparsity attribute
cvxpy/cvxpy pull request #2532
Opened 2024-08-12 18:22 UTC by Transurgeon

## Description
This PR attempts to introduce a new attribute for cvxpy expressions: sparsity.
The input must be in a form similar to [np.indices](https://numpy.org/doc/stable/reference/generated/numpy.indices.html) but instead of numpy arrays we only support a list of tuples.
I added a few input validations in a function called ``_validate_sparsity``.
Issue link (if applicable):

## Type of change
- [x] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [x] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [x] Write unittests.
- [x] Run the unittests and check that they’re passing.
- [x] Run the benchmarks to make sure your change doesn’t introduce a regression.

2024-08-12 18:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=2532) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=2532) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Transurgeon<br/>:x: William Zijie Zhang<br/><hr/>**William Zijie Zhang** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cvxpy/cvxpy?pullRequest=2532) it.</sub>

2024-08-12 18:28 UTC, SteveDiamond commented on cvxpy/tests/test_attributes.py
> +            cp.Variable((3, 3), sparsity=[(0, 1), (0, 1), (0, 1)])
I thought we were taking the input as ndarrays?

2024-08-12 19:54 UTC, Transurgeon commented on cvxpy/tests/test_attributes.py
> +            cp.Variable((3, 3), sparsity=[(0, 1), (0, 1), (0, 1)])
yea sorry about that. Let me try to fix it now.

2024-08-12 20:13 UTC, Transurgeon commented on cvxpy/tests/test_attributes.py
> +            cp.Variable((3, 3), sparsity=[(0, 1), (0, 1), (0, 1)])
actually I just tried with list of ndarrays as input and it is also supported. I've added a new test for that in the newest commit.

2024-08-25 04:51 UTC, PTNobel requested changes
I don't look at the test changes, but I'm overall pretty positive on this!

2024-08-25 04:51 UTC, PTNobel commented on cvxpy/expressions/leaf.py
> +            if np.any(indices[:, dim] < 0) or np.any(indices[:, dim] >= self._shape[dim]):
I think it would be better to do `np.array(self._shape)` and then just eliminate the loop

2024-08-25 04:51 UTC, PTNobel commented on cvxpy/expressions/leaf.py
> +        self.sparse_idx = tuple(indices)
Why not keep it an array?

2024-08-25 04:51 UTC, PTNobel commented on cvxpy/expressions/leaf.py
> +        """np.ndarray or None: The numeric value of the expression."""
Can we move the return type to a type annotation?

2024-08-25 04:51 UTC, PTNobel commented on cvxpy/reductions/cvx_attr2constr.py
> +    'sparsity'
I think we should have a trailing comma but maybe that's just my preference

2024-08-25 04:51 UTC, PTNobel commented on cvxpy/reductions/cvx_attr2constr.py
> +                    obj = reshape(full_mat, (n, n))
Why no explicit order?

2024-09-25 01:05 UTC, Transurgeon commented on cvxpy/expressions/leaf.py
> +        """np.ndarray or None: The numeric value of the expression."""
done.

2024-09-25 01:05 UTC, Transurgeon commented on cvxpy/reductions/cvx_attr2constr.py
> +    'sparsity'
done.

2024-09-25 01:05 UTC, Transurgeon commented on cvxpy/reductions/cvx_attr2constr.py
> +                    obj = reshape(full_mat, (n, n))
done.

2024-09-25 03:57 UTC, Transurgeon commented on cvxpy/expressions/leaf.py
> +        self.sparse_idx = tuple(indices)
because it allows us to directly index the expression with the sparsity like this: ``expr[sparsity]``.
also the documentation for [np.nonzero](https://numpy.org/doc/stable/reference/generated/numpy.nonzero.html#numpy.nonzero) returns a tuple of np.ndarrays.

2024-09-25 03:58 UTC, Transurgeon commented on cvxpy/expressions/leaf.py
> +            if np.any(indices[:, dim] < 0) or np.any(indices[:, dim] >= self._shape[dim]):
yea great catch.. I was using chatgpt for some initial prototyping and missed this, thanks!

2024-09-25 05:40 UTC, PTNobel approved these changes
Looks good to me I think

2024-09-25 05:40 UTC, PTNobel commented on cvxpy/expressions/leaf.py
> +    def _validate_indices(self, indices: List[tuple] | tuple[np.ndarray]) -> None:
```suggestion
    def _validate_indices(self, indices: list[tuple[int]] | tuple[np.ndarray]) -> None:
```

2024-09-25 05:42 UTC, PTNobel commented on cvxpy/reductions/cvx_attr2constr.py
> +def convex_attributes(variables) -> List[str]:
```suggestion
def convex_attributes(variables) -> list[str]:
```

2024-09-25 05:42 UTC, PTNobel commented on cvxpy/reductions/cvx_attr2constr.py
> +def attributes_present(variables, attr_map) -> List[str]:
```suggestion
def attributes_present(variables, attr_map) -> list[str]:
```

2024-09-25 05:46 UTC, PTNobel commented
Ah sorry missed that the reduction isn't implemented yet

2024-09-25 13:18 UTC, Transurgeon commented
> Ah sorry missed that the reduction isn't implemented yet

I did implement it [here](https://github.com/cvxpy/cvxpy/pull/2532/files#diff-473769730e5348777c84850d453e9aa50cda2d3cf48cdb2562d541c5ff019069R152-R161)
but I still need to add more tests.

2024-09-25 15:36 UTC, Transurgeon commented on cvxpy/reductions/cvx_attr2constr.py
> +    #TODO add case for sparsity
Ok I think the PR is ready for a more thorough review.
@SteveDiamond does this need to be implemented for this PR? I am not entirely sure what ``recover_value_for_variable`` does here. 
I am planning to add a follow-up PR to this one, for sparse parameters/coo_tensors, maybe I can implement this in the future?

2024-09-25 16:16 UTC, SteveDiamond commented on cvxpy/reductions/cvx_attr2constr.py
> +    #TODO add case for sparsity
I'm not sure. Maybe the project case handles it? The purpose is to set the ._value field of the original sparse variable object.

2024-09-26 14:34 UTC, Transurgeon commented on cvxpy/reductions/cvx_attr2constr.py
> +    #TODO add case for sparsity
yea I think the project case did handle it. I did reimplement the same thing just in case.
Also added a TODO for returning a sparse coo_tensor instead of a dense array.

2024-10-01 23:29 UTC, SteveDiamond approved these changes
lgtm

2024-10-01 23:34 UTC, merged