New CVaR atom
cvxpy/cvxpy pull request #2552
Opened 2024-09-02 07:37 UTC by davidppineiro

## Description
This PR adds the `cvar` atom (conditional value at risk). It is implemented as a wrapper around the existing `dotsort` atom. 

## Type of change
- [X] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [X] Add our license to new files.
- [X] Check that your code adheres to our coding style.
- [ ] Write unittests.
- [ ] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

2024-09-02 07:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=2552) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=2552) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cvxpy/cvxpy?pullRequest=2552) it.</sub>

2024-09-02 23:48 UTC, PTNobel commented
Hey David! I'd encourage that you install and setup the pre-commit hook to make sure your files are properly formatted.

Overall seems like a fine change, but we'll need tests and docs to go with it too.

Tests can be whatever we have for dotsort, just a couple quick tests, and docs can just be an additional row in the atoms table.

2024-09-06 17:51 UTC, Transurgeon commented
Hello @davidppineiro thank you for your contribution. 
Just reiterating on Parth's suggestion and giving you more pointers.
- code style instructions can be found [here](https://github.com/cvxpy/cvxpy/blob/master/CONTRIBUTING.md#code-style).
- tests should be added in ``test_atoms.py`` below the ``TestDotSort`` class. You could try solving the wikipedia definition of cvar and do an assertion that the cvar atom gives a similar answer (up to some very small precision). 
- docs will mostly involve a better description in the docstrings of the function. Put some math, and explain the type of the inputs (x must be an vector expression, alpha must be a float between 0 and 1, representing a percentage), etc. Then to add it to the website, you would need to add one line below ``cp.cummax`` [here](https://github.com/cvxpy/cvxpy/blob/master/doc/source/api_reference/cvxpy.atoms.other_atoms.rst#cummax) so that sphinx can generate the docs for the new cvar atom.

2024-09-08 23:06 UTC, PTNobel commented
> docs will mostly involve a better description in the docstrings of the function. Put some math, and explain the type of the inputs (x must be an vector expression, alpha must be a float between 0 and 1, representing a percentage), etc. Then to add it to the website, you would need to add one line below cp.cummax [here](https://github.com/cvxpy/cvxpy/blob/master/doc/source/api_reference/cvxpy.atoms.other_atoms.rst#cummax) so that sphinx can generate the docs for the new cvar atom.

It also needs to be added to the Atoms table! David, you can find me on Tuesday and I can show you where that goes.

2024-09-17 18:44 UTC, SteveDiamond approved these changes
Nice!

2024-09-19 02:05 UTC, PTNobel commented on doc/source/tutorial/functions/index.rst
> +      - average of the :math:`(1-\beta)` fraction of worst outcomes in :math:`x`
@Transurgeon Is this too long for the new format?

2024-09-19 02:22 UTC, Transurgeon commented on doc/source/tutorial/functions/index.rst
> +      - average of the :math:`(1-\beta)` fraction of worst outcomes in :math:`x`
yea most certainly will, good catch.
I think we might need to separate it into two lines.
Let met try to generate the docs and see how it looks.

2024-09-19 02:59 UTC, Transurgeon commented on doc/source/tutorial/functions/index.rst
> +      - average of the :math:`(1-\beta)` fraction of worst outcomes in :math:`x`
ok, there was actually a formatting error and the table wasn't showing at all.. good that we checked before merging.
@PTNobel or @davidppineiro , can you change the atoms table change from line 84-92 to the following (make sure the star and dashes are aligned with everything else)?:
```py
   * - :ref:`cvar(x, beta) <cvar>`
     - average of the :math:`(1-\beta)`
      
       fraction of worst
       
       outcomes in :math:`x`
     - :math:`x \in \mathbf{R}^m`
      
       :math:`\beta \in (0,1)`
     - depends on :math:`x`
     - |convex| convex
     - |incr| incr.
```

2024-09-21 16:24 UTC, davidppineiro commented on doc/source/tutorial/functions/index.rst
> +      - average of the :math:`(1-\beta)` fraction of worst outcomes in :math:`x`
Done! Does it show up now?

2024-09-21 16:44 UTC, PTNobel requested changes

2024-09-21 16:44 UTC, PTNobel commented on doc/source/tutorial/functions/index.rst
> +       fraction of worst
Last change, what does worst mean? Can we either say smallest or largest?

2024-09-21 18:01 UTC, Transurgeon approved these changes
LGTM on condition of addressing Parth's suggestion.
Thanks for doing this @davidppineiro !

2024-09-27 18:00 UTC, davidppineiro commented on doc/source/tutorial/functions/index.rst
> +       fraction of worst
If we go with largest/smallest, we have to specify if the vector x represents losses or profits. 
Which version do you prefer?
1. average of the :math:`(1-\beta)` fraction of worst values in :math:`x`
2. average of the :math:`(1-\beta)` fraction of largest losses in :math:`x`
Let me know if you have a better alternative.

2024-09-27 21:34 UTC, SteveDiamond commented on doc/source/tutorial/functions/index.rst
> +       fraction of worst
+1 for option 3

2024-09-27 21:41 UTC, SteveDiamond commented on doc/source/tutorial/functions/index.rst
> +       is a vector of losses
do we need to say what `x` is, given we are saying cvar is averaging the largest values?

2024-09-27 21:42 UTC, SteveDiamond commented on doc/source/tutorial/functions/index.rst
> +       is a vector of losses
in other words I don't think we need the part about `where x is a vector of losses`

2024-09-27 21:45 UTC, davidppineiro commented on doc/source/tutorial/functions/index.rst
> +       is a vector of losses
Yeah, I think you are right. It's redundant. Will take it out.

2024-09-27 22:09 UTC, PTNobel commented on doc/source/tutorial/functions/index.rst
> +       fraction of worst
Definitely 3

2024-09-27 22:33 UTC, davidppineiro commented
@PTNobel @SteveDiamond I have made some changes to the docstring in the CVaR atom and the table, and included some checks. Let me know if you have more suggestions.

2024-09-27 22:52 UTC, SteveDiamond commented on cvxpy/atoms/cvar.py
> +    if len(x.shape) > 1 and x.shape[1] != 1:
I don't think this is the condition we want. It should be `len(x.shape) == 1`.

2024-09-27 22:55 UTC, davidppineiro commented on cvxpy/atoms/cvar.py
> +    if len(x.shape) > 1 and x.shape[1] != 1:
But that will fail for x = cp.Variable((n,1)). Is this what we want?

2024-09-27 23:03 UTC, SteveDiamond commented on cvxpy/atoms/cvar.py
> +    if len(x.shape) > 1 and x.shape[1] != 1:
Yes, that should fail. It's not consistent with numpy style to allow `x = cp.Variable((n,1))` but not allow `x = cp.Variable((1,n))`. If we allow 2D inputs we need to start thinking about having an axis argument, which would be much more complicated (though maybe doable?)

2024-09-27 23:15 UTC, davidppineiro commented on cvxpy/atoms/cvar.py
> +    if len(x.shape) > 1 and x.shape[1] != 1:
Makes sense. Just changed the assert to raise an error if it's not a 1D array.

2024-09-27 23:16 UTC, davidppineiro commented
@SteveDiamond @PTNobel Also added another test for the CVaR atom: solving a small LP with a CVaR constraint.

2024-09-27 23:23 UTC, SteveDiamond approved these changes
Nice job!

2024-09-27 23:31 UTC, PTNobel approved these changes

2024-09-27 23:31 UTC, merged