HiGHS solver interface for CVXPY
cvxpy/cvxpy pull request #2580
Opened 2024-09-30 19:08 UTC by UweGensheimer

## Description
Please include a short summary of the change.
Issue link (if applicable): [issue](https://github.com/cvxpy/cvxpy/issues/2568)

This PR links CVXPY directly to the highspy interface (C++ bindings), replacing the prior integration through SciPy with HiGHS v1.2.0. To facilitate this, the highs_qpif.py file has been introduced, establishing HiGHS as a Quadratic Programming (QP) solver. As a result, quadratic objectives can now be handled more efficiently.

Special thanks to [Gabriel Hackebeil](https://github.com/ghackebeil) for their valuable input and collaboration, which greatly contributed to the success of this enhancement.
## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [x] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [x ] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [x] Write unittests.
- [x] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

2024-09-30 19:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=2580) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=2580) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cvxpy/cvxpy?pullRequest=2580) it.</sub>

2024-10-01 04:49 UTC, PTNobel requested changes
Looks like a great initial interface! We'll need some to update the docs too; especially if you support warm start. 

I know our warm start support isn't simple, and we've disabled it in solvers before; I'll have to do some review.

2024-10-01 04:49 UTC, PTNobel commented on cvxpy/reductions/solvers/defines.py
> +              s.HIGHS]
I think I'd prefer HIGHS to be higher in priority, but I'll have to chat with the maintainers for their preferences.

2024-10-01 04:49 UTC, PTNobel commented on cvxpy/reductions/solvers/defines.py
> +              s.XPRESS, s.CBC, s.SCIP, s.COPT, s.ECOS_BB, s.HIGHS]
HIGHS should definitely be before ECOS_BB... I'm less sure about the others

2024-10-01 04:49 UTC, PTNobel commented on cvxpy/reductions/solvers/qp_solvers/highs_qpif.py
> +    """QP interface for the OSQP solver"""
```suggestion
    """QP interface for the HIGHS solver"""
```

2024-10-01 04:49 UTC, PTNobel commented on cvxpy/reductions/solvers/qp_solvers/highs_qpif.py
> +            dual_vars = None
@SteveDiamond how do we handle dual vars for MIPs?

2024-10-01 04:49 UTC, PTNobel commented on cvxpy/reductions/solvers/qp_solvers/highs_qpif.py
> +                raise SolverError(
I'm not sure how we normally handle this ... I'll have to look for precedent

2024-10-01 12:05 UTC, rileyjmurray reviewed
I'm writing this review on my cell phone so it isn't thorough. Looks like I also left a comment about solver priority in the wrong place? You get the idea though.

2024-10-01 12:05 UTC, rileyjmurray commented on cvxpy/settings.py
> +           NAG, PDLP, SCIP, SCIPY, DAQP, HIGHS]
I agree that HIGHS shouldn't be at the end. But I think a bigger discussion about this is in order. How about we keep it here for now and open a new issue about solver priority?

2024-10-01 12:05 UTC, rileyjmurray commented on cvxpy/reductions/solvers/qp_solvers/highs_qpif.py
> +                )
@PTNobel, you can look at how MOSEK handles requests for mixed-integer SDP for precedent.

2024-10-01 14:48 UTC, SteveDiamond commented on cvxpy/reductions/solvers/qp_solvers/highs_qpif.py
> +            dual_vars = None
MIPs don't return dual variables

2024-10-01 16:33 UTC, Transurgeon commented
Thanks for this @UweGensheimer !
Could you add tests in ``test_conic_solvers.py`` as well. We currently test LP/MILP for gurobi there even though it gets routed through gurobi's QP interface, see [here](https://github.com/cvxpy/cvxpy/blob/master/cvxpy/tests/test_conic_solvers.py#L1418-L1420). 
You can probably just copy paste the tests I added in #2573 ([link](https://github.com/cvxpy/cvxpy/pull/2573/files#diff-896acfa00647f17dac200b1cbe34230a583fd253a22286bff4481f600c6140c8R2243-R2285) to the changes).

2024-10-01 19:11 UTC, SteveDiamond commented on cvxpy/reductions/solvers/qp_solvers/highs_qpif.py
> +                raise SolverError(
Information about what problems a solver supports needs to be exposed at a higher level than this. Unfortunately there is new logic needed to enable QP solvers that can solve MILP but not MIQP. This is the first interface of that kind. We have a lot of granular logic for cone solvers but not for QP solvers. One of the cvxpy devs will need to help add this code.

2024-10-01 20:18 UTC, ghackebeil commented on cvxpy/reductions/solvers/qp_solvers/highs_qpif.py
> +                raise SolverError(
I’d even be in favor of leaving this explicit check out. Highs will error with the same message, and maybe they’ll add support one day. No changes would be needed here at that  point.

2024-10-01 20:42 UTC, PTNobel commented on cvxpy/reductions/solvers/qp_solvers/highs_qpif.py
> +                )
https://github.com/cvxpy/cvxpy/blob/b4fc85bac58f350d1604ef5e596a3a798d223d41/cvxpy/reductions/solvers/conic_solvers/mosek_conif.py#L117

Here is what we're doing there... I need to check where that list is being used.

2024-10-01 20:54 UTC, SteveDiamond commented on cvxpy/reductions/solvers/qp_solvers/highs_qpif.py
> +                )
We don't have this for QPs though

2024-10-01 21:24 UTC, PTNobel commented on cvxpy/reductions/solvers/qp_solvers/highs_qpif.py
> +                )
We could make this a conif with quadratic objective?

2024-10-01 23:14 UTC, SteveDiamond commented on cvxpy/reductions/solvers/qp_solvers/highs_qpif.py
> +                )
Good idea!

2024-10-01 23:42 UTC, PTNobel commented on cvxpy/reductions/solvers/qp_solvers/highs_qpif.py
> +                )
Steven and I discussed further: it's probably for the best to just have two interfaces. One for QPs and one for MIP

2024-10-02 02:17 UTC, UweGensheimer commented on cvxpy/reductions/solvers/qp_solvers/highs_qpif.py
> +                )
Just to confirm, the final conclusion is to have 2 HiGHS interfaces (as QpSolver and ConicSolver)?

2024-10-02 06:02 UTC, PTNobel commented on cvxpy/reductions/solvers/qp_solvers/highs_qpif.py
> +                )
Yep. Only the second would support MIP.

2024-10-13 21:45 UTC, UweGensheimer commented on cvxpy/reductions/solvers/qp_solvers/highs_qpif.py
> +                )
I went ahead and added the HiGHS conic interface.

2024-10-13 21:46 UTC, UweGensheimer commented
HiGHS conic interface is added to support MIPs. Also, more unittests are added as @Transurgeon pointed out above.

2024-10-15 15:58 UTC, Transurgeon reviewed
I am not too familiar with interfaces, but if the tests are passing it should be good. 
I think we should document somewhere that the conic interface is only for the MILP support of HIGHS.

Also, @UweGensheimer in terms of documenting the solver, could you replicate the changes in #2573 to the install instructions, pyproject.toml and solver table?

2024-10-15 15:58 UTC, Transurgeon commented on cvxpy/reductions/solvers/qp_solvers/highs_qpif.py
> +#  - solver cache + warm start
this could probably be removed

2024-10-15 15:58 UTC, Transurgeon commented on cvxpy/reductions/solvers/conic_solvers/highs_conif.py
> +            subject to    L <= A x <= U
should change this to conic form

2024-10-15 15:58 UTC, Transurgeon commented on cvxpy/reductions/solvers/conic_solvers/highs_conif.py
> +    # Map of OSQP status to CVXPY status.
change to HIGHS

2024-10-15 15:58 UTC, Transurgeon commented on cvxpy/reductions/solvers/qp_solvers/highs_qpif.py
> +    # Map of OSQP status to CVXPY status.
ditto

2024-10-16 16:42 UTC, SteveDiamond commented on doc/source/install/index.rst
The scipy interface will still exist though. The existing description looks fine.

2024-10-17 22:02 UTC, SteveDiamond approved these changes
LGTM. @Transurgeon or @PTNobel can one of you review as well?

2024-10-18 00:58 UTC, Transurgeon approved these changes
LGTM. @rileyjmurray should we also update the "interface owners" in this [discussion page](https://github.com/cvxpy/cvxpy/discussions/2203)?

2024-10-18 13:08 UTC, rileyjmurray commented
Yeah, updating the interface owners would be wise.

On Thu, Oct 17, 2024 at 8:59 PM William Zijie Zhang <
***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> LGTM. @rileyjmurray <https://github.com/rileyjmurray> should we also
> update the "interface owners" in this discussion page
> <https://github.com/cvxpy/cvxpy/discussions/2203>?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cvxpy/cvxpy/pull/2580#pullrequestreview-2376690570>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACRLIFERYBHP7BF5PZBXGWDZ4BMNXAVCNFSM6AAAAABPEBBOZWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNZWGY4TANJXGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-18 18:01 UTC, merged