Re-enable sdist publishing + clean up build workflows
cvxpy/cvxpy pull request #2585
Opened 2024-10-08 17:29 UTC by bkurtz

## Description
Reduce duplication in github actions workflow for builds, and re-add "single action" configurations that produce coverage uploads and Source Distribution (sdist) files.

Fixes #2584.

## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [x] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [x] Add our license to new files.
- [ ] Check that your code adheres to our coding style.
- [ ] Write unittests.
- [ ] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

2024-10-08 17:34 UTC, bkurtz commented on .github/workflows/build.yml
> +        base: [ true, false ]
Combined the below `build_cvxpy-base` job into this one using an extra matrix parameter to keep things DRY.  That mostly meant using the `build_wheels` job definition, with the addition of a couple steps, but git seems to detect the change as mostly re-using the `build_cvxpy-base` job definition with a bunch of minor changes.

(if it makes life easier when reviewing, that refactor is mostly contained in the first commit of the PR).

2024-10-08 17:34 UTC, bkurtz commented on .github/workflows/build.yml
> +        exclude:
Since, (AFAICT) the "single action" configurations _also_ build all the normal steps, I went ahead and set this up to _delete_ one normal matrix item and add back a new one with "single action config" so we don't end up with duplication.

2024-10-08 17:34 UTC, bkurtz commented on .github/workflows/build.yml
> +            base: true
As I think through this with the fresh light of a new day, I think we might actually want to do this for both base=true and base=false, so that we end up with sdists for both packages?

2024-10-08 17:45 UTC, Transurgeon commented on .github/workflows/build.yml
> +          name: wheels-${CVXPY_BASE_SUFFIX}${{ matrix.os }}-${{ matrix.python-version }}
does this suffix exist?

2024-10-08 17:45 UTC, Transurgeon commented on .github/workflows/build.yml
> +      PYPI_PASSWORD: ${{ matrix.base && secrets.PYPI_BASE_PASSWORD || secrets.PYPI_PASSWORD }}
if my understanding is correct, we want to check if matrix.base is True and if so, we set PYPI_PASSWORD to be ``secrets.PYPI_BASE_PASSWORD``, is this code implementing this functionality?

2024-10-08 17:45 UTC, Transurgeon commented on .github/workflows/build.yml
> +        if: ${{matrix.base && env.PIP_INSTALL == 'True'}}
why are we checking if matrix.base is True here?

2024-10-08 17:45 UTC, Transurgeon commented on .github/workflows/build.yml
> +      PIP_INSTALL: "${{ matrix.python-version == '3.12' }}"
what does this do? Is it only being triggered when using python3.12?

2024-10-08 17:50 UTC, Transurgeon commented on .github/workflows/build.yml
> +        exclude:
yea that part makes sense. But I don't particularly like the delete then adding it back with single action config. Maybe you can revert to using the previous setup [here](https://github.com/cvxpy/cvxpy/commit/69e3e6c95b3908a6d3e897d7ba665379c20191af#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L33-L43) but change everything to python3.12 instead of 3.8 (and also remove 3.12 from the matrix.python-version). What do you think?

2024-10-08 17:50 UTC, Transurgeon commented on .github/workflows/build.yml
> +            base: true
yeah that's probably a good idea, maybe if you just remove the ``base: true`` line it would work for both cases?

2024-10-08 21:50 UTC, bkurtz commented on .github/workflows/build.yml
> +        exclude:
I guess I'd feel like that mostly depends on whether you want _other_ one-off configs added (e.g. previously there was also an "openmp" version of some sort.  If it's just for one config, it sortof seems silly to have to add _four_ manual entries rather than two to me, but... it's not my repo.

2024-10-08 21:50 UTC, bkurtz commented on .github/workflows/build.yml
> +        exclude:
Actually, I think on a more careful read of the [docs](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrixinclude) we should be able to just add the "include" clause and it will add keys to one of the existing matrix entries, and use similar shortcuts below.

2024-10-08 21:50 UTC, bkurtz commented on .github/workflows/build.yml
> +            base: true
Read through the docs in more detail, and I think you're right.

2024-10-08 21:50 UTC, bkurtz commented on .github/workflows/build.yml
> +        if: ${{matrix.base && env.PIP_INSTALL == 'True'}}
Previously this was only done in the `cvxpy-base` job of the workflow.  I don't have a strong opinion about when it should be done, but was trying to preserve previous behavior.

2024-10-08 21:50 UTC, bkurtz commented on .github/workflows/build.yml
> +      PYPI_PASSWORD: ${{ matrix.base && secrets.PYPI_BASE_PASSWORD || secrets.PYPI_PASSWORD }}
I don't actually know what y'all have set up with the secrets, but _I assume_ based on the way the job was already coded that there are separate passwords for the `cvxpy` and `cvxpy-base` packages being submitted to pypi.  This is supposed to condition which one of those ends up in the `PYPI_PASSWORD` environment variable.

Several other places in this file that check for true/false values seem to assume that the matrix outputs are strings.  I was hoping maybe they can be just directly used as booleans, but I'd want to test that!

2024-10-08 21:50 UTC, bkurtz commented on .github/workflows/build.yml
> +      PIP_INSTALL: "${{ matrix.python-version == '3.12' }}"
On the "cvxpy-base" configuration, this was being used to test that packages successfully `pip install` after building.  This sortof seems like overkill to me, but it was supported before, so thought I'd add it back.  The previous setup only did this for one version of python (I assume on the grounds that if it works on one, it works on all?), so I thought I'd do the same here, and it seemed easier to just key it directly on a value than to add matrix entries.  Though now I've learned about the better syntax for adding matrix keys, that presumably wouldn't be too bad either.

2024-10-08 21:50 UTC, bkurtz commented on .github/workflows/build.yml
> +          name: wheels-${CVXPY_BASE_SUFFIX}${{ matrix.os }}-${{ matrix.python-version }}
The environment variable would (AFAICT) be undefined in that case, resulting in the shell expanding it as an empty string.

2024-10-08 21:50 UTC, bkurtz commented on .github/workflows/build.yml
> +        include:
this matrix previously included some extra configs that checked openmp compatibility.  I haven't added them back, but maybe we should?

2024-10-08 22:07 UTC, Transurgeon commented on .github/workflows/build.yml
> +        exclude:
ok I think you are right, I am fine with keeping it as is.

2024-10-08 22:08 UTC, Transurgeon commented on .github/workflows/build.yml
> +        if: ${{matrix.base && env.PIP_INSTALL == 'True'}}
ok this seems fine to me.

2024-10-08 22:09 UTC, Transurgeon commented on .github/workflows/build.yml
> +      PIP_INSTALL: "${{ matrix.python-version == '3.12' }}"
ok, thanks for the explanation. I think we should definitely keep the old behavior the same, so let's keep it this way.

2024-10-08 22:11 UTC, Transurgeon commented on .github/workflows/build.yml
> +      PYPI_PASSWORD: ${{ matrix.base && secrets.PYPI_BASE_PASSWORD || secrets.PYPI_PASSWORD }}
I understand what you mean here, but the current code has a condition on ``matrix.base && secrets.PYPI_BASE`` which doesn't seem to set the ``PYPI_PASSWORD`` to the correct value (doesn't it return a boolean instead now?)

2024-10-08 22:12 UTC, Transurgeon commented on .github/workflows/build.yml
> +          name: wheels-${CVXPY_BASE_SUFFIX}${{ matrix.os }}-${{ matrix.python-version }}
ok seems fine to me, as long as it doesn't create an error.

2024-10-09 00:40 UTC, Transurgeon commented on .github/workflows/build.yml
> +        include:
yea I think that's a good idea.

2024-10-09 00:43 UTC, Transurgeon commented
@bkurtz the CI is failing due to an error with pytest when ``single_action_config == True``. It seems to be something related to the ``cov`` flag (code is [here](https://github.com/cvxpy/cvxpy/blob/master/continuous_integration/test_script.sh#L22-L26). I don't think this test was failing before.. and it seems quite weird that is is failing now, any idea why this is happening?

2024-10-09 14:02 UTC, Transurgeon commented
> @bkurtz the CI is failing due to an error with pytest when `single_action_config == True`. It seems to be something related to the `cov` flag (code is [here](https://github.com/cvxpy/cvxpy/blob/master/continuous_integration/test_script.sh#L22-L26) ). I don't think this test was failing before.. and it seems quite weird that it is failing now, any idea why this is happening?

NVM, I just made a PR with only the single action config changes in #2587 and it seems to be failing with the same error. I'll look into it.

2024-10-10 11:09 UTC, bkurtz commented
> @bkurtz the CI is failing due to an error with pytest when `single_action_config == True`. It seems to be something related to the `cov` flag (code is [here](https://github.com/cvxpy/cvxpy/blob/master/continuous_integration/test_script.sh#L22-L26) ). I don't think this test was failing before.. and it seems quite weird that it is failing now, any idea why this is happening?

That'll be the different dependencies that we used to install for 3.8 here:
https://github.com/cvxpy/cvxpy/blob/3ccafc2d9ae15a0967011a019986aa03de7c3384/continuous_integration/install_dependencies.sh#L14

(in particular, `pytest-cov` is relevant)

2024-10-10 11:15 UTC, bkurtz commented on .github/workflows/build.yml
> +      PYPI_PASSWORD: ${{ matrix.base && secrets.PYPI_BASE_PASSWORD || secrets.PYPI_PASSWORD }}
I think (as is true with short-circuit logical operators in python) the JS evaluation of these template fields doesn't coerce to boolean values.

See, for example, the existing code here:
https://github.com/cvxpy/cvxpy/blob/273e0cfa65a90440b0e5cf05164a76a501edf6c0/.github/workflows/build.yml#L41

Or compare to python:
```python
>>> False and "hi" or "bye"
'bye'
>>> True and "hi" or "bye"
'hi'
```

2024-10-10 14:32 UTC, Transurgeon commented on .github/workflows/build.yml
> +      PYPI_PASSWORD: ${{ matrix.base && secrets.PYPI_BASE_PASSWORD || secrets.PYPI_PASSWORD }}
ohhh I see, it's some javascript trick.. looks good then

2024-10-10 14:35 UTC, Transurgeon commented
> > @bkurtz the CI is failing due to an error with pytest when `single_action_config == True`. It seems to be something related to the `cov` flag (code is [here](https://github.com/cvxpy/cvxpy/blob/master/continuous_integration/test_script.sh#L22-L26) ). I don't think this test was failing before.. and it seems quite weird that it is failing now, any idea why this is happening?
> 
> That'll be the different dependencies that we used to install for 3.8 here:
> 
> https://github.com/cvxpy/cvxpy/blob/3ccafc2d9ae15a0967011a019986aa03de7c3384/continuous_integration/install_dependencies.sh#L14
> 
> (in particular, `pytest-cov` is relevant)

Yeah really nice catch! I was not careful when removing support for python 3.8.
can you add pytest-cov to the install dependencies on this [line](https://github.com/cvxpy/cvxpy/blob/297278e2a88db3c0084750052a16e60672074da3/continuous_integration/install_dependencies.sh#L12)?
If the CI passes, I think the PR makes sense and looks good to me :)

2024-10-10 14:38 UTC, Transurgeon commented on .github/workflows/build.yml
> +        base: [ true, false ]
could you add a comment next to base stating that it's for building cvxpy and cvxpy_base simultaneously? Would be helpful for future reference.

2024-10-13 00:09 UTC, bkurtz commented on .github/workflows/build.yml
> +      PYPI_PASSWORD: ${{ matrix.base && secrets.PYPI_BASE_PASSWORD || secrets.PYPI_PASSWORD }}
One thing I realized from this conversation that I do still want to verify is whether matrix values can actually be native booleans, or if I might need this to be
```suggestion
      PYPI_PASSWORD: ${{ matrix.base == 'true' && secrets.PYPI_BASE_PASSWORD || secrets.PYPI_PASSWORD }}
```
I'm going to push a commit that tests this on the regular "build" section of the workflow so that it's something we can test before merging the PR.
(Actually, we should talk more about what we _can_ do to test this more thoroughly before merging?)

2024-10-13 14:16 UTC, bkurtz commented on .github/workflows/pr_benchmark_comment.yml
> +    uses: cvxpy/actions/.github/workflows/benchmark_comment.yml@main
This is totally unrelated, but I've been getting warnings about this after most pushes on this PR, and it seemed like an easy thing to fix while I was here, assuming there aren't other issues in that pipeline that need fixing (if so, I'll probably just revert this change and leave it for another day).

2024-10-13 14:47 UTC, bkurtz commented on .github/workflows/pr_benchmark_comment.yml
> +    uses: cvxpy/actions/.github/workflows/bechmark_comment.yml@main
Aand... there's a typo in the filename in the other repo.  Should obviously be spelled be**n**chmark with an N.

2024-10-13 14:59 UTC, bkurtz commented on .github/workflows/pr_benchmark_comment.yml
> +    uses: cvxpy/actions/.github/workflows/bechmark_comment.yml@main
Looks like these trigger from the main branch anyway, so getting the spelling right in this PR only helps so much.  Given that, and given that it only use AFAICT is in this repo, I'd be inclined to just rename the other end, rather than trying to fix here.  I've reverted these changes.

2024-10-13 15:12 UTC, bkurtz commented
Okay, I think from my point of view this is ready for final comments.  The "pr_benchmarks" job has a spurious failure (it says performance is worse, but it's been passing normally and I obviously didn't change any related code in this PR), so I assume it will pass on a re-run.

I tested that it looks to me like all the env vars are being set (in particular, that removing the restriction that sdists are only built on "push" got one to build), so I think everything is tested and working.

Do you all use "squash" merges or regular merges?  The commit history here is pretty gross and if it's not all going to squash down into one commit, I'd prefer to clean it up a bit before merging, but otherwise from my point of view this is ready to merge.

2024-10-15 00:08 UTC, Transurgeon commented
> Okay, I think from my point of view this is ready for final comments. The "pr_benchmarks" job has a spurious failure (it says performance is worse, but it's been passing normally and I obviously didn't change any related code in this PR), so I assume it will pass on a re-run.

Yeah this PR benchmark failure has happened a lot before, and it's clear that it has nothing to do with your changes.

> Do you all use "squash" merges or regular merges? The commit history here is pretty gross and if it's not all going to squash down into one commit, I'd prefer to clean it up a bit before merging, but otherwise from my point of view this is ready to merge.

yes we do squash our commits. Thanks again for your work!

2024-10-15 00:09 UTC, Transurgeon approved these changes
This PR looks good to me. @SteveDiamond @PTNobel could you do a quick sanity check and merge please?

2024-10-15 00:24 UTC, Transurgeon commented
> This PR looks good to me. @SteveDiamond @PTNobel could you do a quick sanity check and merge please?

Actually I had one last concern, while taking a second look at this. It seems like a few of the steps are being skipped due to the OPENMP environment variable?
![image](https://github.com/user-attachments/assets/f478a6e5-df7e-4f7a-8973-0a3cac7cbe4e)

2024-10-15 01:03 UTC, Transurgeon requested changes
Ideally the actions steps shouldn't be skipped (Build wheels/source, check wheels, etc.), although now that I check our previous CI behavior, it seems like it was already like this. Could you please address my final comments and I think we would be good to merge after that?

2024-10-15 01:03 UTC, Transurgeon commented on .github/workflows/build.yml
>        USE_OPENMP: "${{ matrix.openmp == 'True' && 'True' || 'False' }}"
maybe we would need to remove the ``== 'True'`` similar to the change you did on line 47?

2024-10-15 03:19 UTC, bkurtz reviewed
> Ideally the actions steps shouldn't be skipped (Build wheels/source, check wheels, etc.), although now that I check our previous CI behavior, it seems like it was already like this. Could you please address my final comments and I think we would be good to merge after that?

These are being skipped because of the `github.event_name == 'push'` condition on those steps.  I did a test (see state prior to bde70a4d0a3e3f5479752f202130c7a674d2586a) with one of those clauses removed to validate that things were working as expected for the other conditions here.

Essentially, this workflow is triggered two ways:
1. on PR updates (what we're doing here)
2. when there's a push event to `master`, a release branch, or any tag

I guess the rationale is that you only want to bother with wheel builds when updating master or a release branch, and TBH we could probably add a condition that skips the "build_wheels" jobs _entirely_ rather than only some steps, but that seemed like a bigger change than I set out to take on here!  It looks like we go even further and only actually push to pypi for "push" events to a tag (which makes sense).

2024-10-15 03:19 UTC, bkurtz commented on .github/workflows/build.yml
> +            single_action_config: "True"
Can be done either way.  They were originally both strings and I changed the other one to test the way I was doing boolean values in the matrix, but didn't bother to change this one.  Let me make them consistent.

2024-10-15 03:19 UTC, bkurtz commented on .github/workflows/build.yml
> +            openmp: "True"
No, this is working as expected.  This is a little confusing because the only uses of the `OPENMP` env var in _this_ file are in the second half (the "build wheels" job) which doesn't ever set the `OPENMP` environment variable.  The first half sets the environment variable (you can check it's value in the github actions output; I'll post a screenshot) and then it's used in the `install_dependencies.sh` and `test_script.sh` files I think.

It _probably_ makes sense to clean up the references to OPENMP in the second half, but they aren't doing any harm right now and I wanted to leave them in case I'm missing somehow that they're being set (and because I felt like before deleting them I should do the leg work to understand when they used to be used and I didn't feel like taking the time this week).

2024-10-15 03:19 UTC, bkurtz commented on .github/workflows/build.yml
>        USE_OPENMP: "${{ matrix.openmp == 'True' && 'True' || 'False' }}"
No, this is working correctly, I'll post a screenshot in the other thread illustrating this.
(On line 47, the value for `single_action_config` is a bool and so can be used in the logical statement directly; here, it's a string, so you have to compare to a string first to convert to a boolean.)

2024-10-15 03:19 UTC, bkurtz commented on .github/workflows/build.yml
> +            openmp: "True"
Here's an example showing ubuntu on python 3.12 with the env variable ending up set to `"True"` and on 3.11 showing it set to `"False"`
![image](https://github.com/user-attachments/assets/599d67b7-1780-4b6d-b556-640a8c07d793)
![image](https://github.com/user-attachments/assets/8a295ae3-c2c9-414e-8f5f-20c0727dfb06)

2024-10-15 03:22 UTC, bkurtz commented
> These are being skipped because of the `github.event_name == 'push'` condition on those steps. I did a test (see state prior to [bde70a4](https://github.com/cvxpy/cvxpy/commit/bde70a4d0a3e3f5479752f202130c7a674d2586a)) with one of those clauses removed to validate that things were working as expected for the other conditions here.

Specifically, commit 5ccdc70291f9b26fa55094f6b4960fc285804ae1 is the one with valid tests for this, e.g. see https://github.com/cvxpy/cvxpy/actions/runs/11313988982/job/31463507745 which completed the "build source" step successfully.

2024-10-15 15:17 UTC, Transurgeon approved these changes
ok I think this LGTM now, thanks for the detailed PR @bkurtz , I have learned a lot about our CI system through this. @SteveDiamond could you have a quick look then merge please?

2024-10-15 19:05 UTC, SteveDiamond approved these changes
Thanks so much @bkurtz ! We are a very small and busy team, so this kind of help goes a long way.

2024-10-15 19:05 UTC, merged