Feature/concatenate
cvxpy/cvxpy pull request #2597
Opened 2024-10-23 19:59 UTC by andresliszt

## Description
Thank you for this amazin project!, I've been using it for a while and I decided to contribute. This PR aims to add `cp.concatenate` support. Note that so far I added it to the atoms and to the numpy/scipy backends. I haven't added it yet to the cpp/rust backends. I'd love to add it there, but before going too far, i'd like to know if this needed/wanted and if my PR is in a good spot. I tried to follow numpy concatenate convention. I added several unit tests and also docstring documentation you can check to follow my ideas. 

**I pushed my changes after runnning ruff format command**, so as you can see there are some format changes that i'd like to avoid --- Do you have a command to do formatting that will sync with master branch?

## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [ ] Add our license to new files.
- [ ] Check that your code adheres to our coding style.
- [ ] Write unittests.
- [ ] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

2024-10-23 19:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=2597) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cvxpy/cvxpy?pullRequest=2597) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cvxpy/cvxpy?pullRequest=2597) it.</sub>

2024-10-23 20:29 UTC, SteveDiamond commented
This is a great feature! We have essentially stopped adding atoms to the CPP backend due to the difficulty of updating it, though it's certainly better to have concatenate in the CPP backend than not have it. Don't worry about the rust backend. @Transurgeon can you take a look at this PR when you have time?

2024-10-23 22:01 UTC, Transurgeon commented
> **I pushed my changes after runnning ruff format command**, so as you can see there are some format changes that i'd like to avoid --- Do you have a command to do formatting that will sync with master branch?

yes, we usually use ``pre-commit``. You can find some instructions [here](https://www.cvxpy.org/contributing/index.html#code-style) on how to get setup. 

P.S. Thanks a lot for doing this, I'll give a proper review once the linting errors are fixed :).

2024-10-23 22:47 UTC, andresliszt commented
> > **I pushed my changes after runnning ruff format command**, so as you can see there are some format changes that i'd like to avoid --- Do you have a command to do formatting that will sync with master branch?
> 
> yes, we usually use `pre-commit`. You can find some instructions [here](https://www.cvxpy.org/contributing/index.html#code-style) on how to get setup.
> 
> P.S. Thanks a lot for doing this, I'll give a proper review once the linting errors are fixed :).

Thanks, I ran the commands and also removed some redundancy. I think it's ready to be reviewed

2024-10-23 22:50 UTC, andresliszt commented on cvxpy/atoms/affine/concatenate.py
> +        super().__init__(*args)
I'm not sure if this is the best way to define `__init__` , but in many places the instances are created using `type(self)(*(args + data)) `, so it doesn't let me to define `axis` as positional. An alternative could be define something like `def __init__(self, expr_l, expr_r, axis)` and we iteratively handle `arg_list` in the main concatenate method

2024-10-23 22:53 UTC, SteveDiamond commented on cvxpy/atoms/affine/concatenate.py
> +        super().__init__(*args)
Yes, this is not correct. There should be an explicit axis atom. This must be communicated to the internals via the get_data function, which you already have.

2024-10-23 22:57 UTC, andresliszt commented on cvxpy/atoms/affine/concatenate.py
> +        super().__init__(*args)
there is an axis atom class `AxisAtom(Atom)`, but it was thought (afik) for single expressions, for example, tensor sum on a specific axis

2024-10-23 23:45 UTC, SteveDiamond commented on cvxpy/atoms/affine/concatenate.py
> +        super().__init__(*args)
sorry, typo. I meant axis argument.

2024-10-23 23:46 UTC, SteveDiamond commented on cvxpy/atoms/affine/concatenate.py
> +        super().__init__(*args)
I do sort of see though what you mean. Let us get back to you on the right approach.

2024-10-24 20:04 UTC, Transurgeon requested changes
Thanks for doing @andresliszt , great work overall!
Apart from the review comments, I had two things to mention:
1. I have some ideas for more tests we could do (potentially generating some using hypothesis).
2. I'll need to spend more time looking at what you wrote for the docstrings of the ``python_backend`` test.
I'll probably do another round of review to address these two issues.

2024-10-24 23:29 UTC, andresliszt commented
> Thanks for doing @andresliszt , great work overall!
> 
> Apart from the review comments, I had two things to mention:
> 
> 1. I have some ideas for more tests we could do (potentially generating some using hypothesis).
> 
> 2. I'll need to spend more time looking at what you wrote for the docstrings of the ``python_backend`` test.
> 
> I'll probably do another round of review to address these two issues.

Thanks for the review, yes will be addresing your comments soon!

2024-10-25 18:48 UTC, andresliszt commented on cvxpy/atoms/affine/concatenate.py
> +        super().__init__(*args)
I think that probably axis as **keyword only** might not work. The problem with this is that we define an arbitrary number of expression at init `def __init__(self, *args, axis=0)`  is that axis becomes a keyword only argument and this doesn't work with this cvxpy [code](https://github.com/andresliszt/cvxpy/blob/297278e2a88db3c0084750052a16e60672074da3/cvxpy/reductions/eval_params.py#L70):

```python
def apply(self, problem):
      """Replace parameters with constant values."""

         # code omitted for simplicity ...

        data = c.get_data()
        if data is not None:
            constraints.append(type(c)(*(args + data))) # This has problems with arbitrary args mixed with keywords
        else:
            constraints.append(type(c)(*args))
      return problems.problem.Problem(objective, constraints), []
```
The evaluation of `type(c)(*(args + data))` will never pass the keyword only values to the constructor, so axis will be passed as positional.

Possible solutions:

1.  Define a `get_data_kw` which allows to define extra data as keyword only as well. This is more complicated because there are several references to `get_data` in the source code.
2. Define `Concatenate.__init__` to work with 2 expressions  `Concatenate.__init__(expr_l, expr_r, axis = 0)`. In this case `axis` works as positional or keyword argument and `type(c)(*(args + data))` will correct setup the values for the expressions and axis. In this case the main function `concatenate`, which I understand is the only function that the user uses, will still having an `arg_list` as argument but we have to `iteratively`  concatenate pairs of expressions. For example in the case of arg_list = `[expr1, expr2, expr3]` we should return `Concatenate(expr3, Concatenate(expr1, expr2, axis = axis), axis = axis)
 `

2024-10-25 19:16 UTC, SteveDiamond commented on cvxpy/atoms/affine/concatenate.py
> +        super().__init__(*args)
I think the way you did it originally is fine for now. We can revisit the topic in a separate PR.

2024-10-29 21:26 UTC, andresliszt commented
Iteresting, some tests are failing due to `XPRESS`, i did not notice it locally because the test is skipped, now I could reproduce it installing `XPRESS`, I will be poking arround!

2024-10-29 21:30 UTC, SteveDiamond commented
Don't worry about Xpress. That was fixed recently in a different MR. We discussed internally and there is interest in including this MR in the upcoming 1.6 release. Do you need help to implement the C++ version of concatenate? It only needs to work for up to 2D inputs. Whenever you have a value with >2 dimensions then cvxpy will ensure the SciPy backend is used.

2024-10-29 21:31 UTC, andresliszt commented
> Don't worry about Xpress. That was fixed recently in a different MR. We discussed internally and there is interest in including this MR in the upcoming 1.6 release. Do you need help to implement the C++ version of concatenate? It only needs to work for up to 2D inputs. Whenever you have a value with >2 dimensions then cvxpy will ensure the SciPy backend is used.

Cool! Yes i can do it, i was waiting for your confirmation, ty

2024-10-30 04:21 UTC, Transurgeon commented
> Cool! Yes i can do it, i was waiting for your confirmation, ty

Thanks a lot @andresliszt , just wanted to say everything else you did looks good as well. We might make another PR for more tests at a future point. If you want to make the CI pass, you can update this branch (my personal preference is to use ``git merge master`` from the branch after syncing your fork with cvxpy master). But it is not necessary. 

P.S. can you check if vstack and hstack work with 3d arrays also? I remember last time I was testing, one of them was failing.

2024-10-30 15:46 UTC, Transurgeon commented on cvxpy/atoms/affine/concatenate.py
> +                    )
I just asked someone from the NumPy community (through the scientific python discord) about this and he recommended us to use [np.lib.side_tricks.as_strided](https://numpy.org/devdocs/reference/generated/numpy.lib.stride_tricks.as_strided.html) to mimic arrays of arbitrary dimensions. Let me get back to you on the best way we should go about this.

2024-10-31 17:08 UTC, Transurgeon commented on cvxpy/atoms/affine/concatenate.py
> +                    )
ok so actually we can use ``np.empty(shape, dtype=np.dtype([]))`` to create truly empty arrays.
Then we can call np.concatenate on them to validate the inputs :). 
But if this changes a lot of the tests, we can always do this in a separate PR.

2024-10-31 20:16 UTC, andresliszt commented
I might be wrong but, is there a way to get the `data` from `linOp`, in this case, `data = [axis]` in the C++ side? . I was looking at the code, and this [line](https://github.com/cvxpy/cvxpy/blob/fc66f1449835580cc6f0d47dea2051b6428520f0/cvxpy/cvxcore/python/cppbackend.py#L179) took my attention. The `sum_entries` defines a data in the same way i'm defining data for my `concatenate` operator. You can see it in [here](https://github.com/cvxpy/cvxpy/blob/fc66f1449835580cc6f0d47dea2051b6428520f0/cvxpy/lin_ops/lin_utils.py#L386). I was looking the C++ side of that operator and I don't see references to `axis` or `keepdims`.

2024-10-31 20:24 UTC, andresliszt commented on cvxpy/atoms/affine/concatenate.py
> +                    )
cool!

2024-10-31 21:36 UTC, SteveDiamond commented
> I might be wrong but, is there a way to get the `data` from `linOp`, in this case, `data = [axis]` in the C++ side? . I was looking at the code, and this [line](https://github.com/cvxpy/cvxpy/blob/fc66f1449835580cc6f0d47dea2051b6428520f0/cvxpy/cvxcore/python/cppbackend.py#L179) took my attention. The `sum_entries` defines a data in the same way i'm defining data for my `concatenate` operator, and according to that line _I think is being ignored_. You can see it in [here](https://github.com/cvxpy/cvxpy/blob/fc66f1449835580cc6f0d47dea2051b6428520f0/cvxpy/lin_ops/lin_utils.py#L386). I was looking the C++ side of that operator and I don't see references to `axis` or `keepdims`.

There is not a clean way to get the data right now. You can see for sum_entries that in certain case the ``axis`` argument produces different graph_implementations 
https://github.com/cvxpy/cvxpy/blob/fc66f1449835580cc6f0d47dea2051b6428520f0/cvxpy/atoms/affine/sum.py#L104
This is because the C++ interface doesn't handle ``axis`` arguments, though the data is passed down so it is possible to extract.

@Transurgeon I think there is a strong case for not adding ``concatenate`` to the C++ backend. After we release 1.6 and people start using the N-dimensional functionality, there will be many requests/MRs for new linear operators. It's not really feasible to keep adding more functionality to the C++ interface.

@andresliszt what do you think?

2024-10-31 22:59 UTC, andresliszt commented
> > I might be wrong but, is there a way to get the `data` from `linOp`, in this case, `data = [axis]` in the C++ side? . I was looking at the code, and this [line](https://github.com/cvxpy/cvxpy/blob/fc66f1449835580cc6f0d47dea2051b6428520f0/cvxpy/cvxcore/python/cppbackend.py#L179) took my attention. The `sum_entries` defines a data in the same way i'm defining data for my `concatenate` operator, and according to that line _I think is being ignored_. You can see it in [here](https://github.com/cvxpy/cvxpy/blob/fc66f1449835580cc6f0d47dea2051b6428520f0/cvxpy/lin_ops/lin_utils.py#L386). I was looking the C++ side of that operator and I don't see references to `axis` or `keepdims`.
> 
> There is not a clean way to get the data right now. You can see for sum_entries that in certain case the `axis` argument produces different graph_implementations
> 
> https://github.com/cvxpy/cvxpy/blob/fc66f1449835580cc6f0d47dea2051b6428520f0/cvxpy/atoms/affine/sum.py#L104
> 
> 
> This is because the C++ interface doesn't handle `axis` arguments, though the data is passed down so it is possible to extract.
> @Transurgeon I think there is a strong case for not adding `concatenate` to the C++ backend. After we release 1.6 and people start using the N-dimensional functionality, there will be many requests/MRs for new linear operators. It's not really feasible to keep adding more functionality to the C++ interface.
> 
> @andresliszt what do you think?

So if this is not added to C++, the `get_backend` function in photo should change?  For example, search in all problem's atoms, and if some atom is in a _non cpp supported list_, so far `non_cpp_supported = [concatenate]`, we use scipy or are you thinking in get rid build matrix C++ completely?
<img width="1117" alt="image" src="https://github.com/user-attachments/assets/6bfbf67a-626d-4c54-bf53-4abd435e1da7">

2024-10-31 23:00 UTC, Transurgeon commented
> > I might be wrong but, is there a way to get the `data` from `linOp`, in this case, `data = [axis]` in the C++ side? . I was looking at the code, and this [line](https://github.com/cvxpy/cvxpy/blob/fc66f1449835580cc6f0d47dea2051b6428520f0/cvxpy/cvxcore/python/cppbackend.py#L179) took my attention. The `sum_entries` defines a data in the same way i'm defining data for my `concatenate` operator, and according to that line _I think is being ignored_. You can see it in [here](https://github.com/cvxpy/cvxpy/blob/fc66f1449835580cc6f0d47dea2051b6428520f0/cvxpy/lin_ops/lin_utils.py#L386). I was looking the C++ side of that operator and I don't see references to `axis` or `keepdims`.
> 
> There is not a clean way to get the data right now. You can see for sum_entries that in certain case the `axis` argument produces different graph_implementations
> 
> https://github.com/cvxpy/cvxpy/blob/fc66f1449835580cc6f0d47dea2051b6428520f0/cvxpy/atoms/affine/sum.py#L104
> 
> This is because the C++ interface doesn't handle `axis` arguments, though the data is passed down so it is possible to extract.
> 
> @Transurgeon I think there is a strong case for not adding `concatenate` to the C++ backend. After we release 1.6 and people start using the N-dimensional functionality, there will be many requests/MRs for new linear operators. It's not really feasible to keep adding more functionality to the C++ interface.

Yea I totally agree. I forgot about this major difference between backends. Honestly, I think this PR can be merged for now, but maybe we just don't advertise it in the 1.6 release yet?

@andresliszt as you can see the CPP backend has been a bit of a historical pain to maintain. We are actively trying to get rid of it by improving the performance on the SciPy backend. Please let us know if you would like to help! We can coordinate on [discord](https://discord.gg/4urRQeGBCr) if needed :).
Thanks again for this great PR!

2024-10-31 23:02 UTC, andresliszt commented on cvxpy/atoms/affine/concatenate.py
> +                    )
Hey @Transurgeon  i was thinking in this approach, `np.empty` uses memory, so if the shape is big, it could cause some memory issues. I tested it locally and for big arrays numpy raises a `MemoryAllocationError`. What do you think?

> Unlike other array creation functions (e.g. [zeros](https://numpy.org/devdocs/reference/generated/numpy.zeros.html#numpy.zeros), [ones](https://numpy.org/devdocs/reference/generated/numpy.ones.html#numpy.ones), [full](https://numpy.org/devdocs/reference/generated/numpy.full.html#numpy.full)), [empty](https://numpy.org/devdocs/reference/generated/numpy.empty.html#numpy.empty) does not initialize the values of the array, and may therefore be marginally faster. However, the values stored in the newly allocated array are arbitrary. For reproducible behavior, be sure to set each element of the array before reading.

2024-10-31 23:06 UTC, Transurgeon commented
> So if this is not added to C++, the `_get_cannon_backend` function in photo should change? For example, search in all problem's atoms, and if some atom is in a _non cpp supported list_, so far `non_cpp_supported = [concatenate]`, we use scipy or are you thinking in get rid build matrix C++ completely? 

Your suggestion is great but might be a bit too complicated. I think anyways, users won't be using cp.concatenate with vectors and matrices (you can already do all of that with vstack/hstack I think), so we hope that users will only use concatenate on >3d expressions which already defaults to the scipy backend. So there's probably no need to make any further changes.

2024-10-31 23:23 UTC, andresliszt commented on cvxpy/atoms/affine/concatenate.py
> +                    )
EDIT: Adding dtype as you suggested works fine, no issues. I will add this change to my PR

2024-10-31 23:27 UTC, andresliszt commented
> > > I might be wrong but, is there a way to get the `data` from `linOp`, in this case, `data = [axis]` in the C++ side? . I was looking at the code, and this [line](https://github.com/cvxpy/cvxpy/blob/fc66f1449835580cc6f0d47dea2051b6428520f0/cvxpy/cvxcore/python/cppbackend.py#L179) took my attention. The `sum_entries` defines a data in the same way i'm defining data for my `concatenate` operator, and according to that line _I think is being ignored_. You can see it in [here](https://github.com/cvxpy/cvxpy/blob/fc66f1449835580cc6f0d47dea2051b6428520f0/cvxpy/lin_ops/lin_utils.py#L386). I was looking the C++ side of that operator and I don't see references to `axis` or `keepdims`.
> 
> > 
> 
> > There is not a clean way to get the data right now. You can see for sum_entries that in certain case the `axis` argument produces different graph_implementations
> 
> > 
> 
> > https://github.com/cvxpy/cvxpy/blob/fc66f1449835580cc6f0d47dea2051b6428520f0/cvxpy/atoms/affine/sum.py#L104
> 
> > 
> 
> > This is because the C++ interface doesn't handle `axis` arguments, though the data is passed down so it is possible to extract.
> 
> > 
> 
> > @Transurgeon I think there is a strong case for not adding `concatenate` to the C++ backend. After we release 1.6 and people start using the N-dimensional functionality, there will be many requests/MRs for new linear operators. It's not really feasible to keep adding more functionality to the C++ interface.
> 
> 
> 
> Yea I totally agree. I forgot about this major difference between backends. Honestly, I think this PR can be merged for now, but maybe we just don't advertise it in the 1.6 release yet?
> 
> 
> 
> @andresliszt as you can see the CPP backend has been a bit of a historical pain to maintain. We are actively trying to get rid of it by improving the performance on the SciPy backend. Please let us know if you would like to help! We can coordinate on [discord](https://discord.gg/4urRQeGBCr) if needed :).
> 
> Thanks again for this great PR!

Would love to help! I will need to bring back my math notebooks haha

2024-11-01 00:14 UTC, Transurgeon commented
> > @andresliszt as you can see the CPP backend has been a bit of a historical pain to maintain. We are actively trying to get rid of it by improving the performance on the SciPy backend. Please let us know if you would like to help! We can coordinate on [discord](https://discord.gg/4urRQeGBCr) if needed :).
> > Thanks again for this great PR!
> 
> Would love to help! I will need to bring back my math notebooks haha

It would actually be more software involved, but definitely some math to understand the backend (although you seem to have grasped many things already on your own :) ). Could you send a message on the cvxpy discord general channel? I will add you from there.

2024-11-01 00:54 UTC, rileyjmurray commented
A formal way to not “advertise” is to not have the function appear in the
top level namespace.

On Thu, Oct 31, 2024 at 7:00 PM William Zijie Zhang <
***@***.***> wrote:

> I might be wrong but, is there a way to get the data from linOp, in this
> case, data = [axis] in the C++ side? . I was looking at the code, and
> this line
> <https://github.com/cvxpy/cvxpy/blob/fc66f1449835580cc6f0d47dea2051b6428520f0/cvxpy/cvxcore/python/cppbackend.py#L179>
> took my attention. The sum_entries defines a data in the same way i'm
> defining data for my concatenate operator, and according to that line *I
> think is being ignored*. You can see it in here
> <https://github.com/cvxpy/cvxpy/blob/fc66f1449835580cc6f0d47dea2051b6428520f0/cvxpy/lin_ops/lin_utils.py#L386>.
> I was looking the C++ side of that operator and I don't see references to
> axis or keepdims.
>
> There is not a clean way to get the data right now. You can see for
> sum_entries that in certain case the axis argument produces different
> graph_implementations
>
>
> https://github.com/cvxpy/cvxpy/blob/fc66f1449835580cc6f0d47dea2051b6428520f0/cvxpy/atoms/affine/sum.py#L104
>
> This is because the C++ interface doesn't handle axis arguments, though
> the data is passed down so it is possible to extract.
>
> @Transurgeon <https://github.com/Transurgeon> I think there is a strong
> case for not adding concatenate to the C++ backend. After we release 1.6
> and people start using the N-dimensional functionality, there will be many
> requests/MRs for new linear operators. It's not really feasible to keep
> adding more functionality to the C++ interface.
>
> Yea I totally agree. I forgot about this major difference between
> backends. Honestly, I think this PR can be merged for now, but maybe we
> just don't advertise it in the 1.6 release yet?
>
> @andresliszt <https://github.com/andresliszt> as you can see the CPP
> backend has been a bit of a historical pain to maintain. We are actively
> trying to get rid of it by improving the performance on the SciPy backend.
> Please let us know if you would like to help! We can coordinate on discord
> <https://discord.gg/4urRQeGBCr> if needed :).
> Thanks again for this great PR!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cvxpy/cvxpy/pull/2597#issuecomment-2450990835>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACRLIFDQ3KBW24LFMZF7HVTZ6KZCFAVCNFSM6AAAAABQPSKAQKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINJQHE4TAOBTGU>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-11-01 15:46 UTC, andresliszt commented
Alright, as @rileyjmurray suggested I took off `concatenate` from the main api for now, i.e `cp.concatenate` doesn't exist.  I think this is reasonable and must be enabled once this is fully supported. Also @Transurgeon I used numpy API for validation and shape set up.  Note same validation could be implemented in many cvxpy methods such as hstack or vstack.

Also would be nice to have custom errors to something like this `raise CustomCvxPyError from numpy_exc
` for having more info where the error is happening

2024-11-01 15:47 UTC, andresliszt commented on cvxpy/atoms/affine/concatenate.py
> +        )
this could be saved to a private attribute to be used below in `shape_from_args` but i don't think is worth it @Transurgeon

2024-11-01 15:53 UTC, Transurgeon approved these changes
I think this PR is ready for now. We will definitely come back to this at some future point to polish things and deal with the CPP backend. Thanks again @andresliszt

2024-11-01 16:39 UTC, SteveDiamond approved these changes

2024-11-01 16:47 UTC, andresliszt commented on cvxpy/atoms/affine/concatenate.py
> +        )
@SteveDiamond @Transurgeon  a con of this approach is that numpy error msgs have changed across different verisons.  I set up the tests with the error msgs i got locally with my specific numpy version. What do you suggest to handle this issue?

2024-11-01 16:58 UTC, Transurgeon commented on cvxpy/atoms/affine/concatenate.py
> +        )
Is it possible to just match the last part of the error message?
i.e. ``but along dimension 0, the array at index 0...``

2024-11-01 18:20 UTC, SteveDiamond commented
Looks like there are some test failures. This approach is fine for now, but we should do a follow up MR to ensure concatenate is not used with the CPP backend. It shouldn't be too difficult. Then we can add it back into the main namespace.

2024-11-01 18:22 UTC, SteveDiamond commented on cvxpy/atoms/affine/concatenate.py
> +        )
Yeah don't sweat it too much, whatever works and is at least testing there is an exception of some kind is fine.

2024-11-01 18:43 UTC, andresliszt commented on cvxpy/atoms/affine/concatenate.py
> +        )
ready to go !

2024-11-01 19:09 UTC, SteveDiamond commented
@andresliszt thanks for doing this!

2024-11-01 19:09 UTC, merged