`quantum_rel_entr`, `quantum_cond_entr` && CVXPY QI Marimo demo
cvxpy/cvxpy pull request #2606
Opened 2024-10-29 00:23 UTC by aryamanjeendgar

## Description
This PR implements two extremely important atoms for QI modelling: `quantum_rel_entr` and `quantum_cond_entr`. I also decided to write a Marimo notebook with excerpts from my thesis bringing together a bunch of really nice and cool QI problems that CVXPY is now capable of solving! (the notebook could definitely use an overhaul XD)

## Type of change
- [x] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [ ] Add our license to new files.
- [ ] Check that your code adheres to our coding style.
- [x] Write unittests.
- [x] Run the unittests and check that they’re passing.
- [x] Run the benchmarks to make sure your change doesn’t introduce a regression.

2024-10-29 00:28 UTC, SteveDiamond commented on cvxpy/tests/test_quantum_rel_entr.py
> +class Test_quantum_rel_entr:
Should be camel case "TestQuantumRelEntr"

2024-10-29 00:29 UTC, SteveDiamond commented on cvxpy/atoms/quantum_cond_entr.py
> +# if sys == 1
Delete old comments

2024-10-29 00:29 UTC, SteveDiamond commented
Thanks @aryamanjeendgar ! You may need to install the precommit https://www.cvxpy.org/contributing/index.html

2024-10-29 00:31 UTC, aryamanjeendgar commented on cvxpy/atoms/quantum_cond_entr.py
> +# if sys == 1
Whoops, sorry! There's a bunch of them --- will remove them when you're done with the first round of review!

2024-10-29 19:02 UTC, SteveDiamond commented on cvxpy/atoms/quantum_cond_entr.py
> +def quantum_cond_entr(rho, dim: list[int], sys=0):
Add types for rho and sys

2024-10-29 19:02 UTC, SteveDiamond commented
looks good overall. you can address all the comments then it is ok to merge.

2024-10-29 19:03 UTC, SteveDiamond commented
actually you need to fix syntax errors.

2024-10-30 16:47 UTC, aryamanjeendgar commented on cvxpy/atoms/quantum_cond_entr.py
> +# if sys == 1
Done!

2024-10-30 16:48 UTC, aryamanjeendgar commented on cvxpy/atoms/quantum_cond_entr.py
> +def quantum_cond_entr(rho, dim: list[int], sys=0):
Done!

2024-10-30 17:00 UTC, aryamanjeendgar commented
@SteveDiamond it looks like the python 3.9 builds are failing since I use a `match-case` in a helper function inside of `test_quantum_rel_entr.py` --- though it's an easy fix, I'm curious if we are targeting 3.9 support for the 1.6 release?

2024-10-30 17:20 UTC, SteveDiamond commented
> @SteveDiamond it looks like the python 3.9 builds are failing since I use a `match-case` in a helper function inside of `test_quantum_rel_entr.py` --- though it's an easy fix, I'm curious if we are targeting 3.9 support for the 1.6 release?

We are still targeting 3.9 support.

2024-11-04 18:47 UTC, SteveDiamond commented on cvxpy/tests/test_quantum_rel_entr.py
> -    def make_test_5():
Why are you deleting test 5?

2024-11-04 18:52 UTC, aryamanjeendgar commented on cvxpy/tests/test_quantum_rel_entr.py
> -    def make_test_5():
This test has kinda weird behaviour across different python versions --- I am comparing solutions against CVXQUAD (Matlab), and for my setup, the problem solves as unbounded but feasible --- whereas on some of the failing test runs I saw, it was outputting the correct CVXQUAD objective value --- even though with `verbose` on, the final primal value of the objective that I am shown is actually the correct objective value, before the solver jumps and outputs an unbounded objective.

I have a feeling the behaviour could be arising from the way I might have implemented some of the additional QI functionalities I needed for this test (like `applychan`)

2024-11-04 18:54 UTC, SteveDiamond commented on cvxpy/tests/test_quantum_rel_entr.py
> -    def make_test_5():
Ok that's fine.

2024-11-04 19:02 UTC, SteveDiamond commented on cvxpy/reductions/complex2real/canonicalizers/matrix_canon.py
> +    TODO: WRITE ME.
Can we put something here?

2024-11-04 19:05 UTC, aryamanjeendgar commented on cvxpy/reductions/complex2real/canonicalizers/matrix_canon.py
> +    TODO: WRITE ME.
Do you mean the `TODO`? I think this is just an old-dangling comment, can/should be removed

2024-11-04 19:06 UTC, SteveDiamond commented on cvxpy/reductions/complex2real/canonicalizers/matrix_canon.py
> +    TODO: WRITE ME.
But we could add a description of what is happening in the canonicalization.

2024-11-04 19:32 UTC, SteveDiamond commented on cvxpy/tests/test_quantum_rel_entr.py
> +        SOLVE_ARGS = {'solver': 'SCS', 'eps': 1e-6, 'max_iters': 500_000,
This is too many iterations. Should be at most 10k. It is taking too long in the CI.

2024-11-04 19:32 UTC, SteveDiamond commented on cvxpy/tests/test_quantum_rel_entr.py
> +        SOLVE_ARGS = {'solver': 'SCS', 'eps': 1e-6, 'max_iters': 500_000,
Clarabel handles SDP so you can use Clarabel.

2024-11-04 19:46 UTC, SteveDiamond commented on cvxpy/tests/test_quantum_rel_entr.py
> +        SOLVE_ARGS = {'solver': 'SCS', 'eps': 1e-6, 'max_iters': 500_000,
You need to change the arguments for Clarabel. You can delete eps and max_iters.

2024-11-05 01:51 UTC, SteveDiamond commented on cvxpy/tests/test_quantum_rel_entr.py
> +    SOLVE_ARGS = {'solver': 'MOSEK', 'verbose': True} if run_full_test_suite\
This is not quite right. test_1 and test_3 should use CLARABEL no matter what. test_2 and test_4 should only run if MOSEK is present, but in a very specific way. At the start of test_2 and test_4 add a check

```
if cp.MOSEK in cp.installed_solvers():
  run test
```

2024-11-05 01:52 UTC, SteveDiamond commented on cvxpy/tests/test_quantum_rel_entr.py
> +    SOLVE_ARGS = {'solver': 'MOSEK', 'verbose': True} if run_full_test_suite\
so the tests should always run no matter what, but test_2 and test_4 do nothing if mosek is not present

2024-11-05 01:52 UTC, SteveDiamond commented on cvxpy/tests/test_quantum_rel_entr.py
> +    SOLVE_ARGS = {'solver': 'MOSEK', 'verbose': True} if run_full_test_suite\
also @rileyjmurray if you can figure out how to make the tests all work with Clarabel that would be very helpful. but that can be a follow up PR.

2024-11-05 01:55 UTC, aryamanjeendgar commented on cvxpy/tests/test_quantum_rel_entr.py
> +    SOLVE_ARGS = {'solver': 'MOSEK', 'verbose': True} if run_full_test_suite\
Oh right --- as of now, `test_{2 | 4}` only run when MOSEK is installed (and the entire test suite is run on MOSEK) but if its not found then they are skipped and `test_{1 | 3}` are run with CLARABEL.

Let me make this change really quick

2024-11-06 03:31 UTC, rileyjmurray requested changes
I left a few minor comments. Should be good to merge once they're addressed.

2024-11-06 03:31 UTC, rileyjmurray commented on cvxpy/atoms/quantum_rel_entr.py
> +        """
I believe this constraint will be enforced by canonicalization, so no comment to this effect is necessary.

2024-11-06 03:31 UTC, rileyjmurray commented on cvxpy/atoms/quantum_rel_entr.py
> +                raise ValueError('Argument must be a square matrix.')
Replace this with checks that ``args[0].is_hermitian()`` and ``args[1].is_hermitian()``.

2024-11-06 03:31 UTC, rileyjmurray commented on cvxpy/atoms/quantum_rel_entr.py
> +        raise ValueError()
Raise NotImplementedError

2024-11-06 03:31 UTC, rileyjmurray commented on cvxpy/atoms/quantum_rel_entr.py
> +        return [self.args[0] >> 0]
We also need ``self.args[1] >> 0``.

2024-11-06 03:31 UTC, rileyjmurray commented on cvxpy/tests/test_quantum_rel_entr.py
> +        return sth
@aryamanjeendgar am I misunderstanding, or does this not rely on quantum relative entropy? Seems this test belongs in test_von_neumann_entr.py.

2024-11-06 03:31 UTC, rileyjmurray commented on cvxpy/reductions/complex2real/canonicalizers/matrix_canon.py
> +    #   problem. -- Riley
This comment can be removed. We've established the correct scaling with ``TestQuantumRelEntr::test_2``.

2024-11-06 03:31 UTC, rileyjmurray commented on cvxpy/reductions/complex2real/canonicalizers/matrix_canon.py
> +    TODO: WRITE ME.
This text will suffice
```
    """Transform Hermitian input for quantum_rel_entr into equivalent
    symmetric input for quantum_rel_entr.
    """
```

2024-11-06 03:31 UTC, rileyjmurray commented on cvxpy/tests/test_quantum_rel_entr.py
> +        return sth
@aryamanjeendgar am I misunderstanding, or does this not rely on quantum relative entropy? Seems this test belongs in test_von_neumann_entr.py.

2024-11-06 05:31 UTC, aryamanjeendgar commented on cvxpy/tests/test_quantum_rel_entr.py
> +        return sth
You're right! I put all of the problems from the Hamza paper in the notebook and didn't check --- thank you for the catch! This has been added to the `Test_von_neumann_entr` test-suite!

2024-11-06 05:33 UTC, aryamanjeendgar commented
@rileyjmurray Done! The latest commit should address all comments!

2024-11-07 18:57 UTC, Transurgeon commented
Is this ready to merge? I'd like to do the release today if possible :)

2024-11-07 18:59 UTC, aryamanjeendgar commented
> Is this ready to merge? I'd like to do the release today if possible :)
I believe so --- @rileyjmurray, is there anything else you'd want me to address?

2024-11-09 02:39 UTC, rileyjmurray commented
Aryaman's latest changes look good to me. Ready to merge!

2024-11-09 04:41 UTC, Transurgeon approved these changes

2024-11-09 04:43 UTC, merged