Enable derivative of dual variables w.r.t. problem parameters
cvxpy/cvxpy pull request #2631
Opened 2024-11-14 21:25 UTC by ericlux

## Description
Enable cp.Problem.derivative() to write deltas to the dual variables.
Issue link (if applicable): N/A

## Type of change
- [x] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [ ] Add our license to new files.
- [ ] Check that your code adheres to our coding style.
- [ ] Write unittests.
- [ ] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

2024-11-14 21:59 UTC, SteveDiamond commented on cvxpy/problems/problem.py
> +from cvxpy.reductions.solvers.conic_solvers import DIFFCP
We can't import DIFFCP here because it might not be installed.

2024-11-15 01:46 UTC, ericlux commented on cvxpy/problems/problem.py
> +from cvxpy.reductions.solvers.conic_solvers import DIFFCP
Moved into the derivative method, which can't be called without diffcp I believe

2024-11-21 05:49 UTC, PTNobel requested changes
Micellaneous unsubstantial concerns + some confusion about what's happening in the code. Some of this might be me not remembering what the derivative codepath in CVXPY is like.

2024-11-21 05:49 UTC, PTNobel commented on cvxpy/problems/problem.py
> +        diffcp = conic_solvers.DIFFCP()
Shouldn't there already be an instance of this class in the reduction chain? As the last reduction?

2024-11-21 05:49 UTC, PTNobel commented on cvxpy/problems/problem.py
> +        solution = {
What's happening with this dictionary? Is the use of SCS here necessary? I'm worried if we're breaking derivatives with Clarabel/ECOS support.

2024-11-21 05:49 UTC, PTNobel commented on cvxpy/problems/problem.py
> +        diffcp = conic_solvers.DIFFCP()
Could we have cached the solution instead?

2024-11-21 05:49 UTC, PTNobel commented on cvxpy/problems/problem.py
> +        solution = chain.invert(solution, inverse_data)
Huh, I'm surprised the chain doesn't have diffcp in it already; doesn't `requires_grad` require `solver=cp.DIFFCP`?

2024-11-21 05:49 UTC, PTNobel commented on cvxpy/problems/problem.py
> +        # dcons = {}
Style nit: no commented out code without like a good explanation for it

2024-11-21 05:49 UTC, PTNobel commented on cvxpy/problems/problem.py
> +            # variable.delta = solution.primal_vars[variable.id]
Same nit as above.

2024-11-21 05:49 UTC, PTNobel commented on cvxpy/reductions/inverse_data.py
> +
Should not be adding white space at the end of a line

2024-11-21 05:49 UTC, PTNobel commented on cvxpy/reductions/inverse_data.py
> +        return (id_map, var_offsets, vert_offset, var_shapes)
Please end your text files with a `\n`

2025-01-20 00:21 UTC, PTNobel commented on cvxpy/reductions/inverse_data.py
> +
```suggestion

```

2026-04-11 22:15 UTC, Transurgeon commented
I'll close this PR since its been a while. Let's revisit this if its still of interest at some point.

2026-04-11 22:15 UTC, closed without merging