Remove bounds setter in leaf replaced by validator
cvxpy/cvxpy pull request #2634
Opened 2024-11-15 21:32 UTC by andresliszt

## Description

Hello! I talked with @Transurgeon  to take this PR. It removes `bounds` setter on leaf as discussed [here](https://github.com/cvxpy/cvxpy/issues/2599). The setter logic was replaced by a validator and also added a test passing through the validator

## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [ ] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [ ] Add our license to new files.
- [ ] Check that your code adheres to our coding style.
- [ ] Write unittests.
- [ ] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

2024-11-15 21:57 UTC, Transurgeon requested changes
generally looks good and seems to be pretty clean with the internal function implementation, we can merge after addressing the comments.
Thanks @andresliszt !

2024-11-15 21:57 UTC, Transurgeon commented on cvxpy/tests/test_expressions.py
> +
can we move this to the file test_attributes.py?

2024-11-15 21:57 UTC, Transurgeon commented on cvxpy/expressions/leaf.py
> +
why did you have to move this?

2024-11-15 21:59 UTC, andresliszt commented on cvxpy/expressions/leaf.py
> +
because otherwise will fall in the lower bound >= upper bound error

2024-11-15 22:53 UTC, PTNobel approved these changes
Looks good to me once @Transurgeon 's comment is addressed

2024-11-15 23:09 UTC, andresliszt commented
I just moved the test location :)

2024-11-15 23:14 UTC, andresliszt commented
Oh i messed something in the unit test definition, will be updating this

2024-11-16 06:37 UTC, Transurgeon approved these changes

2024-11-16 06:37 UTC, merged