Bug fix: assigning values to sparse leafs
cvxpy/cvxpy pull request #2635
Opened 2024-11-17 02:49 UTC by maxschaller

## Description
This PR fixes a bug when assigning the value of a `Leaf` with the `sparsity` attribute. Previously, the `_validate_value` function was demanding that the shape of the assigned value is the same as the shape of the `Leaf`. At the same time, the `project` function is expecting the value to be a flat array of only the nonzero entries. This PR eliminates this contradiction and changes `_validate_value` such that the value can be passed as a flat array. This is relevant especially for `Parameter` with `sparsity` (as used by `cvxpygen`, for example).

No benchmarks were run because it seems they disappeared from `cvxpy/tests`. The [contributing guide](https://github.com/cvxpy/cvxpy/blob/master/CONTRIBUTING.md#benchmarks) still refers to `cvxpy/tests/test_benchmarks.py`.

## Type of change
- [ ] New feature (backwards compatible)
- [ ] New feature (breaking API changes)
- [x] Bug fix
- [ ] Other (Documentation, CI, ...)

## [Contribution checklist](https://www.cvxpy.org/contributing/index.html#contribution-checklist)
- [x] Add our license to new files.
- [x] Check that your code adheres to our coding style.
- [x] Write unittests.
- [x] Run the unittests and check that they’re passing.
- [ ] Run the benchmarks to make sure your change doesn’t introduce a regression.

2024-11-17 17:39 UTC, Transurgeon approved these changes
LGTM thanks for addressing this issue with the new sparsity attribute!
Do you think it would be worth allowing users to specify a sparse value with a sparse array at some point? (The only issue would be when users deal with 3d variables or greater, we might need to create a custom datatype to support this).

2024-11-17 17:43 UTC, Transurgeon commented
also about the benchmarks, the contributing guide in the repo is outdated..
we have a benchmarks [repo](https://github.com/cvxpy/benchmarks) that gets run on every PR.
I think the contributing guide on the [docs](https://www.cvxpy.org/contributing/index.html#benchmarks) reflects this.

2024-11-17 18:42 UTC, maxschaller commented
> LGTM thanks for addressing this issue with the new sparsity attribute! Do you think it would be worth allowing users to specify a sparse value with a sparse array at some point? (The only issue would be when users deal with 3d variables or greater, we might need to create a custom datatype to support this).

I think so, yes. Currently, if a user wants to assign a `scipy.sparse.csc_matrix` S to a sparse `Parameter` P, they can simply say `P.value = S.data`. If their sparse array is row-major or nd, then things are less simple. I guess this would go into a separate PR.

2024-11-17 19:55 UTC, maxschaller commented
The new design expects a numpy nd array. This generalizes to any number of dimensions, and is closer to the previous API.

2024-11-17 22:32 UTC, Transurgeon commented
> The new design expects a numpy nd array. This generalizes to any number of dimensions, and is closer to the previous API.

hmm I think this is great with minimal changes. But then we are not able to do what you mentioned above with setting ``P.value = S.data``. Let's get back to this in another PR though. 
Like you said, this fixes a current bug with setting parameter values of sparse leaves.
@SteveDiamond , what do you think about this?

2024-11-18 06:27 UTC, PTNobel commented
I'll write a design doc tomorrow

2024-12-03 04:15 UTC, SteveDiamond approved these changes

2024-12-03 21:29 UTC, PTNobel commented
Design doc is here: https://github.com/PTNobel/PTNobel/blob/main/cvxpy_design_docs/sparsity-api.md

Decision was to go with Option 3, but raise a warning if we're accessing a sparse variable through its dense representation.

2024-12-06 02:43 UTC, PTNobel commented
@maxschaller @SteveDiamond @Transurgeon if y'all want to look at this PR, and confirm you're okay with this approach, I'll write tests tomorrow or the weekend.

2024-12-06 18:56 UTC, Transurgeon commented on cvxpy/expressions/leaf.py
> +            return self._value
shouldn't this return val?

2024-12-06 18:56 UTC, Transurgeon commented on cvxpy/expressions/leaf.py
> +                          ' Use `.value_sparse` instead', RuntimeWarning, 3)
nice, was just curious what the parameter 3 does? Is it for the stack trace? Why is it different than the warning below?

2024-12-06 18:56 UTC, Transurgeon commented on cvxpy/expressions/leaf.py
> +                             f'type should be {scipy_coo_array_name}')
we should add some documentation so the users knows how to define a ``cvxpy.compat.scipy_coo_array``.
Also im concerned that we are gonna get errors for ``invalid attribute coords``. does a numpy array have a coords attribute?

2024-12-06 19:24 UTC, maxschaller commented on cvxpy/expressions/leaf.py
> +            val[self.sparse_idx] = self._value[self.sparse_idx]
Given that `self._value` holds only the nonzeros, shouldn't we say

`val[self.sparse_idx] = self._value`

2024-12-06 19:37 UTC, maxschaller commented on cvxpy/expressions/leaf.py
>              new_val = np.zeros(self.shape)
This seems to assign a dense array to `self._value`. I think if we want to avoid storing a dense array, we should warn here if there are nonzeros outside of the pattern, return just `val[self.sparse_idx]`, and bypass the `delta` check in `_validate_value`.

2024-12-06 19:46 UTC, maxschaller commented on cvxpy/expressions/leaf.py
> +        self.save_value(self._validate_value(val.data, True))
How about we say

`self.save_value(self._validate_value(val, True).data)` 

This way, the shape check inside `_validate_value` still works. Inside `project`, we could add another case under `self.attributes['sparsity']` that just passes `val` through if `sparse_path=True`.

2024-12-06 21:18 UTC, PTNobel commented on cvxpy/expressions/leaf.py
> +            return self._value
Yes. Yes it should.

2024-12-06 21:18 UTC, PTNobel commented on cvxpy/expressions/leaf.py
> +                          ' Use `.value_sparse` instead', RuntimeWarning, 3)
It is for the stack trace, the 3 means that it goes up above this function into self._validate_value and then up from there to .value

2024-12-06 21:19 UTC, PTNobel commented on cvxpy/expressions/leaf.py
> +                             f'type should be {scipy_coo_array_name}')
Definitely need to write some docs. We should check for a NumPy array first.

2024-12-06 21:20 UTC, PTNobel commented on cvxpy/expressions/leaf.py
> +            val[self.sparse_idx] = self._value[self.sparse_idx]
Yes. Yes we should.

2024-12-06 21:21 UTC, PTNobel commented on cvxpy/expressions/leaf.py
>              new_val = np.zeros(self.shape)
Hmmm so you think we should move the warning up too? Can you comment where you want it?

2024-12-06 21:22 UTC, PTNobel commented on cvxpy/expressions/leaf.py
> +        self.save_value(self._validate_value(val.data, True))
I think that we will break some of the other code and we want to allow mixing attributes other than PSD/NSD and sparse I think

2024-12-06 22:37 UTC, maxschaller commented on cvxpy/expressions/leaf.py
>              new_val = np.zeros(self.shape)
Agreed, let's move it to the `value` setter.

2024-12-06 22:40 UTC, maxschaller commented on cvxpy/expressions/leaf.py
> +        self.save_value(self._validate_value(val.data, True))
Hmm I see. Maybe we'll need to skip or check the shape differently.

2024-12-07 06:45 UTC, PTNobel commented on cvxpy/expressions/leaf.py
> +                             f'type should be {scipy_coo_array_name}')
Wait we have a type check first? If it isn't a known good type, then we error about the types.

2024-12-28 06:31 UTC, PTNobel commented
@maxschaller were you going to do the docs?

2024-12-28 07:00 UTC, PTNobel commented
Update: I need to figure out what's happening with `cvxpy.interface` to figure out the most maintainable approach here.

2024-12-29 17:50 UTC, Transurgeon commented
> Update: I need to figure out what's happening with `cvxpy.interface` to figure out the most maintainable approach here.

are we planning to support both ``sp.*_matrix`` and ``sp.*_array``? My feeling is yes.
But then we need to think about compatibility between the two. I feel like we can replicate the code for numpy arrays and matrices in the interface. (also we can probably remove any instance of ``np.matrix`` as it is officially deprecated).

2024-12-30 00:28 UTC, PTNobel commented
> are we planning to support both sp.*_matrix and sp.*_array? My feeling is yes.

My preference is *no*, we should only support `sp.coo_array`.

1. `coo_array` has nearly the same internal data structure as our API: I think this is really valuable for helping us be flexible on changes to our implementation as we still finish it. 
2. `coo_array` is the only nD sparse format in scipy so far.

2025-01-03 23:23 UTC, Transurgeon commented
> My preference is _no_, we should only support `sp.coo_array`.
> 
> 1. `coo_array` has nearly the same internal data structure as our API: I think this is really valuable for helping us be flexible on changes to our implementation as we still finish it.
> 2. `coo_array` is the only nD sparse format in scipy so far and I think we should be nd first.

Just to clarify, I meant from the users perspective, since we currently support ``*_matrix`` as sparse constants, we would need to atleast raise a warning before deprecating it right? Otherwise, I agree with you that internally we should replace all instances of ``*_matrix`` to ``*_array`` in the backend.

2025-01-03 23:27 UTC, Transurgeon commented
I think the next steps for this feature are the following:
1. add docs (I guess we can add a small section next to the sparsity attribute [docs](https://www.cvxpy.org/tutorial/constraints/index.html#sparsity-attribute))
2. figure out what's going on in cvxpy.interface, some WiP in #2663 , maybe we should merge that PR first
3. add more tests to this PR then merge

What are your thoughts?

2025-01-04 15:28 UTC, maxschaller commented
My suggestion for a small section next to the sparsity attribute [docs](https://www.cvxpy.org/tutorial/constraints/index.html#sparsity-attribute):

**Reading and writing the value of a variable or parameter with the sparsity attribute**

To avoid storing entries that are known to be zero, we provide the `.value_sparse` field, which stores only the nonzero entries as a `scipy.sparse.coo_array`. For details on this data structure, please see the [scipy documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_array.html). When passing a value, it is expected to be a `scipy.sparse.coo_array`.

```
sparsity = ([0, 1, 2, 2], [0, 2, 1, 2])
P = cp.Parameter((3, 3), sparsity=sparsity)
P.value_sparse = coo_array(([1.3, 2.1, 0.7, 3.2], sparsity))
```

Similarly, the value of a sparse variable or parameter is read via `.value_sparse`.

```
X = cp.Variable((3, 3), sparsity=[(0, 1), (0, 2)])
prob = cp.Problem(cp.Minimize(cp.sum(X)), [...])
prob.solve()
print(X.value_sparse)
```

2025-01-13 00:17 UTC, Transurgeon requested changes
Just had a few suggestions for doc improvements @maxschaller , otherwise this PR looks ready to merge to me. I think the stuff about the scipy.sparse_array interface can maybe be done in another PR. 

Just to make sure, does the changes in this PR fix the existing issue with the sparsity attribute not being compatible with cvxpygen? 

Pinging @PTNobel and @SteveDiamond for your approval as well.

2025-01-13 00:17 UTC, Transurgeon commented on doc/source/tutorial/constraints/index.rst
> +Reading and writing the value of a variable or parameter with the sparsity attribute:
```suggestion
Reading and writing the value of a sparse expression
----------------------------------------------------
```

2025-01-13 00:17 UTC, Transurgeon commented on doc/source/tutorial/constraints/index.rst
> +When passing a value, it is expected to be a ``scipy.sparse.coo_array``.
```suggestion
For details on this data structure, please see the `SciPy documentation <https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_array.html>`_.
When passing a sparse value, it is expected to be a ``scipy.sparse.coo_array``.
```

2025-01-13 00:17 UTC, Transurgeon commented on doc/source/tutorial/constraints/index.rst
> +    P.value_sparse = coo_array(([1.3, 2.1, 0.7, 3.2], sparsity))
```suggestion
    data = [1.3, 2.1, 0.7, 3.2]
    P = cp.Parameter((3, 3), sparsity=sparsity)
    P.value_sparse = coo_array((data, sparsity))
```

2025-01-20 00:23 UTC, PTNobel commented
I'm going to add sparse matrix support and then do a full review and hopefully merge.

2025-01-20 21:39 UTC, maxschaller commented
I wrote a couple more tests and fixed some bugs. Since the `value` getter and setter of the `Paramteter` class would override those of the `Leaf` class, they are commented out until @PTNobel will have a closer look.

2025-01-21 22:38 UTC, PTNobel requested changes
Just one thing that I consider blocking. I'm investigating what caused this issue.

2025-01-21 22:38 UTC, PTNobel commented on cvxpy/expressions/constants/parameter.py
> +    #    self._value = self._validate_value(val)
Blocked on deciding whether to just delete this setter and getter

2025-01-22 00:11 UTC, PTNobel approved these changes

2025-01-22 17:28 UTC, SteveDiamond approved these changes
lgtm

2025-01-23 15:03 UTC, Transurgeon approved these changes
LGTM, we can merge after addressing Steven's comment above. 

Quick question though, don't we need to add changes to the matrix [interface](https://github.com/cvxpy/cvxpy/tree/master/cvxpy/interface) too?

2025-01-23 17:41 UTC, PTNobel commented
Quick question though, don't we need to add changes to the matrix interface too?

I believe that was only necessary if we wanted to get rid of the `sparse_path` parameter. But I'm convinced it's worth keeping.

2025-01-23 17:41 UTC, merged